const MAGAZINE='https://note.com/ss_yr/m/mf8a55ef40b9d';
const RECRUIT='https://note.com/ss_yr/n/nf34d092b4032';
const app=document.getElementById('app');
const modal=document.getElementById('modal');
const modalbox=document.getElementById('modalbox');
const toast=document.getElementById('toast');
const creators=[
{id:1,name:'星詠みアカリ',job:'物語召喚士',attrs:['星','言霊'],icon:'✦',intro:'夜空のような物語と、読み手の心に残る言葉を紡ぐクリエイター。',wins:18,views:1240},
{id:2,name:'蒼羽ミオ',job:'共感の導き手',attrs:['水','支援'],icon:'❖',intro:'日常の気づきをやさしい言葉へ変え、読者とつながるクリエイター。',wins:11,views:980},
{id:3,name:'炎筆リン',job:'企画錬金術師',attrs:['炎','創作'],icon:'✺',intro:'企画と行動力で場を動かす、攻めの発信を得意とするクリエイター。',wins:24,views:1670}
];
const pending=[
{name:'仮登録クリエイターA',type:'新規申請',mag:true},
{name:'仮登録クリエイターB',type:'記事更新',mag:true}
];
function route(name){history.replaceState(null,'','#'+name);render(name)}
function bind(){document.querySelectorAll('[data-route]').forEach(el=>el.onclick=()=>route(el.dataset.route))}
function btn(text,routeName,cls=''){return `<button class="btn ${cls}" data-route="${routeName}">${text}</button>`}
function home(){return `<section class="hero"><div><div class="eyebrow">Creator Discovery × Card Battle</div><h1>冒険するように、<br>クリエイターと出会う。</h1><p>1人につき3枚のイラストと2本のnote記事を掲載。専用ページで活動を紹介し、カード対戦をきっかけに、まだ知らないクリエイターへつながる参加型名鑑です。</p><div class="actions">${btn('名鑑を見る','directory','primary')}${btn('対戦を試す','battle')}<a class="btn" href="${RECRUIT}" target="_blank" rel="noopener">参加方法を見る</a><a class="btn" href="${MAGAZINE}" target="_blank" rel="noopener">専用マガジン</a></div></div><div class="showcase"><article class="card one"><div class="art">✦</div><h3>星詠みアカリ</h3><div class="meta">LEGEND SSR・物語召喚士</div></article><article class="card two"><div class="art">❖</div><h3>蒼羽ミオ</h3><div class="meta">DREAM SSR・共感の導き手</div></article></div></section><section class="section"><div class="eyebrow">HOW IT WORKS</div><h2>名鑑・記事・ゲームがひとつにつながる</h2><p class="lead">対戦の勝ち負けだけが目的ではありません。対戦後に相手の専用ページやnote記事を読める設計にし、新しい交流の入口を作ります。</p><div class="grid"><div class="panel"><div class="stat">3</div><h3>イラスト</h3><p class="lead">メインカードとサブイラストを最大3枚掲載。</p></div><div class="panel"><div class="stat">2</div><h3>note記事</h3><p class="lead">おすすめ記事を最大2本まで紹介。</p></div><div class="panel"><div class="stat">1</div><h3>専用ページ</h3><p class="lead">一人ひとりに紹介ページを用意。</p></div></div></section>`}
function directory(){return `<section class="section"><div class="eyebrow">CREATOR DIRECTORY</div><h2>参加クリエイター名鑑</h2><p class="lead">名前・職業・属性・記事から検索し、各種順番で表示できる本番仕様を予定しています。</p><div class="actions"><input id="search" placeholder="クリエイター名・職業・属性を検索" style="flex:1;min-width:240px;padding:13px;border-radius:12px;border:1px solid var(--line);background:#09111f;color:white"><select id="sort" class="btn"><option value="id">名鑑番号順</option><option value="name">名前順</option><option value="wins">勝利数順</option><option value="views">閲覧数順</option></select></div><div class="directory" id="cards"></div></section>`}
function drawCards(list=creators){document.getElementById('cards').innerHTML=list.map(c=>`<article class="profile"><div class="thumb">${c.icon}</div><div class="body"><div class="eyebrow">NO.${String(c.id).padStart(3,'0')}</div><h3>${c.name}</h3><p>${c.job}</p><div class="tags">${c.attrs.map(x=>`<span class="tag">${x}</span>`).join('')}</div><p class="lead">${c.intro}</p><button class="btn primary" onclick="showProfile(${c.id})">専用ページを見る</button></div></article>`).join('')}
function battle(){return `<section class="section"><div class="eyebrow">CARD BATTLE</div><h2>対戦相手を選ぶ</h2><p class="lead">見本版では3ターンの簡易対戦を体験できます。本番では能力値・固有スキル・対戦履歴をサーバー側で管理します。</p><div class="directory">${creators.map(c=>`<article class="profile"><div class="thumb">${c.icon}</div><div class="body"><h3>${c.name}</h3><p>${c.job}</p><button class="btn primary" onclick="startBattle(${c.id})">この相手と対戦</button></div></article>`).join('')}</div></section>`}
function apply(){return `<section class="section"><div class="eyebrow">ENTRY FORM</div><h2>名鑑への参加申請</h2><p class="lead">本番ではログイン後、自分の内容を登録・更新できます。変更時もオーナー承認後に公開されます。</p><div class="panel form"><label>クリエイター名</label><input placeholder="noteで使用している名前"><label>noteプロフィールURL</label><input placeholder="https://note.com/..."><label>自己紹介</label><textarea placeholder="活動内容や得意分野を紹介してください"></textarea><label>イラスト</label><input type="file" multiple accept="image/*"><p class="lead">最大3枚まで</p><label>おすすめnote記事1</label><input placeholder="記事URL"><label>おすすめnote記事2</label><input placeholder="記事URL"><label class="check"><input type="checkbox" checked><span>登録記事を専用マガジンへの掲載候補として申請する</span></label><label class="check"><input type="checkbox"><span>カード対戦への参加を希望する</span></label><label class="check"><input type="checkbox"><span>画像・文章の使用権限を持ち、名鑑および対戦演出での利用に同意する</span></label><button class="btn primary" onclick="demoSubmit()">承認申請を送る</button></div></section>`}
function owner(){return `<section class="section"><div class="eyebrow">OWNER CONSOLE</div><h2>オーナー管理</h2><div class="notice">見本画面です。本番ではオーナーでログインした場合のみ表示されます。</div><div class="panel" style="margin-top:20px">${pending.map((p,i)=>`<div class="ownerrow"><div><b>${p.name}</b><p class="lead">${p.type}・マガジン掲載希望：${p.mag?'あり':'なし'}</p></div><div class="actions"><button class="btn" onclick="review(${i})">内容確認</button><button class="btn primary" onclick="approve(${i})">承認</button></div></div>`).join('')}</div><div class="grid"><div class="panel"><div class="stat">2</div><h3>未承認</h3></div><div class="panel"><div class="stat">2</div><h3>マガジン追加待ち</h3></div><div class="panel"><div class="stat">0</div><h3>通報</h3></div></div></section>`}
function render(name){if(name==='directory'){app.innerHTML=directory();drawCards();const s=document.getElementById('search'),o=document.getElementById('sort');const update=()=>{let list=creators.filter(c=>(c.name+c.job+c.attrs.join('')).includes(s.value));list=[...list].sort((a,b)=>o.value==='name'?a.name.localeCompare(b.name,'ja'):o.value==='wins'?b.wins-a.wins:o.value==='views'?b.views-a.views:a.id-b.id);drawCards(list)};s.oninput=update;o.onchange=update}else if(name==='battle')app.innerHTML=battle();else if(name==='apply')app.innerHTML=apply();else if(name==='owner')app.innerHTML=owner();else app.innerHTML=home();bind();scrollTo({top:0,behavior:'smooth'})}
window.showProfile=id=>{const c=creators.find(x=>x.id===id);modalbox.innerHTML=`<div class="eyebrow">CREATOR PAGE</div><h2>${c.name}</h2><div class="art" style="height:260px">${c.icon}</div><h3>${c.job}</h3><p class="lead">${c.intro}</p><div class="tags">${c.attrs.map(x=>`<span class="tag">${x}</span>`).join('')}</div><div class="grid" style="grid-template-columns:repeat(2,1fr)"><div class="panel"><h3>おすすめ記事1</h3><p class="lead">記事タイトルの見本</p><a class="btn" href="${MAGAZINE}" target="_blank">記事を読む</a></div><div class="panel"><h3>おすすめ記事2</h3><p class="lead">記事タイトルの見本</p><a class="btn" href="${MAGAZINE}" target="_blank">記事を読む</a></div></div><div class="actions"><button class="btn primary" onclick="closeModal();route('battle')">このカードで対戦</button><button class="btn" onclick="closeModal()">閉じる</button></div>`;modal.classList.add('open')}
window.closeModal=()=>modal.classList.remove('open');modal.onclick=e=>{if(e.target===modal)closeModal()}
window.startBattle=id=>{const c=creators.find(x=>x.id===id),win=Math.random()>.45;modalbox.innerHTML=`<div class="eyebrow">BATTLE RESULT</div><h2>${win?'VICTORY':'DEFEAT'}</h2><div class="art" style="height:230px">${c.icon}</div><p class="lead">${c.name}との3ターン対戦が終了しました。</p><div class="notice">対戦後は、相手の活動やnote記事を見に行けます。</div><div class="actions"><button class="btn primary" onclick="closeModal();showProfile(${id})">相手の専用ページ</button><a class="btn" href="${MAGAZINE}" target="_blank">専用マガジン</a><button class="btn" onclick="closeModal()">閉じる</button></div>`;modal.classList.add('open')}
window.demoSubmit=()=>showToast('見本申請を受け付けました。オーナー承認待ちになります。');window.review=i=>showToast(`${pending[i].name}の申請内容を確認`);window.approve=i=>showToast(`${pending[i].name}を承認しました。マガジン追加待ちに登録します。`);function showToast(t){toast.textContent=t;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2800)}
render(location.hash.slice(1)||'home');