import {candidateAvailability,selectionConflicts} from './compatibility.js?v=20.0.0';
import {appendRecipeEvidence} from './recipe-evidence.js?v=20.0.0';
import {productionPlan,repairPrompt} from './production-plan.js?v=20.0.0';
import {stagePrompts} from './production-workflow.js?v=20.0.0';
import {createLayoutPanel} from './layout-export.js?v=20.0.0';
import {applyPose} from './poses.js?v=20.0.0';
import {applyCollection,dailyInspiration} from './collection.js?v=20.0.0';
import {setupEffects} from './effects.js?v=20.0.0';
import {colorWorlds} from './worlds.js?v=20.0.0';
import {mergeCreator} from './creator.js?v=20.0.0';
import {createCropEditor} from './crop-editor.js?v=20.0.0';
import {profileForArtwork} from './activity-settings.js?v=20.0.0';
import {createPicker} from './picker.js?v=20.0.0';
import {modeKeys,modeCopy,initialSelections,effectiveSelections,propose} from './modes.js?v=20.0.0';
import {buildReferenceBoard} from './guide-board.js?v=20.0.0';
import {profileEndpoint,profileHeaders} from './runtime-config.js?v=20.0.0';
import {questions,visibleQuestions,defaults,AUTO,normalizeCreator,resolveSelections} from './catalog.js?v=20.0.0';
import {composePrompt,needsReference} from './prompt.js?v=20.0.0';
import {buildDirection} from './direction.js?v=20.0.0';
import {sampleFor,typePreview} from './examples.js?v=20.0.0';
import {makeZip} from './zip.js?v=20.0.0';
import {imageDeliveryRepairPrompt} from './output-contract.js?v=20.0.0';
import {editorialReferencesFor} from './editorial-reference-sources.js?v=20.0.0';
const APP_VERSION=20;
const $=id=>document.getElementById(id),STORAGE='mumeis-halloween-v2';
let saved={history:[],used:[],count:0},view='auto';
try{const v=JSON.parse(localStorage.getItem(STORAGE)||'null');if(v&&Array.isArray(v.history)&&Array.isArray(v.used))saved={history:v.history.map(r=>({...r,values:{pose:AUTO,line:AUTO,...r?.values}})).filter(x=>x&&typeof x.prompt==='string'&&x.values&&questions.every(q=>typeof x.values[q.key]==='string')&&x.variant&&x.profile&&Array.isArray(x.references)).slice(0,12),used:v.used.filter(x=>x&&typeof x.signature==='string').slice(-2000),count:Number.isSafeInteger(v.count)?v.count:0};view=localStorage.getItem('halloween-view')||'auto';}catch{}
let selections=initialSelections(),refs=[],activeQuestion=null,currentResult=null,adding=false,creating=false,loadedProfile=null,profileController=null,toastTimer,textPart='type';
let disposeLayoutPreview=()=>{};
try{
 if(!localStorage.getItem(STORAGE)){
 const old=JSON.parse(localStorage.getItem('mumeis-halloween-v1')||'null');
 if(old?.history?.length){saved.count=Number.isSafeInteger(old.count)?old.count:0;saved.history=old.history.filter(r=>r&&typeof r.prompt==='string'&&r.values&&typeof r.values.size==='string'&&r.variant&&Array.isArray(r.references)).slice(0,12).map(r=>({...r,legacy:true,values:{pose:AUTO,line:AUTO,...r.values},profile:{displayName:'旧版 / '+r.creator,biography:'',topics:[]},variant:{...r.variant,face:r.variant.angle,distance:'旧版の演出'}}));}
 }
}catch{}
const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
const rng=()=>{const b=new Uint32Array(1);crypto.getRandomValues(b);return b[0]/4294967296;};
const uid=()=>Date.now().toString(36).toUpperCase()+'-'+crypto.getRandomValues(new Uint32Array(1))[0].toString(36).toUpperCase();
const tell=s=>{$('toast').textContent=s;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),4500);};
function persist(){try{localStorage.setItem(STORAGE,JSON.stringify(saved));}catch{tell('端末への履歴保存ができません。制作セットを保存してください。');}}
function syncSaved(){try{const v=JSON.parse(localStorage.getItem(STORAGE)||'null');if(v&&Array.isArray(v.used)){saved.used=[...new Map([...saved.used,...v.used.filter(x=>x&&typeof x.signature==='string')].map(x=>[x.signature,x])).values()].slice(-2000);saved.count=Math.max(saved.count,Number.isSafeInteger(v.count)?v.count:0);}}catch{}}
function displayValue(q,v){return q.key==='size'?v.split('｜')[0]:v;}
function sampleNode(key,value){
 const sample=sampleFor(key,value),n=el('span','sample-thumb'+(key==='design'?' design-sample':''));
 n.setAttribute('role','img');n.setAttribute('aria-label',sample.label+'：'+value);n.title=sample.label;
 const image=(src,cls='sample-image')=>{const img=el('img',cls);img.src=src;img.alt='';img.loading='lazy';img.decoding='async';return img;};
 if(sample.kind==='image')n.append(image(sample.src));
 else if(sample.kind==='reference'){
 const ref=refs.find(r=>r.role==='identity');if(ref)n.append(image(ref.url));else n.append(el('span','sample-text','添付から\nつくる'));
 n.append(el('span','sample-caption','主参照を生かす'));
 }else if(sample.kind==='line'){
 n.className+=' line-sample';n.append(image(sampleFor('medium','実写風フィルム写真').src));
 if(sample.text)n.append(el('span','sample-line',sample.text));else n.append(el('span','sample-caption','セリフなし'));
 }else if(sample.kind==='size'){
 n.className+=' size-sample';const frame=el('span','size-frame');
 if(sample.ratio>=1){frame.style.width='88%';frame.style.aspectRatio=String(sample.ratio);}else{frame.style.height='88%';frame.style.aspectRatio=String(sample.ratio);}
 frame.append(image(sampleFor('design','通常の一枚絵').src));n.append(frame);
 }else if(sample.kind==='type'){
 const plan=typePreview(sample.mode);n.className+=' type-sample '+plan.className;
 if(!plan.className.includes('news'))n.append(image(sampleFor('design','通常の一枚絵').src));
 const copy=el('span','type-copy');plan.blocks.forEach((s,i)=>copy.append(el('span','type-block block-'+i,s)));n.append(copy);
 }else if(sample.kind==='auto'&&sample.srcs.length){
 const grid=el('span','auto-sample-grid');sample.srcs.forEach(src=>grid.append(image(src)));n.append(grid,el('span','sample-caption',key==='mood'?'毎回、表情も角度も':'おまかせの一例'));
 }else n.append(el('span','sample-text',sample.text));
 return n;
}
let boardArtKey='',attachmentMode='bundle';const effects=setupEffects();
let collection='halloween',collectionSnapshots={},mode='detail',modeSnapshots={detail:{...selections}},proposals=[],selectedProposal=null;
let activityEnabled=true,excludedTopics=new Set(),ideaSnapshot=null,ideaApplied=null;
const cropEditor=createCropEditor({$,tell,onApply:async(ref,edit)=>{if(!refs.includes(ref))return;const originalFile=ref.originalFile||ref.file;const url=URL.createObjectURL(edit.file),im=new Image();try{await new Promise((resolve,reject)=>{im.onload=resolve;im.onerror=()=>reject(new Error('編集画像を開けませんでした。'));im.src=url;});URL.revokeObjectURL(ref.url);Object.assign(ref,{originalFile,file:edit.file,url,name:edit.file.name,width:im.naturalWidth,height:im.naturalHeight,crop:edit.crop});renderRefs();}catch(e){URL.revokeObjectURL(url);throw e;}}});
function renderChoices(picked){
 const existing=new Map([...$('choices').children].map(b=>[b.dataset.key,b])),nodes=[];visibleQuestions.forEach((q,i)=>{if(!modeKeys[mode].includes(q.key))return;const stamp=collection+'|'+q.name+'|'+selections[q.key]+(q.key==='type'?'|'+selections.line:'')+'|'+(q.key==='costume'?refs.find(r=>r.role==='identity')?.url||'':'');const old=existing.get(q.key);if(old?.dataset.stamp===stamp){old.classList.remove('just-picked');nodes.push(old);return;}const b=el('button','choice'+(picked===q.key?' just-picked':''));b.type='button';b.dataset.key=q.key;b.dataset.stamp=stamp;b.setAttribute('aria-haspopup','dialog');b.setAttribute('aria-label',q.name+'：'+displayValue(q,selections[q.key])+'。選択を変更');
 const copy=el('span','choice-content');copy.append(el('span','choice-name',String(i+1).padStart(2,'0')+' / '+q.name),el('b','choice-value',displayValue(q,selections[q.key])),el('span','choice-hint',q.key==='type'?'セリフ：'+selections.line:q.hint));b.append(copy,sampleNode(q.key,selections[q.key]),el('span','choice-plus','＋'));b.addEventListener('click',()=>openPicker(q));nodes.push(b);});$('choices').replaceChildren(...nodes);renderBoard(mode==='auto'&&selectedProposal?{...selectedProposal,size:selections.size}:selections);syncActivity();
}
const paletteColors={'漆黒 × 琥珀 × 象牙':['#171513','#db7d20','#f4ebd4'],'深紅 × 黒 × 古金':['#811722','#171513','#b79538'],'群青 × 月白 × 銀':['#263774','#f1f5fc','#bbc5d1'],'紫 × 黒 × 酸性グリーン':['#623084','#171513','#d7ed26'],'藍墨 × 朱 × 和紙の白':['#263d51','#c54022','#ebe4d7'],'桃色 × 墨黒 × 真珠':['#ec92b6','#262122','#f1eaed'],'墨一色':['#141414','#707070','#f3f1eb'],'モノクローム':['#191919','#777','#eee'],'セピア':['#533e26','#ab8353','#e7caa2']};
colorWorlds.forEach(x=>paletteColors[x.value]=x.colors);
function renderBoard(values=selections,variant=null){
 const name=$('creator-name').value.trim();$('stage-id').textContent=name||'YOUR NAME';
 $('stage-line').textContent=values.type==='文字を一切入れない'||values.line==='セリフなし'?'':values.line===AUTO?(collection==='everyday'?'今日の景色を、一枚に。':'まだ見ぬ、一夜へ。'):values.line;
 $('direction-title').textContent=values.theme===AUTO?'物語は、これから。':values.theme;$('direction-medium').textContent=values.medium+' / '+values.design;$('format-badge').textContent=values.size.split('｜')[2]||'おまかせ';
 $('direction-tags').replaceChildren(...[values.costume,values.mood,values.place].map(v=>el('span',null,v)));
 $('swatches').replaceChildren(...(paletteColors[values.palette]||['#f97818','#19120e','#fff6e9']).map(c=>{const n=el('span');n.style.background=c;return n;}));
 $('variant-summary').replaceChildren(el('b',null,'✦'),el('p',null,variant?[variant.face,variant.expression,variant.distance,variant.depth,variant.motion].join('\n'):'キャラは表情・動きを変え、風景は視点と奥行きで構図をつくります。'));
 $('issue-number').textContent='No. '+String(saved.count+1).padStart(3,'0');const artKey=JSON.stringify(['design','medium','theme','costume','palette'].map(k=>values[k]));if(artKey!==boardArtKey){boardArtKey=artKey;$('board-samples').replaceChildren(sampleNode('design',values.design),sampleNode('medium',values.medium));renderHangingGallery(values);}
}
function setView(mode){if(!['auto','phone','tablet','pc'].includes(mode))mode='auto';view=mode;document.body.dataset.view=mode;document.querySelectorAll('.view-switch button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===mode)));$('view-status').textContent={auto:'画面幅に合わせて表示',phone:'スマホの幅・大きな文字',tablet:'タブレットの幅・大きな選択枠',pc:'PCの幅・広い作業スペース'}[mode];try{localStorage.setItem('halloween-view',mode);}catch{}}
const picker=createPicker({$,el,sampleNode,readSelection:()=>selections,choose,onCustom:buildCustom,tell});
function openPicker(q){const text=q.key==='type'||q.key==='line';if(text){if(q.key==='line')textPart='line';q=questions.find(x=>x.key===textPart);}$('text-subtabs').hidden=!text;document.querySelectorAll('[data-text-part]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.textPart===q.key)));activeQuestion=q;const i=visibleQuestions.findIndex(x=>x.key===(q.key==='line'?'type':q.key));$('picker-index').textContent=String(i+1).padStart(2,'0')+' / 10';picker.open(q);}
function buildCustom(q){const form=el('form','custom-form');if(q.key==='size'){const w=el('input'),h=el('input');w.type=h.type='number';w.min=h.min='256';w.max=h.max='16000';w.required=h.required=true;w.placeholder='幅px';h.placeholder='高さpx';w.setAttribute('aria-label','希望の幅');h.setAttribute('aria-label','希望の高さ');form.append(w,el('span',null,'×'),h);form.addEventListener('submit',e=>{e.preventDefault();const a=Number(w.value),b=Number(h.value);if(!Number.isInteger(a)||!Number.isInteger(b)||a<256||b<256||a>16000||b>16000)return;const gcd=(x,y)=>y?gcd(y,x%y):x;const d=gcd(a,b);choose('自由サイズ｜'+a+'×'+b+'｜'+a/d+':'+b/d);});}else{const input=el('input');input.required=true;input.maxLength=160;input.placeholder='希望する'+q.name;input.setAttribute('aria-label',q.name+'を自由入力');form.append(input);form.addEventListener('submit',e=>{e.preventDefault();const v=input.value.trim().replace(/[\r\n]/g,' ');if(v)choose(v);});}const b=el('button','dark-button','この内容にする');b.type='submit';form.append(b);$('custom-area').append(form,el('p','microcopy',q.key==='size'?'256〜16,000px。生成環境に対応する実寸で出力されます。':'具体的な技法や角度も指定できます。160文字まで。'));form.querySelector('input').focus();}
function choose(v){const availability=candidateAvailability(activeQuestion.key,v,selections);if(!availability.enabled){tell(availability.reason);return;}selections[activeQuestion.key]=v;const key=activeQuestion.key;renderChoices(key==='line'?'type':key);$('picker').close();document.querySelector('[data-key="'+(key==='line'?'type':key)+'"]')?.focus();tell(activeQuestion.name+'を選びました');}
function summarizeName(raw){const bracket=raw.match(/^[〖【「『]([^〗】」』]+)[〗】」』]/);return bracket?bracket[1].trim():raw;}
async function loadProfile(){
 const id=normalizeCreator($('creator').value);if(!id){tell('noteのIDまたはプロフィールURLを入力してください。');$('creator').focus();return;}
 if(profileController&&profileController.profileId===id)return profileController.done;if(loadedProfile?.id===id&&loadedProfile.ready)return true;profileController?.abort();const controller=new AbortController();profileController=controller;controller.profileId=id;loadedProfile=null;$('load-profile').disabled=true;$('load-profile').textContent='準備中…';$('stop-profile').hidden=false;$('profile-status').textContent='あなたの世界観を整えています。選択や遊びはそのまま楽しめます。';
 let finish,usable;controller.done=new Promise(r=>finish=r);controller.usable=new Promise(r=>usable=r);try{let page=1;const pages=new Set(),signatures=new Set();while(page){if(pages.has(page))throw new Error('クリエイターの準備が途中で止まりました。');pages.add(page);let data;for(let attempt=0;attempt<2;attempt++){try{const response=await fetch(profileEndpoint+'?id='+encodeURIComponent(id)+'&page='+page,{signal:AbortSignal.any([controller.signal,AbortSignal.timeout(12000)]),headers:profileHeaders});data=await response.json();if(!response.ok||typeof data.name!=='string')throw new Error(data.error||'クリエイター情報を整えられませんでした。');break;}catch(e){if(controller.signal.aborted||e.name==='TimeoutError'||attempt===1)throw e;}}if(controller!==profileController)return false;const signature=data.pagination?.keys?.join('|');if(signature&&signatures.has(signature))throw new Error('クリエイターの準備が途中で止まりました。');if(signature)signatures.add(signature);loadedProfile=mergeCreator(loadedProfile,data);if(page===1){$('creator-name').value=summarizeName(data.name);$('activity').value=data.biography||'';$('profile-editor').open=false;usable(true);}syncProfilePreview();renderBoard();page=data.pagination?.nextPage||null;}
 loadedProfile.ready=true;$('profile-status').textContent=loadedProfile.bodyRead?.status==='partial'?'クリエイター設定は使えます。世界観の準備に一部届かない情報がありました。':'クリエイター設定ができました。そのまま制作できます。';$('profile-status').className='profile-status success';tell('あなたの世界観で制作できます。');return true;}
 catch(e){if(controller!==profileController||e.name==='AbortError')return false;if(loadedProfile)loadedProfile.ready=false;$('profile-editor').open=true;syncProfilePreview();$('profile-status').textContent=(e.message||'準備できませんでした。')+' 名前・活動は手入力できます。';$('profile-status').className='profile-status error';}
 finally{usable(!!loadedProfile&&loadedProfile.id===id);finish(!!loadedProfile&&loadedProfile.id===id);if(controller===profileController){profileController=null;$('stop-profile').hidden=true;$('load-profile').disabled=false;$('load-profile').textContent='IDから読み込む';}}
}
const topicsList=['共同マガジン','コミュニティ','メンバーシップ','子育て','育児','ワーママ','医療','福祉','介護','看護','イラスト','AI','創作','小説','エッセイ','詩','漫画','写真','音楽','料理','旅行','読書','映画','デザイン','アート','日記','仕事','タイミー','副業','収益化','学習','教育','健康','スポーツ','ゲーム','ファッション','動物','自然'];
function currentProfile(){const name=$('creator-name').value.trim(),bio=$('activity').value.trim(),id=normalizeCreator($('creator').value);const base=loadedProfile&&loadedProfile.id===id?loadedProfile:{};const corpus=bio+' '+(base.titles||[]).join(' ');const topics=[...new Set([...topicsList.filter(t=>t==='AI'?/\bAI\b/i.test(corpus):corpus.includes(t)),...(bio===(base.biography||'')?base.topics||[]:[])])];return {...base,id:id||'',name:base.name||name,displayName:name,biography:bio,topics,titles:base.titles||[],source:base.source||'作成者の手動入力'};}
function artworkProfile(){const p=profileForArtwork(currentProfile(),activityEnabled,excludedTopics);return collection==='everyday'?dailyInspiration(p):p;}
function syncProfilePreview(){const p=currentProfile();$('profile-preview').hidden=!p.displayName;$('profile-name').textContent=p.displayName;$('profile-bio').textContent=p.biography||'あなたの創作を、Halloweenの世界へ。';renderTopics(p.topics);syncActivity();}
function syncActivity(){const p=artworkProfile();$('activity-on').setAttribute('aria-pressed',String(activityEnabled));$('activity-off').setAttribute('aria-pressed',String(!activityEnabled));$('activity-state').textContent=activityEnabled?'ON：チェックした活動を作品に使います。タップで個別に外せます。':'OFF：作品には名前だけを使います。活動は反映しません。';$('profile-ideas').hidden=!currentProfile().inspiration?.themes?.length;$('profile-ideas').disabled=!activityEnabled||!p.inspiration?.themes?.length;const applied=ideaApplied&&(selections.theme===ideaApplied.theme||selections.line===ideaApplied.line);$('profile-ideas').setAttribute('aria-pressed',String(!!applied));$('profile-ideas').textContent=applied?'提案を使用中 — タップで解除':'物語・セリフを提案する';$('profile-ideas-off').hidden=!applied;}
function renderTopics(topics){$('activity-topics').replaceChildren(...topics.map(t=>{const on=!excludedTopics.has(t),b=el('button',null,t+' · '+(on?'ON':'OFF'));b.type='button';b.setAttribute('aria-pressed',String(on));b.setAttribute('aria-label',t+'：'+(on?'ON。タップでOFF':'OFF。タップでON'));b.disabled=!activityEnabled;b.addEventListener('click',()=>{if(on)excludedTopics.add(t);else excludedTopics.delete(t);clearIdeas();syncProfilePreview();});return b;}));}
function clearIdeas(){if(ideaSnapshot&&ideaApplied){if(selections.theme===ideaApplied.theme)selections.theme=ideaSnapshot.theme;if(selections.line===ideaApplied.line)selections.line=ideaSnapshot.line;if(mode==='auto'&&selectedProposal){if(selectedProposal.theme===ideaApplied.theme)selectedProposal.theme=ideaSnapshot.proposal?.theme||ideaSnapshot.theme;if(selectedProposal.line===ideaApplied.line)selectedProposal.line=ideaSnapshot.proposal?.line||ideaSnapshot.line;}}ideaSnapshot=null;ideaApplied=null;renderChoices();}
function setActivity(on){if(!on)clearIdeas();activityEnabled=on;syncProfilePreview();}
async function addFiles(files){
 if(adding){tell('画像を読み込み中です。');return;}const incoming=Array.from(files);if(!incoming.length)return;setAttachmentMode('bundle');adding=true;$('generate').disabled=true;
 try{for(const file of incoming){if(refs.length>=4){tell('添付は最大4枚です。');break;}if(!['image/png','image/jpeg','image/webp','image/gif'].includes(file.type)){tell('PNG・JPG・WebP・GIFを選んでください。');continue;}if(file.size>12*1024*1024){tell('画像は1枚12MBまでです。');continue;}const name=file.name.replace(/[\r\n<>]/g,'_').slice(0,120)||'reference.png';if(refs.some(r=>r.name===name&&r.file.size===file.size&&r.file.lastModified===file.lastModified)){tell('同じ画像は添付済みです。');continue;}const url=URL.createObjectURL(file);try{const img=new Image();await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=()=>reject(new Error('画像を読み込めませんでした。'));img.src=url;});refs.push({file,url,name,width:img.naturalWidth,height:img.naturalHeight,role:refs.length?'support':'identity'});renderRefs();}catch(e){URL.revokeObjectURL(url);tell(e.message);}}}finally{adding=false;$('generate').disabled=false;$('image-input').value='';}
}
function renderRefs(refresh=true){
 $('references').replaceChildren();refs.forEach((r,i)=>{const f=el('figure','reference-thumb'),img=el('img');img.src=r.url;img.alt=r.name;const remove=el('button','remove-ref','×');remove.type='button';remove.setAttribute('aria-label',r.name+'を取り除く');remove.addEventListener('click',()=>{URL.revokeObjectURL(r.url);refs.splice(i,1);if(refs.length&&!refs.some(x=>x.role==='identity'))refs[0].role='identity';renderRefs();});const role=el('select');role.setAttribute('aria-label',r.name+'の画像の役割');for(const [v,label]of [['identity','キャラの主参照'],['support','補助参照'],['avoid','似せない前作']]){const o=el('option',null,label);o.value=v;role.append(o);}role.value=r.role;role.addEventListener('change',()=>{if(role.value==='identity')refs.forEach(x=>{if(x!==r&&x.role==='identity')x.role='support';});r.role=role.value;renderRefs();});const edit=el('button','edit-ref','切り抜き・拡大縮小');edit.type='button';edit.addEventListener('click',()=>cropEditor.open(r));f.append(img,remove,edit,el('figcaption',null,String(i+1).padStart(2,'0')+' / '+r.width+'×'+r.height),role);$('references').append(f);});const primary=refs.find(r=>r.role==='identity');if(primary){$('main-reference').src=primary.url;$('main-reference').hidden=false;$('empty-reference').hidden=true;}else{$('main-reference').removeAttribute('src');$('main-reference').hidden=true;$('empty-reference').hidden=false;}$('form-error').hidden=true;if(refresh)renderChoices();
}
function formError(s,focus){$('form-error').textContent=s;$('form-error').hidden=false;focus?.focus();}
async function generate(lockedValues=null){
 if(creating||adding)throw new Error('制作の準備中です。');
 const started=performance.now();
 creating=true;$('generate').disabled=true;$('generate').textContent='制作条件を準備中…';$('generation-status').hidden=false;$('generation-status').textContent='制作に使う設定を確認中…';
 try{
 await new Promise(resolve=>requestAnimationFrame(()=>resolve()));
 if(mode==='auto'&&!selectedProposal){formError('気に入った組み合わせを一つ選んでください。',$('propose'));throw new Error('組み合わせを選んでください。');}
 const creator=normalizeCreator($('creator').value);if(creator===null){formError('noteのIDまたはURLの形式を確認してください。',$('creator'));throw new Error('ID形式が正しくありません。');}
 const manualName=$('profile-editor').open&&$('creator-name').value.trim();
 if(creator&&!manualName&&!($('creator-name').value.trim()&&loadedProfile?.id===creator)){
  if(profileController?.profileId===creator)await profileController.usable;
  else if((!loadedProfile||loadedProfile.id!==creator)&&!$('profile-editor').open){loadProfile();if(profileController?.profileId===creator)await profileController.usable;}
 }
 if(normalizeCreator($('creator').value)!==creator)throw new Error('クリエイターIDが変わりました。新しい名前を確認して、もう一度制作してください。');
 const profile=artworkProfile();if(!profile.displayName){$('profile-editor').open=true;formError('IDから名前を読み込むか、クリエイター名を入力してください。',$('creator-name'));throw new Error('クリエイター名がありません。');}
 $('generation-status').textContent='選んだ項目と参照画像を確認しています…';
  syncSaved();const input=lockedValues?{...lockedValues}:mode==='auto'&&selectedProposal?{...selectedProposal,size:selections.size}:effectiveSelections(mode,selections);
  if(input.theme===AUTO&&profile.inspiration?.themes?.length)input.theme=profile.inspiration.themes[Math.floor(rng()*profile.inspiration.themes.length)];
  if(input.line===AUTO&&profile.inspiration?.phrases?.length)input.line=profile.inspiration.phrases[Math.floor(rng()*profile.inspiration.phrases.length)];
  const values=resolveSelections(input,rng);const conflicts=selectionConflicts(values);if(conflicts.length){formError(conflicts[0].reason,$('generate'));throw new Error(conflicts[0].reason);}if(input.mood===AUTO)values.mood='毎回大胆に変える';
  if(attachmentMode==='bundle'&&needsReference(values)&&!refs.some(r=>r.role==='identity')){formError('主参照を添付してください。人物なしの風景は、参照を使う項目を選んでいなければ画像なしでも作れます。',$('image-input'));throw new Error('主参照画像がありません。');}
  let variant;for(let a=0;a<60;a++){variant=applyPose(buildDirection(saved.used,values.mood,rng,collection,values),values.pose);if(!saved.used.some(r=>r.signature===variant.signature))break;if(a===59)throw new Error('構図の演出を選び直してください。');}
  const edition=uid(),ordered=attachmentMode==='bundle'?[refs.find(r=>r.role==='identity'),...refs.filter(r=>r.role!=='identity')].filter(Boolean):[];
  const metadata=ordered.length?ordered.map((r,i)=>({name:'reference-'+String(i+1).padStart(2,'0')+'-'+r.name,role:r.role,width:r.width,height:r.height})):needsReference(values)?[{name:'ChatGPTへ直接添付する主参照',role:'identity'}]:[];
  $('generation-status').textContent='項目名から画風・形式・場面を制作指示にしています…';
  const production=productionPlan(profile,values,variant,collection,rng);variant=production.variant;
  // A one-image bundle preserves the uploaded bytes. Multi-image flattening is optional.
  // Original files are ready immediately; combine only on explicit request.
  const referenceBoardFile=ordered.length===1?new File([ordered[0].file],metadata[0].name,{type:ordered[0].file.type}):null;
  const prompt=composePrompt({collection,creator:creator||'',profile,values,variant,references:metadata,edition,referenceBundle:ordered.length>1?{name:'creator-references.jpg',combined:true}:null,preparedPlan:production});
  saved.count++;const r={version:APP_VERSION,collection,creator:creator||'',profile,values,variant,edition,prompt,production,stages:stagePrompts(production),date:new Date().toISOString(),references:metadata,localRefs:ordered.map(r=>({...r})),referenceBoardFile,attachmentMode,isFresh:true,preparationMs:Math.round(performance.now()-started),count:saved.count};
  const {localRefs,referenceBoardFile:boardFile,isFresh,...record}=r;
  saved.used.push({signature:variant.signature,family:variant.family,face:variant.face,expression:variant.expression,distance:variant.distance,pose:variant.pose,poseChoice:values.pose,layout:variant.layout});saved.used=saved.used.slice(-2000);saved.history.unshift(record);saved.history=saved.history.slice(0,12);persist();renderHistory();$('form-error').hidden=true;renderBoard(values,variant);$('issue-number').textContent='No. '+String(saved.count).padStart(3,'0');$('stage').classList.remove('flash');void $('stage').offsetWidth;$('stage').classList.add('flash');showResult(r);effects.celebrate();return r;
 }finally{creating=false;$('generate').disabled=false;$('generate').textContent='制作プロンプトをつくる ✦';$('generation-status').hidden=true;}
}
function shareFiles(r){return [...(r.localRefs||[]).map((x,i)=>new File([x.file],r.references[i].name,{type:x.file.type})),new File([r.prompt],'prompt.txt',{type:'text/plain'})];}
function canShareFiles(files){try{return !!navigator.share&&!!navigator.canShare?.({files});}catch{return false;}}
function showResult(r){
 disposeLayoutPreview();disposeLayoutPreview=()=>{};
 currentResult=r;$('copy-repair').hidden=!r.production;$('prompt-output').value=r.prompt;$('result-edition').textContent='EDITION / '+r.edition;
 const live=Array.isArray(r.localRefs)&&r.localRefs.length>0,fresh=!!r.isFresh,requires=needsReference(r.values),noPerson=/風景を主役|モチーフだけ|紋章・アイコン/.test(r.values.costume);
 $('result-intro').textContent=r.version!==APP_VERSION?'以前の仕様で作成した履歴です。新仕様で作る場合は、入力画面から制作してください。':live?'参照画像と制作指示の準備ができました。ChatGPTへ送り、画像を生成します。':requires?'ChatGPTで自分の参照画像を添付し、この指示と一緒に送ります。':'参照画像なしで作れる風景・モチーフです。この指示をChatGPTへ送って画像を生成します。';
 $('result-summary').replaceChildren(el('h3',null,r.values.theme),el('p',null,r.profile.displayName+' / '+r.values.design+' / '+r.values.medium),el('p',null,r.values.size.split('｜').slice(0,2).join(' / ')+'px'),el('p','detail',noPerson?'人物なし / '+r.values.place:[r.variant.face,r.variant.expression,r.variant.distance].join(' / ')));
 if(r.production){const details=el('details','production-details');details.append(el('summary',null,'この作品に反映する10項目と文字原稿'));const list=el('ol');r.production.conditions.forEach(c=>{const li=el('li');const item=el('details','recipe-specs');item.append(el('summary',null,c.name+'：'+c.value));for(const section of c.sections||[{label:'制作条件',text:c.text}]){const p=el('p');p.append(el('b',null,section.label+'：'),document.createTextNode(section.text));item.append(p);}appendRecipeEvidence(item,c.key,c.value,{known:c.known});li.append(item);list.append(li);});details.append(list);if(r.production.copy.slots.length){details.append(el('h4',null,'作品内の文字原稿'));r.production.copy.slots.forEach(slot=>details.append(el('p',null,slot.role+'：'+slot.text)));}r.production.notes.forEach(n=>details.append(el('p','production-note',n)));const sources=editorialReferencesFor(r.values.design);if(sources.length){details.append(el('h4',null,'誌面の構成を確認した資料'));for(const source of sources){const a=el('a',null,source.publisher+' / '+source.location);a.href=source.url;a.target='_blank';a.rel='noopener noreferrer';const item=el('p');item.append(a);details.append(item);}}$('result-summary').append(details);}
 if(r.stages){const workflow=el('details','production-details');workflow.id='staged-workflow';workflow.open=false;workflow.append(el('summary',null,'文字を厳密に配置したい場合の段階制作'));workflow.append(el('p',null,'通常制作は完成画像を1回で直接生成します。文字を厳密に配置したい場合は、下の段階制作も使えます。'));workflow.append(el('p',null,'段階ごとに進める場合は、下の指示を順に送れます。画風の修正には作成途中の主画像を、誌面編集には確認した主画像を添付してください。'));const actions=el('div','result-actions');for(const [key,label] of [['artwork','① 主画像の指示をコピー'],['repair','主画像の画風を直す指示'],['layout','② 誌面の指示をコピー']]){const button=el('button','secondary-button',label);button.type='button';button.dataset.stage=key;button.addEventListener('click',()=>copyStage(key));actions.append(button);}workflow.append(actions);const native=createLayoutPanel(r.production,tell);workflow.append(native.element);disposeLayoutPreview=native.dispose;$('result-summary').append(workflow);}
 $('result-refs').replaceChildren();if(live)r.localRefs.forEach((x,i)=>{const f=el('figure'),im=el('img');im.src=x.url;im.alt=x.name;f.append(im,el('figcaption',null,'共有する参照 '+String(i+1).padStart(2,'0')+' / '+(x.role==='avoid'?'似せない前作':x.role==='identity'?'主参照':'補助')));$('result-refs').append(f);});
 $('download-guide').disabled=!r.production;$('download-kit').disabled=false;$('copy-image').disabled=!live;$('share-all').hidden=true;$('again').hidden=!fresh;$('download-board').hidden=!live;$('download-board').textContent=live&&r.localRefs.length===1?'参照画像を保存':'参照だけを１枚に保存';$('share-board').hidden=!live;
 $('transfer-title').textContent=live?'参照画像＋プロンプト':'プロンプトのみ';
 $('transfer-instruction').textContent=live?'「画像＋プロンプトを共有」で、ご自身の参照画像と prompt.txt を渡します。共有先に画像と指示が届いたことを確認して送信してください。見本の人物や背景は送信しません。':requires?'「プロンプトをコピー」を押し、ChatGPTで自分の参照画像を添付して同じメッセージで送ってください。':'「プロンプトをコピー」を押し、ChatGPTへ送ってください。この選択では人物の参照画像は必要ありません。';
 $('transfer-instruction').textContent+=' ChatGPTの通常の画像作成を使います。5.5でもWorkやコード実行を前提にしません。';
 $('transfer-status').textContent=live?(canShareFiles(shareFiles(r))?'画像と指示ファイルを一緒に共有できます。共有先で両方を確認してください。':'端末の共有対応を確認します。使えない場合は制作セットを保存できます。'):fresh?'完成画像はChatGPT側に表示されます。':'履歴に画像データはありません。必要な場合は元の参照画像をChatGPTへ添付してください。';
 $('kit-note').textContent=live?'ZIPを解凍して、reference- で始まる参照画像と prompt.txt を同じメッセージに添付してください。':'生成した画像が表示されない場合は「画像が出ないときの指示」をコピーして、同じチャットへ送れます。';
 if(!$('result').open)$('result').showModal();
}
async function copyPrompt(){if(!currentResult)return false;try{await navigator.clipboard.writeText(currentResult.prompt);tell(needsReference(currentResult.values)?'プロンプトをコピーしました。自分の参照画像と一緒に送ってください。':'プロンプトをコピーしました。ChatGPTへ送って画像を生成します。');return true;}catch{const ta=$('prompt-output');ta.closest('details').open=true;ta.focus();ta.select();try{if(document.execCommand('copy')){tell('プロンプトをコピーしました。');return true;}}catch{}tell('全文を選択しました。長押しでコピーできます。');return false;}}
async function copyStage(key){const text=currentResult?.stages?.[key];if(!text)return;try{await navigator.clipboard.writeText(text);tell(key==='artwork'?(needsReference(currentResult.values)?'主画像の指示をコピーしました。自分の主参照と一緒に送ってください。':'主画像の指示をコピーしました。ChatGPTへ送ってください。'):key==='repair'?'画風の修正指示をコピーしました。制作途中の主画像と一緒に送ってください。':'誌面の指示をコピーしました。確認した主画像と一緒に送ってください。');}catch{download(new Blob([text],{type:'text/plain;charset=utf-8'}),'stage-'+key+'.txt');tell('この段階の指示を保存しました。対象の画像と一緒に送ってください。');}}
async function shareAll(){
 const r=currentResult;if(!r?.isFresh)return;
 const files=shareFiles(r),images=files.filter(f=>f.type.startsWith('image/'));
 let payload;if(canShareFiles(files))payload={files,text:'添付の prompt.txt と参照画像で絵を1枚描いてください。ChatGPTの画像作成機能を実行し、通常の生成画像としてこのチャットに表示してください。計画・コード・ダウンロードリンクだけで終わらないでください。',title:r.collection==='everyday'?'イラスト制作資料':'Halloween制作資料'};else if(images.length&&canShareFiles(images))payload={files:images,text:r.prompt,title:'画像と制作指示'};
 if(!payload){$('transfer-status').textContent='この端末では同時共有に対応していません。制作セットを保存し、解凍した画像と prompt.txt をChatGPTへ添付してください。';await downloadKit();return;}
 try{await navigator.share(payload);$('transfer-status').textContent=payload.files.some(f=>f.type==='text/plain')?'共有画面を閉じました。送信先の画像と prompt.txt を確認して送信してください。':'参照画像を共有しました。共有先で指示が表示されない場合は「プロンプトをコピー」で追加してください。';}
 catch(e){if(e.name==='AbortError'){$('transfer-status').textContent='共有を取り消しました。もう一度共有できます。';return;}$('transfer-status').textContent='共有できませんでした。参照画像とプロンプトを別々に保存して添付できます。';tell('共有できませんでした。制作セット保存を使ってください。');}
}
async function imagePNG(r){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>{try{const c=document.createElement('canvas');c.width=img.naturalWidth;c.height=img.naturalHeight;c.getContext('2d').drawImage(img,0,0);c.toBlob(b=>b?resolve(b):reject(new Error('画像を変換できませんでした。')),'image/png');}catch(e){reject(e);}};img.onerror=reject;img.src=r.url;});}
async function copyImage(){const r=currentResult?.localRefs?.find(x=>x.role==='identity');if(!r)return;if(!navigator.clipboard?.write||typeof ClipboardItem==='undefined'){download(r.file,'reference-'+r.name);tell('画像を保存しました。ChatGPTに添付してください。');return;}try{const promise=imagePNG(r);await navigator.clipboard.write([new ClipboardItem({'image/png':promise})]);$('transfer-status').textContent='主参照画像をコピーしました。ChatGPTへ貼り付けた後、プロンプトも貼り付けてください。';tell('主参照の画像をコピーしました。ChatGPTで貼り付けてください。');}catch{download(r.file,'reference-'+r.name);tell('画像コピーに対応していないため、画像を保存しました。');}}
function download(blob,name){const url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
async function downloadKit(){const r=currentResult;if(!r)return;const b=$('download-kit');b.disabled=true;b.textContent='セットを準備中…';try{
 const imageNames=(r.localRefs||[]).map((_,i)=>r.references[i].name);
 const help=['画像制作セット','','1. ZIPを解凍します。',imageNames.length?'2. 下の参照画像と prompt.txt を同じChatGPTのメッセージへ添付します。':needsReference(r.values)?'2. prompt.txt とご自身の主参照画像を、同じChatGPTのメッセージへ添付します。':'2. prompt.txt をChatGPTへ添付するか、中の指示をコピーして送ります。','3. prompt.txt の条件で画像を1枚描き、ChatGPTの通常の生成画像としてチャットに表示するよう送信します。','4. 完成画像が出ない場合は、ツールの「画像が出ないときの指示」を同じチャットへ送ります。','','添付する参照画像：',...imageNames,'','選択画面の見本絵は制作セットに含めません。','名前：'+r.profile.displayName,'制作番号：'+r.edition].join('\n');
 const files=[{name:'prompt.txt',data:new TextEncoder().encode(r.prompt)},{name:'使い方.txt',data:new TextEncoder().encode(help)}];
 for(let i=0;i<(r.localRefs||[]).length;i++)files.push({name:r.references[i].name,data:new Uint8Array(await r.localRefs[i].file.arrayBuffer())});
 download(makeZip(files),'Artwork-'+r.edition+'.zip');tell('制作セットを保存しました。');
 }catch{tell('保存に失敗しました。プロンプトと参照画像を個別に保存してください。');}finally{b.disabled=false;b.textContent='制作セットを保存';}}
function renderHistory(){$('history').replaceChildren();if(!saved.history.length){$('history').append(el('p','history-empty','まだ白紙のコレクション。最初の一夜をつくろう。'));return;}saved.history.forEach(r=>{const b=el('button','history-card');b.type='button';b.append(sampleNode('medium',r.values.medium),el('span','hist-id','No. '+String(r.count).padStart(3,'0')),el('b',null,r.values.theme),el('p',null,r.profile.displayName+' / '+r.values.medium),el('small',null,r.variant.face));b.addEventListener('click',()=>showResult(r));$('history').append(b);});}
function setAttachmentMode(next){attachmentMode=next==='bundle'?'bundle':'chatgpt';document.querySelectorAll('[name="attachment-mode"]').forEach(r=>r.checked=r.value===attachmentMode);$('drop-zone').hidden=false;$('reference-note').hidden=false;$('attachment-mode-note').textContent=attachmentMode==='bundle'?'ここにご自身の参照画像を添付し、項目名から作る制作指示と一緒に共有します。人物なしの風景は画像なしでも作れます。':'制作指示をコピーし、ChatGPTで自分の画像を添付して送ります。ここで画像を添付すると「画像＋プロンプト」に切り替わります。';}
document.querySelectorAll('[name="attachment-mode"]').forEach(r=>r.addEventListener('change',()=>setAttachmentMode(r.value)));
$('activity-on').addEventListener('click',()=>setActivity(true));$('activity-off').addEventListener('click',()=>setActivity(false));
$('profile-ideas-off').addEventListener('click',()=>{clearIdeas();tell('提案を解除し、前の選択に戻しました。');});
$('profile-ideas').addEventListener('click',()=>{if(ideaApplied&&(selections.theme===ideaApplied.theme||selections.line===ideaApplied.line)){clearIdeas();tell('提案を解除し、前の選択に戻しました。');return;}const idea=artworkProfile().inspiration;if(!activityEnabled||!idea?.themes?.length)return;ideaSnapshot={theme:selections.theme,line:selections.line,proposal:selectedProposal?{...selectedProposal}:null};selections.theme=idea.themes[Math.floor(rng()*idea.themes.length)];if(idea.phrases?.length)selections.line=idea.phrases[Math.floor(rng()*idea.phrases.length)];ideaApplied={theme:selections.theme,line:selections.line};if(mode==='auto')selectedProposal={...(selectedProposal||propose(selections,rng)),...ideaApplied,size:selections.size};renderChoices();tell('物語とセリフに提案を使っています。もう一度押すと解除できます。');});
$('stop-profile').addEventListener('click',()=>{profileController?.abort();profileController=null;$('stop-profile').hidden=true;$('load-profile').disabled=false;$('load-profile').textContent='IDから読み込む';$('profile-editor').open=!loadedProfile;$('profile-status').textContent='準備を止めました。今の設定で続けられます。';});
$('download-board').addEventListener('click',async()=>{const r=currentResult;if(!r?.localRefs?.length)return;const b=$('download-board');b.disabled=true;const label=b.textContent;b.textContent='参照をまとめています…';try{r.referenceBoardFile||=await buildReferenceBoard(r.localRefs,r.references);download(r.referenceBoardFile,r.referenceBoardFile.name);}catch{tell('まとめられませんでした。元の参照画像はそのまま共有できます。');}finally{b.disabled=false;b.textContent=label;}});
$('share-board').addEventListener('click',shareAll);
$('load-profile').addEventListener('click',loadProfile);$('creator').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();loadProfile();}});$('creator').addEventListener('input',()=>{profileController?.abort();profileController=null;$('stop-profile').hidden=true;$('load-profile').disabled=false;$('load-profile').textContent='IDから読み込む';if(loadedProfile&&normalizeCreator($('creator').value)!==loadedProfile.id){if($('creator-name').value===summarizeName(loadedProfile.name))$('creator-name').value='';if($('activity').value===loadedProfile.biography)$('activity').value='';loadedProfile=null;excludedTopics.clear();clearIdeas();renderTopics([]);}$('profile-status').className='profile-status';$('profile-status').textContent='IDを入力すると、名前と活動内容を読み込みます。';syncProfilePreview();renderBoard();});
$('creator').addEventListener('change',()=>{if(normalizeCreator($('creator').value))loadProfile();});
$('creator-name').addEventListener('input',()=>{syncProfilePreview();renderBoard();$('form-error').hidden=true;});$('activity').addEventListener('input',syncProfilePreview);$('image-input').addEventListener('change',e=>addFiles(e.target.files));
$('pick-image').addEventListener('click',()=>$('image-input').click());
$('paste-image').addEventListener('click',async()=>{try{if(!navigator.clipboard?.read)throw new Error('unsupported');const items=await navigator.clipboard.read(),files=[];for(const item of items){const type=item.types.find(t=>['image/png','image/jpeg','image/webp','image/gif'].includes(t));if(type){const blob=await item.getType(type);files.push(new File([blob],'paste-'+Date.now()+'.'+(type==='image/jpeg'?'jpg':type.split('/')[1]),{type}));}}if(!files.length)throw new Error('no image');await addFiles(files);$('paste-target').hidden=true;}catch{$('paste-target').hidden=false;$('paste-target').focus();tell('貼り付け欄を長押しして貼り付けてください。写真を選ぶこともできます。');}});
document.addEventListener('paste',e=>{const files=Array.from(e.clipboardData?.items||[]).filter(i=>i.kind==='file').map(i=>i.getAsFile()).filter(Boolean);if(files.length&&!$('result').open&&!$('picker').open&&!$('crop-dialog').open){e.preventDefault();$('paste-target').hidden=true;addFiles(files);}else if(e.target===$('paste-target'))e.preventDefault();});$('drop-zone').addEventListener('dragover',e=>{e.preventDefault();$('drop-zone').classList.add('dragover');});$('drop-zone').addEventListener('dragleave',()=>$('drop-zone').classList.remove('dragover'));$('drop-zone').addEventListener('drop',e=>{e.preventDefault();$('drop-zone').classList.remove('dragover');addFiles(e.dataTransfer.files);});window.addEventListener('dragover',e=>{if(e.dataTransfer?.types.includes('Files'))e.preventDefault();});window.addEventListener('drop',e=>{if(e.dataTransfer?.types.includes('Files'))e.preventDefault();});
$('shuffle').addEventListener('click',()=>{const size=selections.size;selections=resolveSelections(Object.fromEntries(questions.map(q=>[q.key,AUTO])),rng);selections.mood='毎回大胆に変える';selections.size=size;if(mode==='auto')selectedProposal={...selections};renderChoices();tell('サイズを保ったまま、新しい組み合わせを選びました。');});$('generate').addEventListener('click',async()=>{try{await generate();}catch(e){if($('form-error').hidden)tell(e.message);}});$('copy').addEventListener('click',copyPrompt);$('copy-repair').addEventListener('click',async()=>{if(!currentResult?.production)return;const text=repairPrompt(currentResult);try{await navigator.clipboard.writeText(text);tell('修正指示をコピーしました。完成画像と同じチャットへ送ってください。');}catch{download(new Blob([text],{type:'text/plain;charset=utf-8'}),'finish-instructions.txt');tell('修正指示を保存しました。完成画像と一緒に送ってください。');}});$('share-all').addEventListener('click',shareAll);$('copy-image').addEventListener('click',copyImage);$('chatgpt').addEventListener('click',()=>{window.open('https://chatgpt.com/','_blank','noopener,noreferrer');tell(currentResult&&!needsReference(currentResult.values)?'コピーした制作指示を送信してください。':'ご自身の参照画像とプロンプトを両方添付してから送信してください。');});$('download-kit').addEventListener('click',downloadKit);$('download-text').addEventListener('click',()=>{if(currentResult)download(new Blob([currentResult.prompt],{type:'text/plain;charset=utf-8'}),'Halloween-'+currentResult.edition+'.txt');});
$('again').addEventListener('click',async()=>{try{const old=currentResult;if((old.collection||'halloween')!==collection)setCollection(old.collection||'halloween');selections={...old.values};if(mode==='auto')selectedProposal={...old.values};$('creator').value=old.creator;$('creator-name').value=old.profile.displayName;$('activity').value=old.profile.biography;loadedProfile=old.profile;activityEnabled=old.profile.activityEnabled!==false;excludedTopics.clear();ideaSnapshot=ideaApplied=null;setAttachmentMode(old.attachmentMode||'bundle');syncProfilePreview();refs.forEach(r=>URL.revokeObjectURL(r.url));refs=old.localRefs.map(r=>({...r,url:URL.createObjectURL(r.file)}));renderRefs();renderChoices();await generate(old.values);}catch(e){tell(e.message);}});$('help').addEventListener('click',()=>$('help-dialog').showModal());document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>$(b.dataset.close).close()));document.querySelectorAll('.view-switch button').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}}));$('clear-history').addEventListener('click',()=>{if(!saved.history.length)return tell('履歴はありません。');if(window.confirm('この端末の制作履歴を消しますか？演出の重複回避記録は残ります。')){saved.history=[];persist();renderHistory();tell('履歴を消しました。');}});
document.querySelectorAll('.mode-switch button').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));$('propose').addEventListener('click',makeProposals);document.querySelectorAll('[data-text-part]').forEach(b=>b.addEventListener('click',()=>{textPart=b.dataset.textPart;openPicker(questions.find(q=>q.key===textPart));}));$('download-guide').addEventListener('click',()=>{if(!currentResult?.production)return;download(new Blob([[...(currentResult.production.interactions||[]),...currentResult.production.conditions.map(c=>c.name+'：'+c.value+'\n'+(c.sections||[{label:'制作条件',text:c.text}]).map(s=>s.label+'：'+s.text).join('\n'))].join('\n\n')],{type:'text/plain;charset=utf-8'}),'selected-conditions.txt');});
$('copy-delivery').addEventListener('click',async()=>{if(!currentResult)return;const text=imageDeliveryRepairPrompt(currentResult);try{await navigator.clipboard.writeText(text);tell('再表示の指示をコピーしました。画像が出なかった同じチャットへ送ってください。');}catch{download(new Blob([text],{type:'text/plain;charset=utf-8'}),'show-finished-image.txt');tell('再表示の指示を保存しました。同じチャットへ送ってください。');}});
const motionMedia=window.matchMedia('(prefers-reduced-motion: reduce)');let motion=true;try{motion=localStorage.getItem('halloween-motion')!=='off';}catch{}function setMotion(on){motion=on;const enabled=on&&!motionMedia.matches;document.body.dataset.motion=enabled?'on':'off';$('motion-label').textContent=motionMedia.matches?'OFF：端末の省動作設定を優先':enabled?(collection==='everyday'?'ON：彩りが動きます':'ON：魔法が動きます'):'OFF：動きと遊びを停止';$('motion-off').setAttribute('aria-pressed',String(!enabled));$('motion-toggle').setAttribute('aria-pressed',String(enabled));$('motion-toggle').disabled=motionMedia.matches;$('play-state').textContent=enabled?(collection==='everyday'?'彩りが動いています':'魔法が動いています'):'演出は止まっています';$('playground').dataset.paused=String(!enabled);['play-spell','play-ghosts'].forEach(id=>$(id).disabled=!enabled);effects.sync();try{localStorage.setItem('halloween-motion',on?'on':'off');}catch{}}setMotion(motion);motionMedia.addEventListener('change',()=>setMotion(motion));$('motion-toggle').addEventListener('click',()=>setMotion(true));$('motion-off').addEventListener('click',()=>setMotion(false));$('light-play').addEventListener('click',()=>{const on=document.body.dataset.lights!=='night';document.body.dataset.lights=on?'night':'day';$('light-play').setAttribute('aria-pressed',String(on));$('light-play').textContent=(on?'夜の工房':'昼の工房')+' ／ タップで'+(on?'昼':'夜')+'へ';});
document.querySelectorAll('.collection-switch button').forEach(b=>b.addEventListener('click',()=>setCollection(b.dataset.collection)));
document.querySelectorAll('[data-decoration]').forEach(b=>{if(b.tagName!=='BUTTON')return;b.addEventListener('click',()=>{document.body.dataset.decoration=b.dataset.decoration;document.querySelectorAll('button[data-decoration]').forEach(n=>n.setAttribute('aria-pressed',String(n===b)));effects.celebrate();});});
function setCollection(next){if(!['halloween','everyday'].includes(next))return;clearIdeas();collectionSnapshots[collection]={mode,selections:{...selections},modeSnapshots:structuredClone(modeSnapshots),proposals,selectedProposal};collection=next;applyCollection(collection);const state=collectionSnapshots[next];mode=state?.mode||'detail';selections=state?.selections||initialSelections();modeSnapshots=state?.modeSnapshots||{detail:{...selections}};proposals=[];selectedProposal=state?.selectedProposal||null;document.body.dataset.collection=collection;const daily=collection==='everyday';document.querySelectorAll('.collection-switch button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.collection===collection)));$('hero-eyebrow').textContent=daily?'EVERYDAY / ILLUSTRATION STUDIO':'HALLOWEEN / CREATE YOUR WORLD';$('studio-title').replaceChildren(document.createTextNode(daily?'日々を、作品に。':'遊ぶ。描く。'),el('br'),document.createTextNode(daily?'好きな世界を描こう。':'変身する。'));$('hero-copy').textContent=daily?'日常、旅、ファッション、幻想。季節を問わず、自由な一枚へ。':'写真から墨絵まで。あなたの主役で、まだ見ぬ一夜を。';$('intro-copy').textContent=daily?'あなたのキャラで、毎日に新しい一枚を。':'あなたのキャラで、いつもと違うHalloween。';$('stage-brand').textContent=daily?'YOUR ILLUSTRATION':'YOUR HALLOWEEN';$('playground').setAttribute('aria-label',daily?'彩りの遊び場':'魔法の遊び場');$('playground-title').textContent=daily?'彩りの遊び場':'魔法の遊び場';$('play-spell').textContent=daily?'✦ 彩りをひろげる':'✦ 魔法を飛ばす';$('spell-status').textContent=daily?'花・紙片・光の演出を楽しめます。':'７種類の魔法。次は何が起きる？';setMotion(motion);$('play-copy').textContent=daily?'色や写真、身近なモチーフ。飾りに触って、創作のひらめきを。':'飾りをタップして魔法を発見。制作の合間にも、ひと遊び。';$('play-ghosts').textContent=daily?'モチーフをあつめる':'おばけとお菓子集め';$('ghost-title').textContent=daily?'モチーフをあつめる':'おばけとお菓子集め';boardArtKey='';setMode(mode);syncProfilePreview();effects.refresh();try{localStorage.setItem('halloween-collection',collection);}catch{}}
setView(view);renderRefs(false);setMode('detail');let initialCollection='halloween';try{initialCollection=localStorage.getItem('halloween-collection')||'halloween';}catch{}setCollection(initialCollection);renderHistory();

function setMode(next){if(!modeKeys[next])return;modeSnapshots[mode]={...selections};mode=next;selections={...(modeSnapshots[next]||initialSelections()),size:selections.size};document.body.dataset.mode=mode;document.querySelectorAll('.mode-switch button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===mode)));$('mode-description').textContent=modeCopy[mode];$('choice-heading').textContent={detail:'2. 10項目で決める',simple:'2. 5項目だけ選ぶ',auto:'2. 見本の組み合わせで決める'}[mode];$('auto-proposals').hidden=mode!=='auto';$('shuffle').hidden=mode==='auto';renderChoices();if(mode==='auto'&&!proposals.length)makeProposals();}
function makeProposals(){proposals=Array.from({length:3},()=>propose(selections,rng));selectedProposal=null;$('proposal-cards').replaceChildren();proposals.forEach((values,i)=>{const b=el('button','proposal-card');b.type='button';b.setAttribute('aria-pressed','false');const arts=el('span','proposal-art');arts.append(sampleNode('medium',values.medium),sampleNode('design',values.design));b.append(arts,el('b',null,values.medium),el('span',null,values.design),el('small',null,values.theme+' / '+values.palette));b.addEventListener('click',()=>{selectedProposal={...values,size:selections.size};document.querySelectorAll('.proposal-card').forEach(n=>n.setAttribute('aria-pressed',String(n===b)));renderBoard(selectedProposal);tell('この作例の組み合わせを選びました。');});$('proposal-cards').append(b);});renderBoard({...initialSelections(),size:selections.size});$('generation-status').hidden=true;}
function renderHangingGallery(values){if(!$('hanging-gallery'))return;$('hanging-gallery').replaceChildren();for(const key of ['medium','design','theme','costume','palette']){const card=el('div','hanging-card');const label=questions.find(q=>q.key===key).name;card.append(sampleNode(key,values[key]),el('b',null,label),el('span',null,values[key]));$('hanging-gallery').append(card);}}
const mc=document.modelContext;if(mc?.registerTool){const lifecycle=new AbortController();const register=tool=>{try{Promise.resolve(mc.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};register({name:'read_halloween_settings',title:'Halloweenの選択を読む',description:'現在の10項目、クリエイター名と添付数を読む。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>({mode,profile:currentProfile(),selections:mode==='auto'&&selectedProposal?{...selectedProposal,size:selections.size}:effectiveSelections(mode,selections),referenceCount:refs.length})});register({name:'create_halloween_prompt',title:'Halloween制作プロンプトを作る',description:'画面で設定した名前、参照、10項目を使って制作指示を作成し、画面と端末履歴へ反映する。画像生成や画像転送はしない。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async input=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('入力は空のオブジェクトにしてください。');const r=await generate();return {edition:r.edition,prompt:r.prompt,referenceCount:r.references.length};}});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
