import {setupEffects} from './effects.js?v=7';
import {colorWorlds} from './worlds.js?v=7';
import {mergeCreator} from './creator.js?v=7';
import {createPicker} from './picker.js?v=7';
import {modeKeys,modeCopy,initialSelections,effectiveSelections,propose} from './modes.js?v=7';
import {buildGuideBoard,buildReferenceBoard} from './guide-board.js?v=7';
import {profileEndpoint,profileHeaders} from './runtime-config.js?v=7';
import {questions,defaults,AUTO,normalizeCreator,resolveSelections} from './catalog.js?v=7';
import {composePrompt} from './prompt.js?v=7';
import {buildDirection} from './direction.js?v=7';
import {sampleFor,typePreview} from './examples.js?v=7';
import {makeZip} from './zip.js?v=7';
const $=id=>document.getElementById(id),STORAGE='mumeis-halloween-v2';
let saved={history:[],used:[],count:0},view='auto';
try{const v=JSON.parse(localStorage.getItem(STORAGE)||'null');if(v&&Array.isArray(v.history)&&Array.isArray(v.used))saved={history:v.history.filter(x=>x&&typeof x.prompt==='string'&&x.values&&questions.every(q=>typeof x.values[q.key]==='string')&&x.variant&&x.profile&&Array.isArray(x.references)).slice(0,12),used:v.used.filter(x=>x&&typeof x.signature==='string').slice(-2000),count:Number.isSafeInteger(v.count)?v.count:0};view=localStorage.getItem('halloween-view')||'auto';}catch{}
let selections=initialSelections(),refs=[],activeQuestion=null,currentResult=null,adding=false,creating=false,loadedProfile=null,profileController=null,toastTimer;
try{
 if(!localStorage.getItem(STORAGE)){
 const old=JSON.parse(localStorage.getItem('mumeis-halloween-v1')||'null');
 if(old?.history?.length){saved.count=Number.isSafeInteger(old.count)?old.count:0;saved.history=old.history.filter(r=>r&&typeof r.prompt==='string'&&r.values&&typeof r.values.size==='string'&&r.variant&&Array.isArray(r.references)).slice(0,12).map(r=>({...r,legacy:true,profile:{displayName:'旧版 / '+r.creator,biography:'',topics:[]},variant:{...r.variant,face:r.variant.angle,distance:'旧版の演出'}}));}
 }
}catch{}
const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
const rng=()=>{const b=new Uint32Array(1);crypto.getRandomValues(b);return b[0]/4294967296;};
const uid=()=>Date.now().toString(36).toUpperCase()+'-'+crypto.getRandomValues(new Uint32Array(1))[0].toString(36).toUpperCase();
const tell=s=>{$('toast').textContent=s;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),4500);};
function persist(){try{localStorage.setItem(STORAGE,JSON.stringify(saved));}catch{tell('端末への履歴保存ができません。制作セットを保存してください。');}}
function syncSaved(){try{const v=JSON.parse(localStorage.getItem(STORAGE)||'null');if(v&&Array.isArray(v.used)){saved.used=[...new Map([...saved.used,...v.used.filter(x=>x&&typeof x.signature==='string')].map(x=>[x.signature,x])).values()].slice(-2000);saved.count=Math.max(saved.count,Number.isSafeInteger(v.count)?v.count:0);}}catch{}}
function displayValue(q,v){return q.key==='size'?v.split('｜')[0]:v;}
function sampleNode(key,value){
 const sample=sampleFor(key,value),n=el('span','sample-thumb');
 n.setAttribute('role','img');n.setAttribute('aria-label',sample.label+'：'+value);n.title=sample.label;
 const image=(src,cls='sample-image')=>{const img=el('img',cls);img.src=src;img.alt='';img.loading='lazy';img.decoding='async';return img;};
 if(sample.kind==='image')n.append(image(sample.src));
 else if(sample.kind==='reference'){
 const ref=refs.find(r=>r.role==='identity');if(ref)n.append(image(ref.url));else n.append(el('span','sample-text','添付から\nつくる'));
 n.append(el('span','sample-caption','主参照を生かす'));
 }else if(sample.kind==='line'){
 n.className+=' line-sample';n.append(image(sampleFor('medium','実写風フィルム写真').src));
 if(sample.text)n.append(el('span','sample-line',sample.text));else n.append(el('span','sample-caption','セリフなし'));
 }else if(sample.kind==='size'){
 n.className+=' size-sample';const frame=el('span','size-frame');
 if(sample.ratio>=1){frame.style.width='88%';frame.style.aspectRatio=String(sample.ratio);}else{frame.style.height='88%';frame.style.aspectRatio=String(sample.ratio);}
 frame.append(image(sampleFor('design','通常の一枚絵').src));n.append(frame);
 }else if(sample.kind==='type'){
 const plan=typePreview(sample.mode);n.className+=' type-sample '+plan.className;
 if(!plan.className.includes('news'))n.append(image(sampleFor('design','通常の一枚絵').src));
 const copy=el('span','type-copy');plan.blocks.forEach((s,i)=>copy.append(el('span','type-block block-'+i,s)));n.append(copy);
 }else if(sample.kind==='auto'&&sample.srcs.length){
 const grid=el('span','auto-sample-grid');sample.srcs.forEach(src=>grid.append(image(src)));n.append(grid,el('span','sample-caption',key==='mood'?'毎回、表情も角度も':'おまかせの一例'));
 }else n.append(el('span','sample-text',sample.text));
 return n;
}
let boardArtKey='',attachmentMode='chatgpt';const effects=setupEffects();
let mode='detail',modeSnapshots={detail:{...selections}},proposals=[],selectedProposal=null;
function renderChoices(picked){
 const existing=new Map([...$('choices').children].map(b=>[b.dataset.key,b])),nodes=[];questions.forEach((q,i)=>{if(!modeKeys[mode].includes(q.key))return;const stamp=selections[q.key]+'|'+(q.key==='costume'?refs.find(r=>r.role==='identity')?.url||'':'');const old=existing.get(q.key);if(old?.dataset.stamp===stamp){old.classList.remove('just-picked');nodes.push(old);return;}const b=el('button','choice'+(picked===q.key?' just-picked':''));b.type='button';b.dataset.key=q.key;b.dataset.stamp=stamp;b.setAttribute('aria-haspopup','dialog');b.setAttribute('aria-label',q.name+'：'+displayValue(q,selections[q.key])+'。選択を変更');
 const copy=el('span','choice-content');copy.append(el('span','choice-name',String(i+1).padStart(2,'0')+' / '+q.name),el('b','choice-value',displayValue(q,selections[q.key])),el('span','choice-hint',q.hint));b.append(copy,sampleNode(q.key,selections[q.key]),el('span','choice-plus','＋'));b.addEventListener('click',()=>openPicker(q));nodes.push(b);});$('choices').replaceChildren(...nodes);renderBoard(mode==='auto'&&selectedProposal?{...selectedProposal,size:selections.size}:selections);
}
const paletteColors={'漆黒 × 琥珀 × 象牙':['#171513','#db7d20','#f4ebd4'],'深紅 × 黒 × 古金':['#811722','#171513','#b79538'],'群青 × 月白 × 銀':['#263774','#f1f5fc','#bbc5d1'],'紫 × 黒 × 酸性グリーン':['#623084','#171513','#d7ed26'],'藍墨 × 朱 × 和紙の白':['#263d51','#c54022','#ebe4d7'],'桃色 × 墨黒 × 真珠':['#ec92b6','#262122','#f1eaed'],'墨一色':['#141414','#707070','#f3f1eb'],'モノクローム':['#191919','#777','#eee'],'セピア':['#533e26','#ab8353','#e7caa2']};
colorWorlds.forEach(x=>paletteColors[x.value]=x.colors);
function renderBoard(values=selections,variant=null){
 const name=$('creator-name').value.trim();$('stage-id').textContent=name||'YOUR NAME';
 $('stage-line').textContent=values.type==='文字を一切入れない'||values.line==='セリフなし'?'':values.line===AUTO?'まだ見ぬ、一夜へ。':values.line;
 $('direction-title').textContent=values.theme===AUTO?'物語は、これから。':values.theme;$('direction-medium').textContent=values.medium+' / '+values.design;$('format-badge').textContent=values.size.split('｜')[2]||'おまかせ';
 $('direction-tags').replaceChildren(...[values.costume,values.mood,values.place].map(v=>el('span',null,v)));
 $('swatches').replaceChildren(...(paletteColors[values.palette]||['#f97818','#19120e','#fff6e9']).map(c=>{const n=el('span');n.style.background=c;return n;}));
 $('variant-summary').replaceChildren(el('b',null,'✦'),el('p',null,variant?[variant.face,variant.expression,variant.distance,variant.depth,variant.motion].join('\n'):'顔立ちは同じ。表情・向き・距離・身体の動きは新しく。'));
 $('issue-number').textContent='No. '+String(saved.count+1).padStart(3,'0');const artKey=JSON.stringify(['design','medium','theme','costume','palette'].map(k=>values[k]));if(artKey!==boardArtKey){boardArtKey=artKey;$('board-samples').replaceChildren(sampleNode('design',values.design),sampleNode('medium',values.medium));renderHangingGallery(values);}
}
function setView(mode){if(!['auto','phone','tablet','pc'].includes(mode))mode='auto';view=mode;document.body.dataset.view=mode;document.querySelectorAll('.view-switch button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===mode)));$('view-status').textContent={auto:'画面幅に合わせて表示',phone:'スマホの幅・大きな文字',tablet:'タブレットの幅・大きな選択枠',pc:'PCの幅・広い作業スペース'}[mode];try{localStorage.setItem('halloween-view',mode);}catch{}}
const picker=createPicker({$,el,sampleNode,readSelection:()=>selections,choose,onCustom:buildCustom,tell});
function openPicker(q){activeQuestion=q;$('picker-index').textContent=String(questions.indexOf(q)+1).padStart(2,'0')+' / 10';picker.open(q);}
function buildCustom(q){const form=el('form','custom-form');if(q.key==='size'){const w=el('input'),h=el('input');w.type=h.type='number';w.min=h.min='256';w.max=h.max='16000';w.required=h.required=true;w.placeholder='幅px';h.placeholder='高さpx';w.setAttribute('aria-label','希望の幅');h.setAttribute('aria-label','希望の高さ');form.append(w,el('span',null,'×'),h);form.addEventListener('submit',e=>{e.preventDefault();const a=Number(w.value),b=Number(h.value);if(!Number.isInteger(a)||!Number.isInteger(b)||a<256||b<256||a>16000||b>16000)return;const gcd=(x,y)=>y?gcd(y,x%y):x;const d=gcd(a,b);choose('自由サイズ｜'+a+'×'+b+'｜'+a/d+':'+b/d);});}else{const input=el('input');input.required=true;input.maxLength=160;input.placeholder='希望する'+q.name;input.setAttribute('aria-label',q.name+'を自由入力');form.append(input);form.addEventListener('submit',e=>{e.preventDefault();const v=input.value.trim().replace(/[\r\n]/g,' ');if(v)choose(v);});}const b=el('button','dark-button','この内容にする');b.type='submit';form.append(b);$('custom-area').append(form,el('p','microcopy',q.key==='size'?'256〜16,000px。生成環境に対応する実寸で出力されます。':'具体的な技法や角度も指定できます。160文字まで。'));form.querySelector('input').focus();}
function choose(v){selections[activeQuestion.key]=v;const key=activeQuestion.key;renderChoices(key);$('picker').close();document.querySelector('[data-key="'+key+'"]')?.focus();tell(activeQuestion.name+'を選びました');}
function summarizeName(raw){const bracket=raw.match(/^[〖【「『]([^〗】」』]+)[〗】」』]/);return bracket?bracket[1].trim():raw;}
async function loadProfile(){
 const id=normalizeCreator($('creator').value);if(!id){tell('noteのIDまたはプロフィールURLを入力してください。');$('creator').focus();return;}
 if(profileController&&profileController.profileId===id)return profileController.done;if(loadedProfile?.id===id&&loadedProfile.ready)return true;profileController?.abort();const controller=new AbortController();profileController=controller;controller.profileId=id;loadedProfile=null;$('load-profile').disabled=true;$('load-profile').textContent='準備中…';$('profile-status').textContent='あなたの世界観を整えています。選択や遊びはそのまま楽しめます。';
 let finish;controller.done=new Promise(r=>finish=r);try{let page=1;const pages=new Set(),signatures=new Set();while(page){if(pages.has(page))throw new Error('クリエイターの準備が途中で止まりました。');pages.add(page);let data;for(let attempt=0;attempt<2;attempt++){try{const response=await fetch(profileEndpoint+'?id='+encodeURIComponent(id)+'&page='+page,{signal:AbortSignal.any([controller.signal,AbortSignal.timeout(45000)]),headers:profileHeaders});data=await response.json();if(!response.ok||typeof data.name!=='string')throw new Error(data.error||'クリエイター情報を整えられませんでした。');break;}catch(e){if(controller.signal.aborted||attempt===1)throw e;}}if(controller!==profileController)return false;const signature=data.pagination?.keys?.join('|');if(signature&&signatures.has(signature))throw new Error('クリエイターの準備が途中で止まりました。');if(signature)signatures.add(signature);loadedProfile=mergeCreator(loadedProfile,data);if(page===1){$('creator-name').value=summarizeName(data.name);$('activity').value=data.biography||'';$('profile-editor').open=false;}syncProfilePreview();renderBoard();page=data.pagination?.nextPage||null;}
 loadedProfile.ready=true;$('profile-status').textContent=loadedProfile.bodyRead?.status==='partial'?'クリエイター設定は使えます。世界観の準備に一部届かない情報がありました。':'クリエイター設定ができました。そのまま制作できます。';$('profile-status').className='profile-status success';tell('あなたの世界観で制作できます。');return true;}
 catch(e){if(controller!==profileController||e.name==='AbortError')return false;if(loadedProfile)loadedProfile.ready=false;$('profile-editor').open=true;syncProfilePreview();$('profile-status').textContent=(e.message||'準備できませんでした。')+' 名前・活動は手入力できます。';$('profile-status').className='profile-status error';}
 finally{finish(!!loadedProfile&&loadedProfile.id===id);if(controller===profileController){profileController=null;$('load-profile').disabled=false;$('load-profile').textContent='IDから読み込む';}}
}
const topicsList=['共同マガジン','コミュニティ','メンバーシップ','子育て','育児','ワーママ','医療','福祉','介護','看護','イラスト','AI','創作','小説','エッセイ','詩','漫画','写真','音楽','料理','旅行','読書','映画','デザイン','アート','日記','仕事','タイミー','副業','収益化','学習','教育','健康','スポーツ','ゲーム','ファッション','動物','自然'];
function currentProfile(){const name=$('creator-name').value.trim(),bio=$('activity').value.trim(),id=normalizeCreator($('creator').value);const base=loadedProfile&&loadedProfile.id===id?loadedProfile:{};const corpus=bio+' '+(base.titles||[]).join(' ');const topics=[...new Set([...topicsList.filter(t=>t==='AI'?/\bAI\b/i.test(corpus):corpus.includes(t)),...(bio===(base.biography||'')?base.topics||[]:[])])];return {...base,id:id||'',name:base.name||name,displayName:name,biography:bio,topics,titles:base.titles||[],source:base.source||'作成者の手動入力'};}
function syncProfilePreview(){const p=currentProfile();$('profile-preview').hidden=!p.displayName;$('profile-name').textContent=p.displayName;$('profile-bio').textContent=p.biography||'あなたの創作を、Halloweenの世界へ。';renderTopics(p.topics);$('profile-ideas').hidden=!p.inspiration?.themes?.length;}
function renderTopics(topics){$('activity-topics').replaceChildren(...topics.slice(0,10).map(t=>el('span',null,t)));}
async function addFiles(files){
 if(adding){tell('画像を読み込み中です。');return;}const incoming=Array.from(files);if(!incoming.length)return;setAttachmentMode('bundle');adding=true;$('generate').disabled=true;
 try{for(const file of incoming){if(refs.length>=4){tell('添付は最大4枚です。');break;}if(!['image/png','image/jpeg','image/webp','image/gif'].includes(file.type)){tell('PNG・JPG・WebP・GIFを選んでください。');continue;}if(file.size>12*1024*1024){tell('画像は1枚12MBまでです。');continue;}const name=file.name.replace(/[\r\n<>]/g,'_').slice(0,120)||'reference.png';if(refs.some(r=>r.name===name&&r.file.size===file.size&&r.file.lastModified===file.lastModified)){tell('同じ画像は添付済みです。');continue;}const url=URL.createObjectURL(file);try{const img=new Image();await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=()=>reject(new Error('画像を読み込めませんでした。'));img.src=url;});refs.push({file,url,name,width:img.naturalWidth,height:img.naturalHeight,role:refs.length?'support':'identity'});renderRefs();}catch(e){URL.revokeObjectURL(url);tell(e.message);}}}finally{adding=false;$('generate').disabled=false;$('image-input').value='';}
}
function renderRefs(refresh=true){
 $('references').replaceChildren();refs.forEach((r,i)=>{const f=el('figure','reference-thumb'),img=el('img');img.src=r.url;img.alt=r.name;const remove=el('button','remove-ref','×');remove.type='button';remove.setAttribute('aria-label',r.name+'を取り除く');remove.addEventListener('click',()=>{URL.revokeObjectURL(r.url);refs.splice(i,1);if(refs.length&&!refs.some(x=>x.role==='identity'))refs[0].role='identity';renderRefs();});const role=el('select');role.setAttribute('aria-label',r.name+'の画像の役割');for(const [v,label]of [['identity','キャラの主参照'],['support','補助参照'],['avoid','似せない前作']]){const o=el('option',null,label);o.value=v;role.append(o);}role.value=r.role;role.addEventListener('change',()=>{if(role.value==='identity')refs.forEach(x=>{if(x!==r&&x.role==='identity')x.role='support';});r.role=role.value;renderRefs();});f.append(img,remove,el('figcaption',null,String(i+1).padStart(2,'0')+' / '+r.width+'×'+r.height),role);$('references').append(f);});const primary=refs.find(r=>r.role==='identity');if(primary){$('main-reference').src=primary.url;$('main-reference').hidden=false;$('empty-reference').hidden=true;}else{$('main-reference').removeAttribute('src');$('main-reference').hidden=true;$('empty-reference').hidden=false;}$('form-error').hidden=true;if(refresh)renderChoices();
}
function formError(s,focus){$('form-error').textContent=s;$('form-error').hidden=false;focus?.focus();}
async function generate(lockedValues=null){
 if(creating||adding)throw new Error('制作の準備中です。');if(mode==='auto'&&!selectedProposal){formError('気に入った作例の組み合わせを一つ選んでください。',$('propose'));throw new Error('組み合わせを選んでください。');}const creator=normalizeCreator($('creator').value);if(creator===null){formError('noteのIDまたはURLの形式を確認してください。',$('creator'));throw new Error('ID形式が正しくありません。');}if(creator&&profileController?.profileId===creator)await profileController.done;else if(creator&&(!loadedProfile||loadedProfile.id!==creator)&&!$('profile-editor').open)await loadProfile();const profile=currentProfile();if(!profile.displayName){$('profile-editor').open=true;formError('IDから名前を読み込むか、クリエイター名を入力してください。',$('creator-name'));throw new Error('クリエイター名がありません。');}if(attachmentMode==='bundle'&&!refs.some(r=>r.role==='identity')){formError('キャラの主参照を1枚以上、添付してください。',$('image-input'));throw new Error('主参照画像がありません。');}
 if(creating)throw new Error('制作の準備中です。');creating=true;$('generate').disabled=true;$('generate').textContent='選んだ作例と制作指示を準備中…';$('generation-status').hidden=false;$('generation-status').textContent='作例の画像を読み込んでいます…';try{syncSaved();const input=lockedValues?{...lockedValues}:mode==='auto'&&selectedProposal?{...selectedProposal,size:selections.size}:effectiveSelections(mode,selections);const values=resolveSelections(input,rng);if(input.theme===AUTO&&profile.inspiration?.themes?.length)values.theme=profile.inspiration.themes[Math.floor(rng()*profile.inspiration.themes.length)];if(input.line===AUTO&&profile.inspiration?.phrases?.length)values.line=profile.inspiration.phrases[Math.floor(rng()*profile.inspiration.phrases.length)];if(input.mood===AUTO)values.mood='毎回大胆に変える';const variant=buildDirection(saved.used,values.mood,rng),edition=uid();const ordered=attachmentMode==='bundle'?[refs.find(r=>r.role==='identity'),...refs.filter(r=>r.role!=='identity')]:[];const metadata=ordered.length?ordered.map((r,i)=>({name:'reference-'+String(i+1).padStart(2,'0')+'-'+r.name,role:r.role,width:r.width,height:r.height})):[{name:'ChatGPTへ直接添付するキャラの主参照',role:'identity'}];const guide=await buildGuideBoard(values,ordered[0]);$('generation-status').textContent='選択した画風・形式・雰囲気を制作指示へ照合しています…';const referenceBoardFile=ordered.length?await buildReferenceBoard(guide.file,ordered):null;const prompt=composePrompt({creator:creator||'',profile,values,variant,references:metadata,edition,styleGuide:{name:referenceBoardFile?.name||guide.file.name,combined:!!referenceBoardFile,cells:guide.cells},random:rng});saved.count++;const r={creator:creator||'',profile,values,variant,edition,prompt,date:new Date().toISOString(),references:metadata,localRefs:[...ordered],guideFile:guide.file,referenceBoardFile,attachmentMode,isFresh:true,guideCells:guide.cells,count:saved.count};const {localRefs,guideFile,referenceBoardFile:boardFile,isFresh,...record}=r;saved.used.push({signature:variant.signature,family:variant.family,face:variant.face,expression:variant.expression,distance:variant.distance,pose:variant.pose,layout:variant.layout});saved.used=saved.used.slice(-2000);saved.history.unshift(record);saved.history=saved.history.slice(0,12);persist();renderHistory();$('form-error').hidden=true;renderBoard(values,variant);$('issue-number').textContent='No. '+String(saved.count).padStart(3,'0');$('stage').classList.remove('flash');void $('stage').offsetWidth;$('stage').classList.add('flash');showResult(r);effects.celebrate();return r;}finally{creating=false;$('generate').disabled=false;$('generate').textContent='制作プロンプトをつくる ✦';$('generation-status').hidden=true;}
}
function shareFiles(r){return [...r.localRefs.map((x,i)=>new File([x.file],r.references[i].name,{type:x.file.type})),...(r.guideFile?[r.guideFile]:[]),new File([r.prompt],'Halloween-prompt.txt',{type:'text/plain'})];}
let currentGuideURL=null;
function showResult(r){
 currentResult=r;$('prompt-output').value=r.prompt;$('result-edition').textContent='EDITION / '+r.edition;const live=Array.isArray(r.localRefs)&&r.localRefs.length>0,fresh=!!r.isFresh;$('result-intro').textContent=r.legacy?'旧版で作成した履歴です。新仕様で作る場合は、入力画面で名前と参照を設定して制作してください。':live?'参照画像とプロンプトを、両方渡してから生成します。':'履歴のプロンプトです。作成時の参照画像をChatGPTに添付してください。';$('result-summary').replaceChildren(el('h3',null,r.values.theme),el('p',null,r.profile.displayName+' / '+r.values.design+' / '+r.values.medium),el('p',null,r.values.size.split('｜').slice(0,2).join(' / ')+'px'),el('p','detail',[r.variant.face,r.variant.expression,r.variant.distance].join(' / ')));$('result-refs').replaceChildren();if(live)r.localRefs.forEach((x,i)=>{const f=el('figure');const im=el('img');im.src=x.url;im.alt=x.name;f.append(im,el('figcaption',null,String(i+1).padStart(2,'0')+' / '+(x.role==='avoid'?'似せない前作':x.role==='identity'?'主参照':'補助')));$('result-refs').append(f);});
 $('download-guide').disabled=!r.guideFile;$('download-kit').disabled=!live;$('copy-image').disabled=!live;$('share-all').disabled=!fresh;$('again').hidden=!fresh;$('download-board').hidden=!r.referenceBoardFile;$('share-board').hidden=!r.referenceBoardFile;$('share-all').hidden=!!r.referenceBoardFile;$('transfer-status').textContent=live?(navigator.canShare?.({files:shareFiles(r)})?'この端末は画像付き共有に対応しています。共有先にChatGPTを選び、画像と指示が両方届いたことを確認してください。':'この端末では画像付き共有を利用できない場合があります。画像コピーまたは制作セット保存を使えます。'):'履歴には画像データを保存していません。';$('kit-note').textContent=r.referenceBoardFile?'ZIPを解凍して reference-board.jpg と prompt.txt を添付します。キャラと作例が１枚にまとまっています。':'作例画像とキャラ画像をChatGPTへ添付し、プロンプトを貼り付けます。';if(r.guideFile){if(currentGuideURL)URL.revokeObjectURL(currentGuideURL);currentGuideURL=URL.createObjectURL(r.referenceBoardFile||r.guideFile);const f=el('figure','guide-preview'),im=el('img');im.src=currentGuideURL;im.alt='選んだ作例と制作条件の画像セット';f.append(im,el('figcaption',null,'選んだ作例 / キャラの顔は主参照を優先'));$('result-refs').append(f);}if(!$('result').open)$('result').showModal();if(fresh&&!live){$('result-intro').textContent='キャラ画像はChatGPTへ一度だけ添付します。このツールへのキャラ添付は不要です。';$('transfer-status').textContent='プロンプトをコピーし、作例画像とキャラ画像をChatGPTに添付してください。';}
}
async function copyPrompt(){if(!currentResult)return false;try{await navigator.clipboard.writeText(currentResult.prompt);tell('プロンプトをコピーしました。参照画像も一緒に添付してください。');return true;}catch{const ta=$('prompt-output');ta.closest('details').open=true;ta.focus();ta.select();try{if(document.execCommand('copy')){tell('プロンプトをコピーしました。');return true;}}catch{}tell('全文を選択しました。長押しでコピーできます。');return false;}}
async function shareAll(){const r=currentResult;if(!r?.isFresh)return;const files=shareFiles(r);if(!navigator.share||!navigator.canShare?.({files})){tell('画像付き共有はこの端末で使えません。画像コピーまたは制作セット保存を使ってください。');$('transfer-status').textContent='ChatGPTを開いて画像を添付し、コピーしたプロンプトを貼り付けてください。';return;}try{await navigator.share({files,text:r.prompt,title:'Halloween制作セット'});$('transfer-status').textContent='共有先で画像とプロンプトの両方を確認してから送信してください。';}catch(e){if(e.name!=='AbortError')tell('共有できませんでした。画像とプロンプトを別々に添付できます。');}}
async function imagePNG(r){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>{try{const c=document.createElement('canvas');c.width=img.naturalWidth;c.height=img.naturalHeight;c.getContext('2d').drawImage(img,0,0);c.toBlob(b=>b?resolve(b):reject(new Error('画像を変換できませんでした。')),'image/png');}catch(e){reject(e);}};img.onerror=reject;img.src=r.url;});}
async function copyImage(){const r=currentResult?.localRefs?.find(x=>x.role==='identity');if(!r)return;if(!navigator.clipboard?.write||typeof ClipboardItem==='undefined'){download(r.file,'reference-'+r.name);tell('画像を保存しました。ChatGPTに添付してください。');return;}try{const promise=imagePNG(r);await navigator.clipboard.write([new ClipboardItem({'image/png':promise})]);$('transfer-status').textContent='主参照画像をコピーしました。ChatGPTへ貼り付けた後、プロンプトも貼り付けてください。';tell('主参照の画像をコピーしました。ChatGPTで貼り付けてください。');}catch{download(r.file,'reference-'+r.name);tell('画像コピーに対応していないため、画像を保存しました。');}}
function download(blob,name){const url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
async function downloadKit(){const r=currentResult;if(!r?.localRefs?.length)return;const b=$('download-kit');b.disabled=true;b.textContent='セットを準備中…';try{const files=[{name:'prompt.txt',data:new TextEncoder().encode(r.prompt)},{name:'使い方.txt',data:new TextEncoder().encode('Halloween制作セット\n\n1. ZIPを解凍します。\n2. reference-board.jpg と prompt.txt を同じChatGPTのメッセージに添付します。\n3. 画像と指示が両方届いたことを確認して送信します。\n\nreference-01が主参照。前作比較の画像はprompt.txtに指定した役割で使用します。\n名前：'+r.profile.displayName+'\n制作番号：'+r.edition)}];if(r.referenceBoardFile)files.push({name:r.referenceBoardFile.name,data:new Uint8Array(await r.referenceBoardFile.arrayBuffer())});if(r.guideFile)files.push({name:r.guideFile.name,data:new Uint8Array(await r.guideFile.arrayBuffer())});for(let i=0;i<r.localRefs.length;i++)files.push({name:r.references[i].name,data:new Uint8Array(await r.localRefs[i].file.arrayBuffer())});download(makeZip(files),'Halloween-'+r.edition+'.zip');tell('画像とプロンプトのセットを保存しました。');}catch{tell('保存に失敗しました。プロンプトだけ保存し、元画像を添付してください。');}finally{b.disabled=false;b.textContent='画像＋プロンプトを保存';}}
function renderHistory(){$('history').replaceChildren();if(!saved.history.length){$('history').append(el('p','history-empty','まだ白紙のコレクション。最初の一夜をつくろう。'));return;}saved.history.forEach(r=>{const b=el('button','history-card');b.type='button';b.append(sampleNode('medium',r.values.medium),el('span','hist-id','No. '+String(r.count).padStart(3,'0')),el('b',null,r.values.theme),el('p',null,r.profile.displayName+' / '+r.values.medium),el('small',null,r.variant.face));b.addEventListener('click',()=>showResult(r));$('history').append(b);});}
function setAttachmentMode(next){attachmentMode=next==='bundle'?'bundle':'chatgpt';document.querySelectorAll('[name="attachment-mode"]').forEach(r=>r.checked=r.value===attachmentMode);$('drop-zone').hidden=attachmentMode!=='bundle';$('reference-note').hidden=attachmentMode!=='bundle';$('attachment-mode-note').textContent=attachmentMode==='bundle'?'キャラと選んだ作例を１枚の資料画像にまとめます。共有が使えない場合も、この１枚だけ保存して渡せます。':'キャラ画像はここでは不要。制作時にChatGPTへ一度だけ添付します。';}
document.querySelectorAll('[name="attachment-mode"]').forEach(r=>r.addEventListener('change',()=>setAttachmentMode(r.value)));
$('profile-ideas').addEventListener('click',()=>{const p=currentProfile(),idea=p.inspiration;if(!idea?.themes?.length)return;selections.theme=idea.themes[Math.floor(rng()*idea.themes.length)];if(idea.phrases?.length)selections.line=idea.phrases[Math.floor(rng()*idea.phrases.length)];if(mode==='auto')selectedProposal={...(selectedProposal||propose(selections,rng)),theme:selections.theme,line:selections.line,size:selections.size};renderChoices();tell('本文の話題からテーマとセリフを提案しました。');});
$('download-board').addEventListener('click',()=>{if(currentResult?.referenceBoardFile)download(currentResult.referenceBoardFile,currentResult.referenceBoardFile.name);});
$('share-board').addEventListener('click',async()=>{const r=currentResult;if(!r?.referenceBoardFile)return;const files=[r.referenceBoardFile];if(!navigator.share||!navigator.canShare?.({files})){download(r.referenceBoardFile,r.referenceBoardFile.name);tell('キャラと作例の１枚を保存しました。プロンプトをコピーしてChatGPTへ渡してください。');return;}try{await navigator.share({files,text:r.prompt,title:'Halloween制作資料'});}catch(e){if(e.name!=='AbortError')tell('共有できませんでした。「まとめた１枚を保存」を使ってください。');}});
$('load-profile').addEventListener('click',loadProfile);$('creator').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();loadProfile();}});$('creator').addEventListener('input',()=>{profileController?.abort();profileController=null;$('load-profile').disabled=false;$('load-profile').textContent='IDから読み込む';if(loadedProfile&&normalizeCreator($('creator').value)!==loadedProfile.id){if($('creator-name').value===summarizeName(loadedProfile.name))$('creator-name').value='';if($('activity').value===loadedProfile.biography)$('activity').value='';loadedProfile=null;renderTopics([]);}$('profile-status').className='profile-status';$('profile-status').textContent='IDを入力すると、名前と活動内容を読み込みます。';syncProfilePreview();renderBoard();});
$('creator').addEventListener('change',()=>{if(normalizeCreator($('creator').value))loadProfile();});
$('creator-name').addEventListener('input',()=>{syncProfilePreview();renderBoard();$('form-error').hidden=true;});$('activity').addEventListener('input',syncProfilePreview);$('image-input').addEventListener('change',e=>addFiles(e.target.files));
document.addEventListener('paste',e=>{const files=Array.from(e.clipboardData?.items||[]).filter(i=>i.kind==='file').map(i=>i.getAsFile()).filter(Boolean);if(files.length&&!$('result').open&&!$('picker').open){e.preventDefault();addFiles(files);}});$('drop-zone').addEventListener('dragover',e=>{e.preventDefault();$('drop-zone').classList.add('dragover');});$('drop-zone').addEventListener('dragleave',()=>$('drop-zone').classList.remove('dragover'));$('drop-zone').addEventListener('drop',e=>{e.preventDefault();$('drop-zone').classList.remove('dragover');addFiles(e.dataTransfer.files);});window.addEventListener('dragover',e=>{if(e.dataTransfer?.types.includes('Files'))e.preventDefault();});window.addEventListener('drop',e=>{if(e.dataTransfer?.types.includes('Files'))e.preventDefault();});
$('shuffle').addEventListener('click',()=>{const size=selections.size;selections=resolveSelections(Object.fromEntries(questions.map(q=>[q.key,AUTO])),rng);selections.mood='毎回大胆に変える';selections.size=size;if(mode==='auto')selectedProposal={...selections};renderChoices();tell('サイズを保ったまま、新しい組み合わせを選びました。');});$('generate').addEventListener('click',async()=>{try{await generate();}catch(e){if($('form-error').hidden)tell(e.message);}});$('copy').addEventListener('click',copyPrompt);$('share-all').addEventListener('click',shareAll);$('copy-image').addEventListener('click',copyImage);$('chatgpt').addEventListener('click',()=>{window.open('https://chatgpt.com/','_blank','noopener,noreferrer');tell('参照画像とプロンプトを両方添付してから送信してください。');});$('download-kit').addEventListener('click',downloadKit);$('download-text').addEventListener('click',()=>{if(currentResult)download(new Blob([currentResult.prompt],{type:'text/plain;charset=utf-8'}),'Halloween-'+currentResult.edition+'.txt');});
$('again').addEventListener('click',async()=>{try{const old=currentResult;selections={...old.values};if(mode==='auto')selectedProposal={...old.values};$('creator').value=old.creator;$('creator-name').value=old.profile.displayName;$('activity').value=old.profile.biography;loadedProfile=old.profile;setAttachmentMode(old.attachmentMode||'bundle');syncProfilePreview();refs.forEach(r=>URL.revokeObjectURL(r.url));refs=old.localRefs.map(r=>({...r,url:URL.createObjectURL(r.file)}));renderRefs();renderChoices();await generate(old.values);}catch(e){tell(e.message);}});$('help').addEventListener('click',()=>$('help-dialog').showModal());document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>$(b.dataset.close).close()));document.querySelectorAll('.view-switch button').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}}));$('clear-history').addEventListener('click',()=>{if(!saved.history.length)return tell('履歴はありません。');if(window.confirm('この端末の制作履歴を消しますか？演出の重複回避記録は残ります。')){saved.history=[];persist();renderHistory();tell('履歴を消しました。');}});
document.querySelectorAll('.mode-switch button').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));$('propose').addEventListener('click',makeProposals);$('download-guide').addEventListener('click',()=>{if(currentResult?.guideFile)download(currentResult.guideFile,currentResult.guideFile.name);});
const motionMedia=window.matchMedia('(prefers-reduced-motion: reduce)');let motion=true;try{motion=localStorage.getItem('halloween-motion')!=='off';}catch{}function setMotion(on){motion=on;const enabled=on&&!motionMedia.matches;document.body.dataset.motion=enabled?'on':'off';$('motion-toggle').replaceChildren(el('b',null,'演出 '+(enabled?'ON':'OFF')),el('small',null,motionMedia.matches?'端末の省動作設定を優先':'タップで'+(enabled?'OFF':'ON')+'にする'));$('motion-toggle').setAttribute('aria-pressed',String(enabled));$('motion-toggle').disabled=motionMedia.matches;$('play-state').textContent=enabled?'魔法が動いています':'演出は止まっています';$('playground').dataset.paused=String(!enabled);['play-spell','play-ghosts'].forEach(id=>$(id).disabled=!enabled);effects.sync();try{localStorage.setItem('halloween-motion',on?'on':'off');}catch{}}setMotion(motion);motionMedia.addEventListener('change',()=>setMotion(motion));$('motion-toggle').addEventListener('click',()=>setMotion(!motion));$('light-play').addEventListener('click',()=>{const on=document.body.dataset.lights!=='night';document.body.dataset.lights=on?'night':'day';$('light-play').setAttribute('aria-pressed',String(on));$('light-play').textContent=(on?'夜の工房':'昼の工房')+' ／ タップで'+(on?'昼':'夜')+'へ';});
setView(view);renderRefs(false);setMode('detail');renderHistory();

function setMode(next){if(!modeKeys[next])return;modeSnapshots[mode]={...selections};mode=next;selections={...(modeSnapshots[next]||initialSelections()),size:selections.size};document.body.dataset.mode=mode;document.querySelectorAll('.mode-switch button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===mode)));$('mode-description').textContent=modeCopy[mode];$('choice-heading').textContent={detail:'2. 10項目で決める',simple:'2. 5項目だけ選ぶ',auto:'2. 見本の組み合わせで決める'}[mode];$('auto-proposals').hidden=mode!=='auto';$('shuffle').hidden=mode==='auto';renderChoices();if(mode==='auto'&&!proposals.length)makeProposals();}
function makeProposals(){proposals=Array.from({length:3},()=>propose(selections,rng));selectedProposal=null;$('proposal-cards').replaceChildren();proposals.forEach((values,i)=>{const b=el('button','proposal-card');b.type='button';b.setAttribute('aria-pressed','false');const arts=el('span','proposal-art');arts.append(sampleNode('medium',values.medium),sampleNode('design',values.design));b.append(arts,el('b',null,values.medium),el('span',null,values.design),el('small',null,values.theme+' / '+values.palette));b.addEventListener('click',()=>{selectedProposal={...values,size:selections.size};document.querySelectorAll('.proposal-card').forEach(n=>n.setAttribute('aria-pressed',String(n===b)));renderBoard(selectedProposal);tell('この作例の組み合わせを選びました。');});$('proposal-cards').append(b);});renderBoard({...initialSelections(),size:selections.size});$('generation-status').hidden=true;}
function renderHangingGallery(values){if(!$('hanging-gallery'))return;$('hanging-gallery').replaceChildren();for(const key of ['medium','design','theme','costume','palette']){const card=el('div','hanging-card');const label=questions.find(q=>q.key===key).name;card.append(sampleNode(key,values[key]),el('b',null,label),el('span',null,values[key]));$('hanging-gallery').append(card);}}
const mc=document.modelContext;if(mc?.registerTool){const lifecycle=new AbortController();const register=tool=>{try{Promise.resolve(mc.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};register({name:'read_halloween_settings',title:'Halloweenの選択を読む',description:'現在の10項目、クリエイター名と添付数を読む。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>({mode,profile:currentProfile(),selections:mode==='auto'&&selectedProposal?{...selectedProposal,size:selections.size}:effectiveSelections(mode,selections),referenceCount:refs.length})});register({name:'create_halloween_prompt',title:'Halloween制作プロンプトを作る',description:'画面で設定した名前、参照、10項目を使って制作指示を作成し、画面と端末履歴へ反映する。画像生成や画像転送はしない。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async input=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('入力は空のオブジェクトにしてください。');const r=await generate();return {edition:r.edition,prompt:r.prompt,referenceCount:r.references.length};}});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
