import {releaseCanvas} from './image-resources.js?v=28.4.3';
export function createCropEditor({$,onApply,tell}){
 const dialog=$('crop-dialog'),canvas=$('crop-canvas'),ctx=canvas.getContext('2d'),zoomInput=$('crop-zoom'),ratioInput=$('crop-ratio');
 let ref=null,img=null,sourceURL='',zoom=1,cx=0,cy=0,frame=null,scale=1,raf=0,opening=0,busy=false;const pointers=new Map();
 const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
 function geometry(){if(!img)return;const ratio=ratioInput.value==='original'?img.naturalWidth/img.naturalHeight:Number(ratioInput.value);const maxW=canvas.width-64,maxH=canvas.height-64;let w=maxW,h=w/ratio;if(h>maxH){h=maxH;w=h*ratio;}frame={x:(canvas.width-w)/2,y:(canvas.height-h)/2,w,h};scale=Math.max(w/img.naturalWidth,h/img.naturalHeight)*zoom;cx=clamp(cx,w/(2*scale),img.naturalWidth-w/(2*scale));cy=clamp(cy,h/(2*scale),img.naturalHeight-h/(2*scale));}
 function paint(){raf=0;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#271834';ctx.fillRect(0,0,canvas.width,canvas.height);if(!img)return;geometry();const x=canvas.width/2-cx*scale,y=canvas.height/2-cy*scale;ctx.drawImage(img,x,y,img.naturalWidth*scale,img.naturalHeight*scale);ctx.fillStyle='#160c24b3';ctx.fillRect(0,0,canvas.width,frame.y);ctx.fillRect(0,frame.y+frame.h,canvas.width,canvas.height-frame.y-frame.h);ctx.fillRect(0,frame.y,frame.x,frame.h);ctx.fillRect(frame.x+frame.w,frame.y,canvas.width-frame.x-frame.w,frame.h);ctx.strokeStyle='#ffcf85';ctx.lineWidth=4;ctx.strokeRect(frame.x,frame.y,frame.w,frame.h);ctx.strokeStyle='#fff8de66';ctx.lineWidth=1;for(let i=1;i<3;i++){ctx.beginPath();ctx.moveTo(frame.x+frame.w*i/3,frame.y);ctx.lineTo(frame.x+frame.w*i/3,frame.y+frame.h);ctx.moveTo(frame.x,frame.y+frame.h*i/3);ctx.lineTo(frame.x+frame.w,frame.y+frame.h*i/3);ctx.stroke();}zoomInput.value=zoom.toFixed(2);$('crop-zoom-value').textContent=zoom.toFixed(2)+'倍';$('crop-dimensions').textContent='切り抜き範囲：'+Math.round(frame.w/scale)+' × '+Math.round(frame.h/scale)+'px';}
 function schedule(){if(!raf)raf=requestAnimationFrame(paint);}
 function point(e){const r=canvas.getBoundingClientRect();return {x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height};}
 function zoomAt(next,p={x:canvas.width/2,y:canvas.height/2}){if(!img)return;geometry();const old=scale;zoom=clamp(next,1,5);geometry();cx+=(p.x-canvas.width/2)*(1/old-1/scale);cy+=(p.y-canvas.height/2)*(1/old-1/scale);schedule();}
 canvas.addEventListener('pointerdown',e=>{if(!img||busy)return;e.preventDefault();canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,point(e));});
 canvas.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId)||!img||busy)return;e.preventDefault();const old=[...pointers.values()],previous=pointers.get(e.pointerId),next=point(e);pointers.set(e.pointerId,next);const now=[...pointers.values()];if(now.length===1){cx-=(next.x-previous.x)/scale;cy-=(next.y-previous.y)/scale;schedule();}else if(now.length===2){const length=a=>Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y),before=length(old);if(before>0)zoomAt(zoom*length(now)/before,{x:(now[0].x+now[1].x)/2,y:(now[0].y+now[1].y)/2});}});
 for(const type of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(type,e=>pointers.delete(e.pointerId));
 canvas.addEventListener('wheel',e=>{if(!img)return;e.preventDefault();zoomAt(zoom*Math.exp(-e.deltaY*.0015),point(e));},{passive:false});
 canvas.addEventListener('keydown',e=>{if(!img||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();const d=18/scale;cx+=e.key==='ArrowRight'?d:e.key==='ArrowLeft'?-d:0;cy+=e.key==='ArrowDown'?d:e.key==='ArrowUp'?-d:0;schedule();});
 zoomInput.addEventListener('input',()=>zoomAt(Number(zoomInput.value)));ratioInput.addEventListener('change',()=>{zoom=1;schedule();});
 $('crop-reset').addEventListener('click',()=>{if(!img)return;zoom=1;cx=img.naturalWidth/2;cy=img.naturalHeight/2;ratioInput.value='original';paint();});
 $('crop-original').addEventListener('click',async()=>{if(!ref||busy)return;busy=true;try{await onApply(ref,{file:ref.originalFile||ref.file,crop:null,restore:true});dialog.close();}finally{busy=false;}});
 $('crop-apply').addEventListener('click',async()=>{if(!ref||!img||busy)return;busy=true;$('crop-apply').disabled=true;let out=null;try{geometry();const crop={ratio:ratioInput.value,zoom,cx:cx/img.naturalWidth,cy:cy/img.naturalHeight},sw=frame.w/scale,sh=frame.h/scale;const factor=Math.min(1,4096/Math.max(sw,sh));out=document.createElement('canvas');out.width=Math.max(1,Math.round(sw*factor));out.height=Math.max(1,Math.round(sh*factor));out.getContext('2d').drawImage(img,cx-sw/2,cy-sh/2,sw,sh,0,0,out.width,out.height);const original=ref.originalFile||ref.file,mime=original.type==='image/jpeg'?'image/jpeg':'image/png';const blob=await new Promise(r=>out.toBlob(r,mime,.96));if(!blob)throw new Error('切り抜きを保存できませんでした。');const name=original.name.replace(/\.[^.]+$/,'')+'-crop.'+(mime==='image/jpeg'?'jpg':'png');await onApply(ref,{file:new File([blob],name,{type:mime}),crop,width:out.width,height:out.height});dialog.close();tell('切り抜いた画像を制作資料に使います。');}catch(e){tell(e.message);}finally{releaseCanvas(out);busy=false;$('crop-apply').disabled=false;}});
 dialog.addEventListener('close',()=>{opening++;pointers.clear();cancelAnimationFrame(raf);raf=0;img?.removeAttribute('src');if(sourceURL)URL.revokeObjectURL(sourceURL);sourceURL='';img=null;ref=null;frame=null;ctx.clearRect(0,0,canvas.width,canvas.height);});
 return {async open(target){const token=++opening;ref=target;img=null;busy=false;$('crop-apply').disabled=true;$('crop-dimensions').textContent='画像を準備しています…';dialog.showModal();paint();sourceURL=URL.createObjectURL(target.originalFile||target.file);const next=new Image();try{await new Promise((resolve,reject)=>{next.onload=resolve;next.onerror=()=>reject(new Error('画像を開けませんでした。'));next.src=sourceURL;});if(token!==opening)return;img=next;const crop=target.crop;ratioInput.value=crop?.ratio||'original';zoom=crop?.zoom||1;cx=(crop?.cx??.5)*img.naturalWidth;cy=(crop?.cy??.5)*img.naturalHeight;paint();$('crop-apply').disabled=false;}catch(e){tell(e.message);dialog.close();}}};
}
