import {createSpells,studioIcons} from './spells.js?v=20.0.0';
import {icons} from './halloween-icons.js?v=20.0.0';
export function setupEffects(){
 function refresh(){const daily=document.body.dataset.collection==='everyday';document.getElementById('spell-status').textContent=daily?'タップで色と形の演出が変わります。':'タップで毎回、違う魔法が広がります。';document.querySelectorAll('#magic-scene .ornament').forEach((n,i)=>{n.innerHTML=(daily?studioIcons:icons)[i];n.setAttribute('aria-label',(daily?['太陽','花','カメラ','鉛筆']:['おばけ','カボチャ','コウモリ','お菓子'])[i]+'の飾りで遊ぶ');});}
 refresh();
 const layer=document.createElement('div');layer.id='effect-layer';layer.setAttribute('aria-hidden','true');document.body.append(layer);
 const canvas=document.createElement('canvas');canvas.id='magic-sky';canvas.setAttribute('aria-hidden','true');document.body.prepend(canvas);const ctx=canvas.getContext('2d');
 const reduced=matchMedia('(prefers-reduced-motion: reduce)'),active=()=>document.body.dataset.motion==='on'&&!reduced.matches&&!document.hidden;
 const spells=createSpells({layer,active});
 let frame=0,last=0,w=0,h=0,pointerAt=0,score=0,time=0,timer=0;
 const motes=Array.from({length:18},(_,i)=>({x:Math.random(),y:Math.random(),r:2+i%4,v:.000012+(i%4)*.000006}));
 function resize(){w=innerWidth;h=innerHeight;const d=Math.min(devicePixelRatio||1,1.5);canvas.width=w*d;canvas.height=h*d;ctx?.setTransform(d,0,0,d,0,0);}resize();addEventListener('resize',resize,{passive:true});
 function paint(t){frame=0;if(!active()||!ctx)return;if(t-last>34){last=t;ctx.clearRect(0,0,w,h);motes.forEach((p,i)=>{p.y-=p.v*34;if(p.y<-.05)p.y=1.05;const x=p.x*w+Math.sin(t*.0004+i)*22,y=p.y*h;const daily=document.body.dataset.collection==='everyday';ctx.fillStyle=daily?(i%3?'#90c8d0':'#dfb6c8'):(i%3?'#ffe5a8':'#d69eff');ctx.globalAlpha=daily?.12+.15*(1+Math.sin(t*.001+i))/2:.25+.35*(1+Math.sin(t*.001+i))/2;ctx.beginPath();if(daily)ctx.arc(x,y,p.r,0,Math.PI*2);else{ctx.moveTo(x-p.r*2,y);ctx.quadraticCurveTo(x,y,x,y-p.r*2);ctx.quadraticCurveTo(x,y,x+p.r*2,y);ctx.quadraticCurveTo(x,y,x,y+p.r*2);ctx.quadraticCurveTo(x,y,x-p.r*2,y);}ctx.fill();});ctx.globalAlpha=1;}frame=requestAnimationFrame(paint);}
 function sync(){spells.stop();cancelAnimationFrame(frame);frame=0;layer.replaceChildren();if(ctx)ctx.clearRect(0,0,w,h);if(active())frame=requestAnimationFrame(paint);else stopGame();}
 function burst(x,y,big=false){if(!active())return;const host=[...document.querySelectorAll('dialog[open]')].at(-1)||document.body;if(layer.parentElement!==host)host.append(layer);const count=big?22:10;for(let i=0;i<count;i++){const spark=document.createElement('i');spark.className=i%4===0?'fx-ring':'fx-spark';spark.style.left=x+'px';spark.style.top=y+'px';spark.style.setProperty('--spark-color',['#ffc642','#ffeac1','#a958f0','#ff7a19'][i%4]);layer.append(spark);const angle=Math.PI*2*i/count,radius=(big?180:75)+(i%3)*18;const a=spark.animate([{opacity:1,transform:'translate(-50%,-50%) scale(.5)'},{opacity:0,transform:'translate(calc(-50% + '+Math.cos(angle)*radius+'px),calc(-50% + '+Math.sin(angle)*radius+'px)) rotate('+i*30+'deg) scale(1.8)'}],{duration:big?1100:650,easing:'cubic-bezier(.18,.68,.2,1)'});a.finished.catch(()=>{}).finally(()=>spark.remove());}while(layer.children.length>66)layer.firstElementChild.remove();}
 document.addEventListener('click',e=>{const button=e.target.closest('button');if(!button||button.disabled)return;const box=button.getBoundingClientRect();burst(e.clientX||box.left+box.width/2,e.clientY||box.top+box.height/2,button.id==='generate'||button.id==='propose');});
 document.addEventListener('pointermove',e=>{if(e.pointerType!=='mouse'||!active()||performance.now()-pointerAt<110||e.target.closest('input,textarea'))return;pointerAt=performance.now();const star=document.createElement('i');star.className='fx-spark';star.style.left=e.clientX+'px';star.style.top=e.clientY+'px';const host=[...document.querySelectorAll('dialog[open]')].at(-1)||document.body;if(layer.parentElement!==host)host.append(layer);layer.append(star);star.animate([{opacity:.9,transform:'scale(1.4)'},{opacity:0,transform:'translateY(-28px) scale(.1)'}],{duration:600}).finished.catch(()=>{}).finally(()=>star.remove());},{passive:true});
 const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(!entry.isIntersecting)return;entry.target.classList.add('entered');observer.unobserve(entry.target);}),{threshold:.12});document.querySelectorAll('.desk,.stage,.mode-panel,.history-section,.direction-card,.playground').forEach(e=>observer.observe(e));
 const game=document.getElementById('ghost-game'),arena=document.getElementById('ghost-arena'),status=document.getElementById('ghost-status');
 function stopGame(){clearInterval(timer);timer=0;arena?.replaceChildren();}
 function moveGhost(b){b.style.left=(8+Math.random()*72)+'%';b.style.top=(8+Math.random()*60)+'%';b.style.setProperty('--float-delay',(-Math.random()*3)+'s');}
 function startGame(){stopGame();const daily=document.body.dataset.collection==='everyday',item=daily?'モチーフ':'お菓子';if(!active()){status.textContent='演出をONにすると遊べます。';return;}score=0;time=20;status.textContent='残り20秒 ／ '+item+'0個';for(let i=0;i<4;i++){const b=document.createElement('button');b.className='ghost-target';b.innerHTML=(document.body.dataset.collection==='everyday'?studioIcons:icons)[i];b.setAttribute('aria-label',(document.body.dataset.collection==='everyday'?['太陽をあつめる','花をあつめる','カメラをあつめる','鉛筆をあつめる']:['おばけをつかまえる','カボチャをつかまえる','お菓子をつかまえる','コウモリをつかまえる'])[i]);moveGhost(b);b.onclick=()=>{score++;status.textContent='残り'+time+'秒 ／ '+item+score+'個';moveGhost(b);};arena.append(b);}timer=setInterval(()=>{time--;status.textContent='残り'+time+'秒 ／ '+item+score+'個';if(time<=0){stopGame();status.textContent=item+score+'個！もう一度、遊んでみる？';burst(innerWidth/2,innerHeight*.4,true);}},1000);}
 document.getElementById('play-ghosts')?.addEventListener('click',()=>{game.showModal();startGame();});document.getElementById('ghost-restart')?.addEventListener('click',startGame);game?.addEventListener('close',stopGame);
 document.getElementById('play-spell')?.addEventListener('click',()=>spells.cast());document.querySelectorAll('#magic-scene .ornament').forEach((b,i)=>b.addEventListener('click',()=>spells.cast(i===0?6:i===1?4:i===2?3:2)));

 document.addEventListener('visibilitychange',sync);reduced.addEventListener('change',sync);sync();
 return {sync,refresh,celebrate(){burst(innerWidth/2,innerHeight*.35,true);}};
}
