import {recipeFor} from './recipes.js?v=13';
import {optionRecipe} from './option-recipes.js?v=13';
import {lookFor} from './looks.js?v=13';
export function pageSize(width,height=window.innerHeight){return width<620?4:width<1100?(height>=1300?9:6):(height>=1300?12:8);}
export function pageSlice(items,page,limit){const pages=Math.max(1,Math.ceil(items.length/limit));const safe=Math.min(Math.max(page,0),pages-1);return {page:safe,pages,items:items.slice(safe*limit,(safe+1)*limit)};}
export function createPicker({$,el,sampleNode,readSelection,choose,onCustom,tell}){
 let question=null,page=0,candidates=[],comparing=false,inspected=null,focused=null,view='ring';
 const selected=()=>readSelection()[question.key];
 function locateSelection(){const matches=records(),index=matches.findIndex(r=>r.value===selected());page=Math.floor(Math.max(0,index)/(view==='ring'?6:pageSize(window.innerWidth)));focused=index>=0?matches[index]:null;}
 function records(){const term=$('search').value.trim().toLowerCase(),group=$('picker-category').value;return question.groups.filter(g=>group==='すべて'||g.label===group).flatMap(g=>g.values.filter(v=>(v+' '+g.label).toLowerCase().includes(term)).map(value=>({value,group:g.label})));}
 function tagList(record){const tags=el('span','look-tags');lookFor(question.key,record.value,record.group).chips.forEach(t=>tags.append(el('span',null,t)));return tags;}
 function toggleCandidate(record){const i=candidates.findIndex(x=>x.value===record.value);if(i>=0)candidates.splice(i,1);else {if(candidates.length===4){tell('比較は４枚までです。一枚外してから追加できます。');return;}candidates.push(record);}if(!candidates.length)comparing=false;render();}
 function inspect(record){inspected=record;$('inspector-title').textContent=record.value;$('inspector-category').textContent=question.name+' / '+record.group;$('inspector-art').replaceChildren(sampleNode(question.key,record.value));$('inspector-traits').replaceChildren(tagList(record));$('inspector-note').textContent='この選択で描く内容：'+recipeFor(question.key,record.value,{values:readSelection()}).text;const recipe=optionRecipe(question.key,record.value,{values:readSelection()});$('inspector-specs').open=false;const body=$('inspector-specs-body');body.replaceChildren();for(const section of recipe.sections){const p=el('p');p.append(el('b',null,section.label+'：'),document.createTextNode(section.text));body.append(p);}$('sample-zoom').value='1';$('inspector').showModal();zoom();}
 function zoom(){const factor=Number($('sample-zoom').value),box=$('inspector-art'),viewport=box.parentElement,art=box.firstElementChild;if(art){const base=Math.min(viewport.clientWidth,viewport.clientHeight),size=base*factor;box.style.width=Math.max(viewport.clientWidth,size)+'px';box.style.height=Math.max(viewport.clientHeight,size)+'px';art.style.width=size+'px';art.style.height=size+'px';art.style.maxWidth='none';art.style.marginLeft=Math.max(0,(viewport.clientWidth-size)/2)+'px';art.style.marginTop=Math.max(0,(viewport.clientHeight-size)/2)+'px';art.style.setProperty('--sample-scale',String(factor));viewport.scrollTop=0;viewport.scrollLeft=0;} $('zoom-value').textContent=factor.toFixed(1)+'倍';}
 function card(record){const c=el('article','sample-card'+(selected()===record.value?' selected':''));c.dataset.value=record.value;const pick=el('button','option-button');pick.type='button';pick.dataset.value=record.value;pick.setAttribute('aria-pressed',String(selected()===record.value));pick.setAttribute('aria-label',record.value+'を選ぶ');pick.append(sampleNode(question.key,record.value),el('b',null,record.value.split('｜')[0]));pick.addEventListener('click',()=>choose(record.value));c.append(pick,tagList(record));const tools=el('div','sample-tools');const big=el('button',null,'拡大');big.type='button';big.setAttribute('aria-label',record.value+'の見本を拡大');big.addEventListener('click',()=>inspect(record));const pin=el('button',null,candidates.some(x=>x.value===record.value)?'比較から外す':'比較に追加');pin.type='button';pin.setAttribute('aria-pressed',String(candidates.some(x=>x.value===record.value)));pin.addEventListener('click',()=>toggleCandidate(record));tools.append(big,pin);c.append(tools);return c;}
 function render(){if(!question)return;const matches=records(),slice=pageSlice(matches,page,(view==='ring'?6:pageSize(window.innerWidth)));page=slice.page;const grid=$('picker-options');grid.replaceChildren();grid.classList.toggle('comparing',comparing);grid.dataset.count=String(comparing?candidates.length:slice.items.length);if(comparing||view==='list')(comparing?candidates:slice.items).forEach(r=>grid.append(card(r)));if((comparing||view==='list')&&!grid.children.length)grid.append(el('p','empty-options','見つかりません。分類や検索語を変えてみてください。'));$('picker-prev').disabled=page===0;$('picker-next').disabled=page===slice.pages-1;$('picker-page').textContent=(page+1)+' / '+slice.pages+' ページ';$('picker-count').textContent=comparing?candidates.length+'枚を比較中':matches.length+'種類 / この画面に'+slice.items.length+'枚';$('picker-pagination').hidden=comparing;$('picker-filters').hidden=comparing;$('picker-auto').hidden=comparing;$('picker-compare').disabled=candidates.length<2&&!comparing;$('picker-compare').textContent=comparing?'一覧に戻る':'比較する（'+candidates.length+'/4）';$('compare-hint').textContent=comparing?'見本は人物ではなく、選んだ項目の特徴を比較してください。':'「比較に追加」で、別ページの見本も一緒に並べられます。';const tray=$('compare-tray');tray.replaceChildren();candidates.forEach(r=>{const b=el('button','candidate-chip',r.value.split('｜')[0]+' ×');b.type='button';b.setAttribute('aria-label',r.value+'を比較から外す');b.addEventListener('click',()=>toggleCandidate(r));tray.append(b);});$('compare-tray').hidden=!candidates.length;$('picker').classList.toggle('has-candidates',!!candidates.length);grid.scrollTop=0;$('picker-reset').disabled=!candidates.length;$('picker-ring-view').setAttribute('aria-pressed',String(view==='ring'));$('picker-list-view').setAttribute('aria-pressed',String(view==='list'));$('ring-stage').hidden=comparing||view!=='ring';grid.hidden=!comparing&&view==='ring';if(!comparing&&view==='ring')renderRing(slice.items);}
 function focusRecord(record){focused=record;const center=$('ring-focus');center.replaceChildren(sampleNode(question.key,record.value),el('b',null,record.value.split('｜')[0]));const pick=el('button','ring-pick','これを選ぶ');pick.type='button';pick.addEventListener('click',()=>choose(record.value));const tools=el('div','ring-tools'),big=el('button',null,'拡大'),pin=el('button',null,candidates.some(x=>x.value===record.value)?'比較から外す':'比較へ');big.type=pin.type='button';big.addEventListener('click',()=>inspect(record));pin.addEventListener('click',()=>toggleCandidate(record));tools.append(big,pin);center.append(pick,tools);$('ring-options').querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.value===record.value)));}
 function renderRing(items){const grid=$('ring-options');grid.replaceChildren();const points=[[-25,-36],[25,-36],[-37,0],[37,0],[-25,36],[25,36]];items.forEach((record,i)=>{const b=el('button','ring-pop');b.type='button';b.dataset.value=record.value;b.setAttribute('aria-label',record.value+'の見本を中央に表示');b.style.setProperty('--rx',points[i][0]+'%');b.style.setProperty('--ry',points[i][1]+'%');b.style.setProperty('--delay',i*35+'ms');b.append(sampleNode(question.key,record.value),el('b',null,record.value.split('｜')[0]));b.addEventListener('click',()=>focusRecord(record));grid.append(b);});const record=items.find(r=>r.value===focused?.value)||items.find(r=>r.value===selected())||items[0];if(record)focusRecord(record);else $('ring-focus').replaceChildren(el('p',null,'見つかりませんでした。'));}
 function open(q){question=q;page=0;focused=null;candidates=[];comparing=false;$('search').value='';$('picker-category').replaceChildren();['すべて',...q.groups.map(g=>g.label)].forEach(label=>{const o=el('option',null,label);o.value=label;$('picker-category').append(o);});$('picker-title').textContent=q.name;$('search').placeholder='選択肢を検索';$('custom-area').replaceChildren();const b=el('button','custom-toggle',q.key==='size'?'自由な幅・高さ':'一覧にない希望');b.type='button';b.addEventListener('click',()=>{b.hidden=true;onCustom(q);});$('custom-area').append(b);$('picker-auto').textContent=q.key==='mood'?'✦ 表情・角度を毎回変える':'✦ この項目をおまかせ';locateSelection();render();$('picker').showModal();$('picker').scrollTop=0;if(view==='list')requestAnimationFrame(()=>$('picker-options').querySelector('.selected')?.scrollIntoView({block:'nearest',behavior:'instant'}));}
 $('picker-reset').addEventListener('click',()=>{candidates=[];comparing=false;render();tell('比較をリセットしました。');});$('picker-ring-view').addEventListener('click',()=>{view='ring';comparing=false;locateSelection();render();});$('picker-list-view').addEventListener('click',()=>{view='list';comparing=false;locateSelection();render();});
 $('search').addEventListener('input',()=>{page=0;render();});$('picker-category').addEventListener('change',()=>{page=0;render();});$('picker-prev').addEventListener('click',()=>{page--;render();});$('picker-next').addEventListener('click',()=>{page++;render();});$('picker-compare').addEventListener('click',()=>{comparing=!comparing;render();});$('picker-auto').addEventListener('click',()=>choose(question.key==='mood'?'毎回大胆に変える':'おまかせ'));$('sample-zoom').addEventListener('input',zoom);$('inspector-pick').addEventListener('click',()=>{const value=inspected.value;$('inspector').close();choose(value);});$('inspector-pin').addEventListener('click',()=>{toggleCandidate(inspected);$('inspector').close();});let lastLimit=pageSize(window.innerWidth);window.addEventListener('resize',()=>{if($('inspector').open)zoom();const limit=pageSize(window.innerWidth);if(limit!==lastLimit){lastLimit=limit;if($('picker').open){locateSelection();render();}}});
 let swipe=null,suppressClickUntil=0;const surface=$('picker').querySelector('.picker-body');
 function movePage(delta){if(comparing||!question)return;const matches=records(),limit=view==='ring'?6:pageSize(innerWidth),pages=Math.ceil(matches.length/limit),next=Math.max(0,Math.min(pages-1,page+delta));if(next===page)return;page=next;focused=null;render();const panel=view==='ring'?$('ring-stage'):$('picker-options');if(document.body.dataset.motion==='on'&&!matchMedia('(prefers-reduced-motion: reduce)').matches){panel.style.setProperty('--slide-x',delta>0?'28px':'-28px');panel.classList.remove('picker-slide');void panel.offsetWidth;panel.classList.add('picker-slide');}}
 surface.addEventListener('pointerdown',e=>{if(e.target.closest('input,textarea,select')||!e.isPrimary)return;swipe={id:e.pointerId,x:e.clientX,y:e.clientY};});
 surface.addEventListener('dragstart',e=>e.preventDefault());
 surface.addEventListener('pointermove',e=>{if(!swipe||e.pointerId!==swipe.id)return;const dx=e.clientX-swipe.x,dy=e.clientY-swipe.y;if(Math.abs(dx)>12&&Math.abs(dx)>Math.abs(dy)*1.5){e.preventDefault();if(!surface.hasPointerCapture(e.pointerId))surface.setPointerCapture(e.pointerId);}});
 surface.addEventListener('pointerup',e=>{if(!swipe||e.pointerId!==swipe.id)return;const dx=e.clientX-swipe.x,dy=e.clientY-swipe.y;swipe=null;if(Math.abs(dx)>55&&Math.abs(dx)>Math.abs(dy)*1.5){suppressClickUntil=performance.now()+400;movePage(dx<0?1:-1);}});
 surface.addEventListener('pointercancel',()=>swipe=null);surface.addEventListener('click',e=>{if(performance.now()<suppressClickUntil){e.preventDefault();e.stopImmediatePropagation();}},{capture:true});
 $('picker').addEventListener('keydown',e=>{if(e.target.closest('input,textarea,select')||!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();movePage(e.key==='ArrowRight'?1:-1);});
 return {open};
}
