import {FAVORITE_LIMIT,FAVORITE_STORAGE,favoriteKey,normalizeFavorites,toggleFavorite} from './favorites.js?v=22.0.0';
import {ringWindow,ringPosition,swipeStep} from './ring-motion.js?v=22.0.0';
import {candidateAvailability,wrappedPage} from './compatibility.js?v=22.0.0';
import {appendRecipeEvidence} from './recipe-evidence.js?v=22.0.0';
import {recipeFor} from './recipes.js?v=22.0.0';
import {optionRecipe} from './option-recipes.js?v=22.0.0';
import {lookFor} from './looks.js?v=22.0.0';
export function pageSize(width,height=window.innerHeight){return width<620?4:width<1100?(height>=1300?9:6):(height>=1300?12:8);}
export function pageSlice(items,page,limit){const pages=Math.max(1,Math.ceil(items.length/limit));const safe=Math.min(Math.max(page,0),pages-1);return {page:safe,pages,items:items.slice(safe*limit,(safe+1)*limit)};}
export function createPicker({$,el,sampleNode,readSelection,choose,onCustom,tell}){
 let question=null,page=0,candidates=[],comparing=false,inspected=null,focused=null,view='ring',rotating=false,rotationToken=0;
 let favorites={};try{favorites=normalizeFavorites(JSON.parse(localStorage.getItem(FAVORITE_STORAGE)||'{}'));}catch{}
 const selected=()=>readSelection()[question.key];
 function locateSelection(){const matches=records(),index=matches.findIndex(r=>r.value===selected());page=view==='ring'?Math.max(0,index):Math.floor(Math.max(0,index)/pageSize(window.innerWidth));focused=index>=0?matches[index]:null;}
 function records(){const term=$('search').value.trim().toLowerCase(),group=$('picker-category').value;return question.groups.filter(g=>group==='すべて'||g.label===group).flatMap(g=>g.values.filter(v=>(v+' '+g.label).toLowerCase().includes(term)).map(value=>({value,group:g.label})));}
 function favoriteValues(){return favorites[favoriteKey(document.body.dataset.collection||'halloween',question.key)]||[];}
 function favoriteButton(record,short=false){const b=el('button','favorite-toggle',favoriteValues().includes(record.value)?'★'+(short?'':' 保存済み'):'☆'+(short?'':' お気に入り'));b.type='button';b.setAttribute('aria-pressed',String(favoriteValues().includes(record.value)));b.setAttribute('aria-label',record.value+(favoriteValues().includes(record.value)?'をお気に入りから外す':'をお気に入りに追加'));b.addEventListener('click',()=>changeFavorite(record));return b;}
 function changeFavorite(record){const key=favoriteKey(document.body.dataset.collection||'halloween',question.key),result=toggleFavorite(favoriteValues(),record.value);if(!result.changed){tell('お気に入りはこの項目で5件までです。一つ外してから追加できます。');return;}favorites[key]=result.values;try{localStorage.setItem(FAVORITE_STORAGE,JSON.stringify(favorites));}catch{tell('この端末にお気に入りを保存できませんでした。');}render();if($('inspector').open)syncInspectorFavorite();}
 function syncInspectorFavorite(){const added=favoriteValues().includes(inspected.value);$('inspector-favorite').textContent=added?'★ お気に入りから外す':'☆ お気に入りに追加';$('inspector-favorite').setAttribute('aria-pressed',String(added));}
 function renderFavorites(){const values=favoriteValues(),box=$('favorites-options');$('favorites-title').textContent='★ お気に入り '+values.length+'/'+FAVORITE_LIMIT;box.replaceChildren();if(!values.length){box.append(el('small','favorite-empty','☆で追加すると、ここからすぐ選べます。'));return;}for(const value of values){const chip=el('div','favorite-chip'),pick=el('button','favorite-pick'),availability=candidateAvailability(question.key,value,readSelection());pick.type='button';pick.disabled=!availability.enabled;pick.title=availability.reason;pick.setAttribute('aria-label','お気に入りの'+value+'を選ぶ');pick.append(sampleNode(question.key,value),el('span',null,value.split('｜')[0]));pick.addEventListener('click',()=>choose(value));const remove=el('button','favorite-remove','×');remove.type='button';remove.setAttribute('aria-label',value+'をお気に入りから外す');remove.addEventListener('click',()=>changeFavorite({value}));chip.append(pick,remove);box.append(chip);}}
 function tagList(record){const tags=el('span','look-tags');lookFor(question.key,record.value,record.group).chips.forEach(t=>tags.append(el('span',null,t)));return tags;}
 function toggleCandidate(record){const i=candidates.findIndex(x=>x.value===record.value);if(i>=0)candidates.splice(i,1);else {if(candidates.length===4){tell('比較は４枚までです。一枚外してから追加できます。');return;}candidates.push(record);}if(!candidates.length)comparing=false;render();}
 function inspect(record){inspected=record;$('inspector-title').textContent=record.value;$('inspector-category').textContent=question.name+' / '+record.group;$('inspector-art').replaceChildren(sampleNode(question.key,record.value));$('inspector-traits').replaceChildren(tagList(record));$('inspector-note').textContent='この選択で描く内容：'+recipeFor(question.key,record.value,{values:readSelection()}).text;const recipe=optionRecipe(question.key,record.value,{values:readSelection()});$('inspector-specs').open=false;const body=$('inspector-specs-body');body.replaceChildren();for(const section of recipe.sections){const p=el('p');p.append(el('b',null,section.label+'：'),document.createTextNode(section.text));body.append(p);}appendRecipeEvidence(body,question.key,record.value,{known:recipe.known});$('sample-zoom').value='1';const availability=candidateAvailability(question.key,record.value,readSelection());$('inspector-pick').disabled=!availability.enabled;$('inspector-pick').title=availability.reason;if(!availability.enabled)body.append(el('p','compatibility-reason',availability.reason));syncInspectorFavorite();$('inspector').showModal();zoom();}
 function zoom(){const factor=Number($('sample-zoom').value),box=$('inspector-art'),viewport=box.parentElement,art=box.firstElementChild;if(art){const base=Math.min(viewport.clientWidth,viewport.clientHeight),size=base*factor;box.style.width=Math.max(viewport.clientWidth,size)+'px';box.style.height=Math.max(viewport.clientHeight,size)+'px';art.style.width=size+'px';art.style.height=size+'px';art.style.maxWidth='none';art.style.marginLeft=Math.max(0,(viewport.clientWidth-size)/2)+'px';art.style.marginTop=Math.max(0,(viewport.clientHeight-size)/2)+'px';art.style.setProperty('--sample-scale',String(factor));viewport.scrollTop=0;viewport.scrollLeft=0;} $('zoom-value').textContent=factor.toFixed(1)+'倍';}
 function card(record){const availability=candidateAvailability(question.key,record.value,readSelection());const c=el('article','sample-card'+(selected()===record.value?' selected':''));c.dataset.value=record.value;const pick=el('button','option-button');pick.type='button';pick.dataset.value=record.value;pick.setAttribute('aria-pressed',String(selected()===record.value));pick.setAttribute('aria-label',record.value+'を選ぶ');pick.disabled=!availability.enabled;pick.title=availability.reason;pick.append(sampleNode(question.key,record.value),el('b',null,record.value.split('｜')[0]));pick.addEventListener('click',()=>choose(record.value));c.append(pick,tagList(record));if(!availability.enabled){c.classList.add('incompatible');c.append(el('p','compatibility-reason',availability.reason));}const tools=el('div','sample-tools');const big=el('button',null,'拡大');big.type='button';big.setAttribute('aria-label',record.value+'の見本を拡大');big.addEventListener('click',()=>inspect(record));const pin=el('button',null,candidates.some(x=>x.value===record.value)?'比較から外す':'比較に追加');pin.type='button';pin.setAttribute('aria-pressed',String(candidates.some(x=>x.value===record.value)));pin.addEventListener('click',()=>toggleCandidate(record));tools.append(big,pin,favoriteButton(record,true));c.append(tools);return c;}
 function render(){if(!question)return;rotationToken++;rotating=false;const matches=records(),slice=view==='ring'?{...ringWindow(matches,page),page:ringWindow(matches,page).index,pages:Math.max(1,matches.length)}:pageSlice(matches,page,pageSize(window.innerWidth));page=slice.page;renderFavorites();const grid=$('picker-options');grid.replaceChildren();grid.classList.toggle('comparing',comparing);grid.dataset.count=String(comparing?candidates.length:slice.items.length);if(comparing||view==='list')(comparing?candidates:slice.items).forEach(r=>grid.append(card(r)));if((comparing||view==='list')&&!grid.children.length)grid.append(el('p','empty-options','見つかりません。分類や検索語を変えてみてください。'));$('picker-prev').disabled=$('picker-next').disabled=slice.pages<=1;$('picker-page').textContent=(page+1)+' / '+slice.pages+(view==='ring'?' 回転位置':' ページ');$('picker-prev').textContent=view==='ring'?'前へ回す':'前のページ';$('picker-next').textContent=view==='ring'?'次へ回す':'次のページ';$('swipe-hint').textContent=view==='ring'?'左で次・右で前へ。リングを回して選べます。':'左で次のページ・右で前のページへ';$('picker-count').textContent=comparing?candidates.length+'枚を比較中':matches.length+'種類 / この画面に'+slice.items.length+'枚';$('picker-pagination').hidden=comparing;$('picker-filters').hidden=comparing;$('picker-auto').hidden=comparing;$('picker-compare').disabled=candidates.length<2&&!comparing;$('picker-compare').textContent=comparing?'一覧に戻る':'比較する（'+candidates.length+'/4）';$('compare-hint').textContent=comparing?'見本は人物ではなく、選んだ項目の特徴を比較してください。':'「比較に追加」で、別ページの見本も一緒に並べられます。';const tray=$('compare-tray');tray.replaceChildren();candidates.forEach(r=>{const b=el('button','candidate-chip',r.value.split('｜')[0]+' ×');b.type='button';b.setAttribute('aria-label',r.value+'を比較から外す');b.addEventListener('click',()=>toggleCandidate(r));tray.append(b);});$('compare-tray').hidden=!candidates.length;$('picker').classList.toggle('has-candidates',!!candidates.length);grid.scrollTop=0;$('picker-reset').disabled=!candidates.length;$('picker-ring-view').setAttribute('aria-pressed',String(view==='ring'));$('picker-list-view').setAttribute('aria-pressed',String(view==='list'));$('ring-stage').hidden=comparing||view!=='ring';grid.hidden=!comparing&&view==='ring';if(!comparing&&view==='ring')renderRing(slice.items);}
 function focusRecord(record){focused=record;const availability=candidateAvailability(question.key,record.value,readSelection());const center=$('ring-focus');center.replaceChildren(sampleNode(question.key,record.value),el('b',null,record.value.split('｜')[0]));const pick=el('button','ring-pick','これを選ぶ');pick.type='button';pick.disabled=!availability.enabled;pick.title=availability.reason;pick.addEventListener('click',()=>choose(record.value));if(!availability.enabled)center.append(el('p','compatibility-reason',availability.reason));const tools=el('div','ring-tools'),big=el('button',null,'拡大'),pin=el('button',null,candidates.some(x=>x.value===record.value)?'比較から外す':'比較へ');big.type=pin.type='button';big.addEventListener('click',()=>inspect(record));pin.addEventListener('click',()=>toggleCandidate(record));tools.append(big,pin,favoriteButton(record,true));center.append(pick,tools);$('ring-options').querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.value===record.value)));}
 function positionRing(rotation=0){const nodes=[...$('ring-options').children];nodes.forEach((b,i)=>{const p=ringPosition(i,nodes.length,rotation);b.style.setProperty('--rx',p.x+'%');b.style.setProperty('--ry',p.y+'%');b.style.setProperty('--orbit-scale',p.scale);b.style.zIndex=String(p.z);});}
 function renderRing(items){const grid=$('ring-options');grid.replaceChildren();items.forEach((record,i)=>{const b=el('button','ring-pop');b.type='button';b.dataset.value=record.value;b.setAttribute('aria-label',record.value+'の見本を中央に表示');b.append(sampleNode(question.key,record.value),el('b',null,record.value.split('｜')[0]));b.addEventListener('click',()=>{const matches=records(),index=matches.findIndex(r=>r.value===record.value);movePage(index-page);});grid.append(b);});positionRing();const record=items[0];if(record)focusRecord(record);else $('ring-focus').replaceChildren(el('p',null,'見つかりませんでした。'));}
 function open(q){question=q;page=0;focused=null;candidates=[];comparing=false;$('search').value='';$('picker-category').replaceChildren();['すべて',...q.groups.map(g=>g.label)].forEach(label=>{const o=el('option',null,label);o.value=label;$('picker-category').append(o);});$('picker-title').textContent=q.name;$('search').placeholder='選択肢を検索';$('custom-area').replaceChildren();const b=el('button','custom-toggle',q.key==='size'?'自由な幅・高さ':'一覧にない希望');b.type='button';b.addEventListener('click',()=>{b.hidden=true;onCustom(q);});$('custom-area').append(b);$('picker-auto').textContent=q.key==='mood'?'✦ 表情・角度を毎回変える':'✦ この項目をおまかせ';locateSelection();render();$('picker').showModal();$('picker').scrollTop=0;if(view==='list')requestAnimationFrame(()=>$('picker-options').querySelector('.selected')?.scrollIntoView({block:'nearest',behavior:'instant'}));}
 $('picker-reset').addEventListener('click',()=>{candidates=[];comparing=false;render();tell('比較をリセットしました。');});$('picker-ring-view').addEventListener('click',()=>{view='ring';comparing=false;locateSelection();render();});$('picker-list-view').addEventListener('click',()=>{view='list';comparing=false;locateSelection();render();});
 $('search').addEventListener('input',()=>{page=0;render();});$('picker-category').addEventListener('change',()=>{page=0;render();});$('picker-prev').addEventListener('click',()=>movePage(-1));$('picker-next').addEventListener('click',()=>movePage(1));$('picker-compare').addEventListener('click',()=>{comparing=!comparing;render();});$('picker-auto').addEventListener('click',()=>choose(question.key==='mood'?'毎回大胆に変える':'おまかせ'));$('sample-zoom').addEventListener('input',zoom);$('inspector-pick').addEventListener('click',()=>{const value=inspected.value;$('inspector').close();choose(value);});$('inspector-favorite').addEventListener('click',()=>changeFavorite(inspected));$('inspector-pin').addEventListener('click',()=>{toggleCandidate(inspected);$('inspector').close();});let lastLimit=pageSize(window.innerWidth);window.addEventListener('resize',()=>{if($('inspector').open)zoom();const limit=pageSize(window.innerWidth);if(limit!==lastLimit){lastLimit=limit;if($('picker').open){locateSelection();render();}}});
 let swipe=null,suppressClickUntil=0;const surface=$('picker').querySelector('.picker-body');
 function movePage(delta){if(comparing||!question||rotating||!delta)return;const matches=records(),pages=view==='ring'?matches.length:Math.ceil(matches.length/pageSize(innerWidth)),next=wrappedPage(page,delta,pages);if(next===page)return;
 if(view==='ring'&&document.body.dataset.motion==='on'&&!matchMedia('(prefers-reduced-motion: reduce)').matches){rotating=true;const token=++rotationToken,started=performance.now(),total=delta*360/Math.max(1,$('ring-options').children.length),q=question;function tick(now){if(token!==rotationToken)return;const progress=Math.min(1,(now-started)/240),ease=1-Math.pow(1-progress,3);positionRing(total*ease);if(progress<1&&question===q&&$('picker').open)requestAnimationFrame(tick);else{rotating=false;if(question===q&&$('picker').open){page=next;focused=null;render();}}}requestAnimationFrame(tick);}
 else{page=next;focused=null;render();if(view==='list'&&document.body.dataset.motion==='on'&&!matchMedia('(prefers-reduced-motion: reduce)').matches){const panel=$('picker-options');panel.style.setProperty('--slide-x',delta>0?'28px':'-28px');panel.classList.remove('picker-slide');void panel.offsetWidth;panel.classList.add('picker-slide');}}
 }
 surface.addEventListener('pointerdown',e=>{if(e.target.closest('input,textarea,select,#favorites-options,.compare-tray')||!e.isPrimary)return;swipe={id:e.pointerId,x:e.clientX,y:e.clientY};});
 surface.addEventListener('dragstart',e=>e.preventDefault());
 surface.addEventListener('pointermove',e=>{if(!swipe||e.pointerId!==swipe.id)return;const dx=e.clientX-swipe.x,dy=e.clientY-swipe.y;if(Math.abs(dx)>12&&Math.abs(dx)>Math.abs(dy)*1.5){e.preventDefault();if(!surface.hasPointerCapture(e.pointerId))surface.setPointerCapture(e.pointerId);}});
 surface.addEventListener('pointerup',e=>{if(!swipe||e.pointerId!==swipe.id)return;const dx=e.clientX-swipe.x,dy=e.clientY-swipe.y;swipe=null;if(Math.abs(dx)>55&&Math.abs(dx)>Math.abs(dy)*1.5){suppressClickUntil=performance.now()+400;movePage(swipeStep(dx,dy));}});
 surface.addEventListener('pointercancel',()=>swipe=null);surface.addEventListener('click',e=>{if(performance.now()<suppressClickUntil){e.preventDefault();e.stopImmediatePropagation();}},{capture:true});
 $('picker').addEventListener('keydown',e=>{if(e.target.closest('input,textarea,select')||!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();movePage(e.key==='ArrowRight'?1:-1);});
 window.addEventListener('storage',e=>{if(e.key!==FAVORITE_STORAGE)return;try{favorites=normalizeFavorites(JSON.parse(e.newValue||'{}'));if($('picker').open)render();}catch{}});
 return {open};
}
