(() => {
'use strict';
const SUPA='https://xxhaerjvrgmnadxjqetz.supabase.co';
const KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4aGFlcmp2cmdtbmFkeGpxZXR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODYwNTMxMTQsImV4cCI6MjEwMTYyOTExNH0.DtoUvuMTrW7rA3jLThLD4zijvluuTB_LmEBIjWJs-jA';
const STORE='mumei-v3-state',SESSION='mumei-v3-session',OWNER='mumei-v3-owner-token',BACK='mumei-v3-backend-session';
const series=()=>window.MUMEI_SERIES?.key||'adventure';
const headers={'apikey':KEY,'Authorization':`Bearer ${KEY}`,'Content-Type':'application/json'};
const uploads=new Map();
const imgUrl=p=>p?`${SUPA}/storage/v1/object/public/creator-images/${p}`:'';
const readState=()=>{try{return JSON.parse(localStorage.getItem(STORE)||'{}')}catch{return {}}};
const writeState=s=>localStorage.setItem(STORE,JSON.stringify(s));
const readBack=()=>{try{return JSON.parse(localStorage.getItem(`${BACK}-${series()}`)||'null')}catch{return null}};
const writeBack=v=>localStorage.setItem(`${BACK}-${series()}`,JSON.stringify(v));
const ownerToken=()=>localStorage.getItem(OWNER)||'';
const notify=m=>{const t=document.querySelector('#toast');if(t){t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}else alert(m)};
async function rpc(name,body={}){const r=await fetch(`${SUPA}/rest/v1/rpc/${name}`,{method:'POST',headers,body:JSON.stringify(body)});const text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch{data=text}if(!r.ok)throw new Error(data?.message||data?.hint||data?.error||text||`HTTP ${r.status}`);return data}
function settings(s){return{title:s.title,hashtag:s.hashtag,started:s.started_label,announcement:s.announcement||'',rankDailyLimit:s.rank_daily_limit||10,winPercent:s.win_percent||45,drawPercent:s.draw_percent||10,profileUrl:s.profile_url||'',recruitUrl:s.recruit_url||'',magazineUrl:s.magazine_url||''}}
function creator(c){return{id:c.id,noteId:c.note_id,displayName:c.display_name||'',status:c.status||'approved',job:c.job||'',rarity:c.rarity||'Normal',dialoguePack:c.dialogue_pack||'gentle',images:(c.images||[]).map(imgUrl),intro:c.intro||'',article1Url:c.article1_url||'',article2Url:c.article2_url||'',participationArticleUrl:c.participation_article_url||'',articleStatus:c.article_status||'none',approvedAt:c.approved_at||null,createdAt:c.created_at||new Date().toISOString(),isDemo:false,backend:true}}
function opponents(list){return(list||[]).map((o,i)=>({id:`s${o.slot||i+1}`,backendId:o.id,name:o.name,job:o.job||'',rarity:o.rarity||'Normal',dialoguePack:o.dialogue_pack||'gentle',images:o.image_path?[imgUrl(o.image_path)]:[],version:o.version||1,enabled:o.enabled!==false}))}
function syntheticBattles(leaders,total,ops){const out=[],now=new Date();let n=0;for(const l of leaders||[]){for(const [res,count] of [['win',Number(l.wins||0)],['draw',Number(l.draws||0)],['lose',Number(l.losses||0)]])for(let i=0;i<count;i++){const d=new Date(now);d.setMinutes(d.getMinutes()-(n++));out.push({id:`remote-${l.id}-${res}-${i}`,participantId:l.id,opponentId:ops[n%Math.max(ops.length,1)]?.id||'s1',opponentVersion:1,action:['strike','guard','special'][n%3],result:res,ranked:true,createdAt:d.toISOString(),source:'remote'})}}while(out.length<Number(total||0))out.push({id:`guest-${out.length}`,participantId:null,guestId:'remote',opponentId:'s1',opponentVersion:1,action:'strike',result:'lose',ranked:false,createdAt:now.toISOString(),source:'remote'});return out}
function fromPublic(d){const ops=opponents(d.opponents);return{version:3,settings:settings(d.series),opponents:ops,participants:(d.creators||[]).map(creator),battles:syntheticBattles(d.leaderboard_week,d.battle_total,ops),audit:[]}}
function fromAdmin(d){const ops=opponents(d.opponents);const count=Number(d.metrics?.battles||0);return{version:3,settings:settings(d.series),opponents:ops,participants:(d.creators||[]).map(creator),battles:Array.from({length:count},(_,i)=>({id:`admin-b-${i}`,participantId:null,guestId:'remote',opponentId:'s1',opponentVersion:1,action:'strike',result:'lose',ranked:false,createdAt:new Date().toISOString()})),audit:(d.logs||[]).map(a=>({id:a.id,action:a.action,at:a.created_at}))}}
async function hydrate(){const d=await rpc('get_public_state',{p_series:series()});if(d?.unreleased&&series()==='sengoku'&&!location.hash.includes('admin')){location.replace(`${location.pathname}?series=adventure`);return}
let st=fromPublic(d);const back=readBack();if(back){try{const p=await rpc('get_creator_private',{p_id:back.id,p_edit_token:back.editToken});const cp=creator(p);const ix=st.participants.findIndex(x=>x.id===cp.id);if(ix>=0)st.participants[ix]=cp;else st.participants.push(cp);localStorage.setItem(SESSION,cp.id)}catch{localStorage.removeItem(`${BACK}-${series()}`);localStorage.removeItem(SESSION)}}
if(location.hash.replace('#','')==='admin'&&ownerToken()){try{st=fromAdmin(await rpc('admin_snapshot',{p_owner_token:ownerToken(),p_series:series()}))}catch{localStorage.removeItem(OWNER)}}
writeState(st);try{const sg=await rpc('get_public_state',{p_series:'sengoku'});localStorage.setItem('mumei-v3-series-release',JSON.stringify({sengokuPublic:!!sg?.series?.is_public}))}catch{}
}
async function fileData(file){const max=1800;const bmp=await createImageBitmap(file);const scale=Math.min(1,max/Math.max(bmp.width,bmp.height)),w=Math.max(1,Math.round(bmp.width*scale)),h=Math.max(1,Math.round(bmp.height*scale));const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(bmp,0,0,w,h);bmp.close();const blob=await new Promise(r=>c.toBlob(r,'image/webp',.9));return new Promise((res,rej)=>{const fr=new FileReader();fr.onload=()=>res(String(fr.result).split(',')[1]);fr.onerror=rej;fr.readAsDataURL(blob)})}
async function upload(mode,payload,file){const base64=await fileData(file);const r=await fetch(`${SUPA}/functions/v1/catalog-image-upload`,{method:'POST',headers:{'apikey':KEY,'Content-Type':'application/json'},body:JSON.stringify({...payload,mode,mime:'image/webp',base64})});const d=await r.json();if(!r.ok)throw new Error(d.error||'画像アップロードに失敗しました');return d}
async function uploadParticipant(back,key){const files=uploads.get(key)||[];for(let i=0;i<Math.min(3,files.length);i++)await upload('participant',{submission_id:back.id,edit_token:back.editToken,position:i},files[i])}
function normId(v){const s=String(v||'').trim(),m=s.match(/note\.com\/([\w-]+)/i);return(m?m[1]:s.replace(/^@/,'')).trim()}
async function refreshAdmin(){const d=await rpc('admin_snapshot',{p_owner_token:ownerToken(),p_series:series()});writeState(fromAdmin(d))}
async function adminLogin(){let tok=ownerToken();if(!tok)tok=prompt('オーナーキーを入力してください')||'';if(!tok)return false;await rpc('admin_snapshot',{p_owner_token:tok,p_series:series()});localStorage.setItem(OWNER,tok);return true}
function stop(e){e.preventDefault();e.stopImmediatePropagation()}

document.addEventListener('change',e=>{const el=e.target.closest?.('[data-upload]');if(!el)return;const id=el.dataset.upload,a=uploads.get(id)||[];uploads.set(id,a.concat([...el.files]).slice(0,3))},true);
document.addEventListener('click',e=>{const rm=e.target.closest?.('[data-remove]');if(rm){const a=uploads.get(rm.dataset.upid)||[];a.splice(Number(rm.dataset.remove),1);uploads.set(rm.dataset.upid,a)}const mv=e.target.closest?.('[data-move]');if(mv){const a=uploads.get(mv.dataset.upid)||[],i=Number(mv.dataset.index),j=mv.dataset.move==='up'?i-1:i+1;if(a[i]&&j>=0&&j<a.length){[a[i],a[j]]=[a[j],a[i]];uploads.set(mv.dataset.upid,a)}}},true);

document.addEventListener('click',async e=>{try{
 const nav=e.target.closest?.('[data-nav="admin"]');if(nav){stop(e);if(await adminLogin()){await refreshAdmin();location.hash='admin';location.reload()}return}
 const tog=e.target.closest?.('[data-toggle-sengoku]');if(tog){stop(e);if(!await adminLogin())return;const cur=JSON.parse(localStorage.getItem('mumei-v3-series-release')||'{"sengokuPublic":false}');const next=!cur.sengokuPublic;if(!confirm(next?'戦国カード名鑑を公開しますか？':'戦国カード名鑑を非公開にしますか？'))return;await rpc('admin_toggle_series',{p_owner_token:ownerToken(),p_series:'sengoku',p_public:next});localStorage.setItem('mumei-v3-series-release',JSON.stringify({sengokuPublic:next}));notify(next?'戦国版を公開しました':'戦国版を非公開にしました');setTimeout(()=>location.reload(),500);return}
 const act=e.target.closest?.('[data-approve],[data-revision],[data-unpublish],[data-verify],[data-reject]');if(act){stop(e);if(!await adminLogin())return;let id,status,fn;if(act.dataset.approve){id=act.dataset.approve;status='approved';fn='admin_set_creator_status'}else if(act.dataset.revision){id=act.dataset.revision;status='revision';fn='admin_set_creator_status'}else if(act.dataset.unpublish){id=act.dataset.unpublish;status='unpublished';fn='admin_set_creator_status'}else if(act.dataset.verify){id=act.dataset.verify;status='verified';fn='admin_verify_article'}else{id=act.dataset.reject;status='revision';fn='admin_verify_article'};const args=fn==='admin_verify_article'?{p_owner_token:ownerToken(),p_id:id,p_status:status}:{p_owner_token:ownerToken(),p_id:id,p_status:status};await rpc(fn,args);await refreshAdmin();location.reload();return}
 const play=e.target.closest?.('[data-play],[data-rematch]');if(play){stop(e);const st=readState(),checked=document.querySelector('input[name="opponent"]:checked'),oid=checked?.value||st.opponents?.[0]?.id,o=st.opponents.find(x=>x.id===oid),sel=document.querySelector('[data-action].selected'),action=sel?.dataset.action||'strike',back=readBack();if(!o?.backendId)throw new Error('対戦相手を選んでください');const r=await rpc('play_catalog_battle',{p_series:series(),p_opponent_id:o.backendId,p_action:action==='strike'?'attack':action,p_participant_id:back?.id||null,p_edit_token:back?.editToken||null});const mark=r.result==='win'?'🏆 勝利！':r.result==='draw'?'🤝 引き分け':'⚔️ 敗北';alert(`${mark}\n${r.ranked?`ランキング加算対象・今週 ${r.week_rank||'-'}位`:'練習対戦'}`);await hydrate();location.reload();return}
 const per=e.target.closest?.('[data-period]');if(per){stop(e);const rows=await rpc('get_leaderboard',{p_series:series(),p_period:per.dataset.period});document.querySelectorAll('[data-period]').forEach(x=>x.classList.toggle('active',x===per));const box=document.querySelector('#rankBox');if(box)box.innerHTML=`<div class="rank-list">${(rows||[]).map((x,i)=>`<div class="rank-row"><span class="place">${i+1}</span><div><b>${String(x.display_name||x.note_id).replace(/[&<>]/g,'')}</b><small>@${x.note_id}</small></div><div class="rank-score"><strong>${x.wins}</strong><small>勝 / ${x.battles}戦</small></div></div>`).join('')||'<div class="empty">まだランキング記録がありません。</div>'}</div>`;return}
 }catch(err){console.error(err);notify(err.message||'処理に失敗しました')}},true);

document.addEventListener('submit',async e=>{try{
 if(e.target.id==='joinForm'){stop(e);const f=new FormData(e.target),noteId=normId(f.get('noteId'));const r=await rpc('register_creator',{p_series:series(),p_note_id:noteId,p_display_name:String(f.get('displayName')||''),p_intro:String(f.get('intro')||''),p_article1_url:String(f.get('article1Url')||'')});const back={id:r.id,editToken:r.edit_token};writeBack(back);localStorage.setItem(SESSION,r.id);await uploadParticipant(back,'join');location.hash='mypage';await hydrate();location.reload();return}
 if(e.target.id==='myForm'){stop(e);const back=readBack();if(!back)throw new Error('参加情報が見つかりません');const f=new FormData(e.target);await rpc('update_creator',{p_id:back.id,p_edit_token:back.editToken,p_display_name:String(f.get('displayName')||''),p_intro:String(f.get('intro')||''),p_article1_url:String(f.get('article1Url')||''),p_article2_url:String(f.get('article2Url')||'')});const key=`my-${back.id}`;if((uploads.get(key)||[]).length)await uploadParticipant(back,key);await hydrate();location.reload();return}
 if(e.target.id==='articleForm'){stop(e);const back=readBack();if(!back)throw new Error('参加情報が見つかりません');const f=new FormData(e.target);await rpc('submit_participation_article',{p_id:back.id,p_edit_token:back.editToken,p_url:String(f.get('url')||'')});await hydrate();location.reload();return}
 if(e.target.id==='settingsForm'){stop(e);if(!await adminLogin())return;const f=new FormData(e.target);await rpc('admin_update_series',{p_owner_token:ownerToken(),p_series:series(),p_title:String(f.get('title')||''),p_hashtag:String(f.get('hashtag')||''),p_started_label:String(f.get('started')||''),p_announcement:String(f.get('announcement')||''),p_rank_daily_limit:Number(f.get('rankDailyLimit')),p_win_percent:Number(f.get('winPercent')),p_draw_percent:Number(f.get('drawPercent')),p_profile_url:String(f.get('profileUrl')||''),p_recruit_url:String(f.get('recruitUrl')||''),p_magazine_url:String(f.get('magazineUrl')||'')});await refreshAdmin();location.reload();return}
 if(e.target.id==='editPForm'){stop(e);if(!await adminLogin())return;const st=readState(),p=st.participants.find(x=>x.id===e.target.dataset.id),f=new FormData(e.target);await rpc('admin_update_creator',{p_owner_token:ownerToken(),p_id:p.id,p_display_name:String(f.get('displayName')||''),p_intro:String(f.get('intro')||''),p_job:String(f.get('job')||''),p_rarity:String(f.get('rarity')||'Normal'),p_dialogue_pack:String(f.get('dialoguePack')||'gentle'),p_article1_url:String(f.get('article1Url')||''),p_article2_url:String(f.get('article2Url')||'')});await refreshAdmin();location.reload();return}
 if(e.target.id==='editOForm'){stop(e);if(!await adminLogin())return;const st=readState(),o=st.opponents.find(x=>x.id===e.target.dataset.id),f=new FormData(e.target);await rpc('admin_update_opponent',{p_owner_token:ownerToken(),p_id:o.backendId,p_name:String(f.get('name')||''),p_job:String(f.get('job')||''),p_rarity:String(f.get('rarity')||'Normal'),p_dialogue_pack:String(f.get('dialoguePack')||'gentle'),p_enabled:f.get('enabled')==='on'});const fs=uploads.get(`eo-${o.id}`)||[];if(fs[0])await upload('owner',{opponent_id:o.backendId,owner_token:ownerToken()},fs[0]);await refreshAdmin();location.reload();return}
 }catch(err){console.error(err);notify(err.message||'保存に失敗しました')}},true);

window.MUMEI_BACKEND_READY=hydrate().catch(err=>{console.error('[backend]',err);notify('共有DBの読み込みに失敗しました。再読み込みしてください。')});
})();