(() => {
'use strict';
const API='https://xxhaerjvrgmnadxjqetz.supabase.co';
const KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4aGFlcmp2cmdtbmFkeGpxZXR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODYwNTMxMTQsImV4cCI6MjEwMTYyOTExNH0.DtoUvuMTrW7rA3jLThLD4zijvluuTB_LmEBIjWJs-jA';
const series=()=>window.MUMEI_SERIES?.key||'adventure';
const stateKey='mumei-v3-state', sessionKey='mumei-v3-session';
const credKey=s=>`mumei-live-creator-${s}`;
const OWNER='mumei-live-owner';
const headers={'apikey':KEY,'Authorization':`Bearer ${KEY}`,'Content-Type':'application/json'};
const rpc=async(name,body={})=>{const r=await fetch(`${API}/rest/v1/rpc/${name}`,{method:'POST',headers,body:JSON.stringify(body),cache:'no-store'});const text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch{data=text}if(!r.ok)throw Error(data?.message||data?.hint||String(data)||`${name}: ${r.status}`);return data};
const publicImage=path=>path?`${API}/storage/v1/object/public/creator-images/${path.split('/').map(encodeURIComponent).join('/')}`:'';
const imagePath=src=>{if(!src||src.startsWith('data:'))return null;try{const u=new URL(src),mark='/storage/v1/object/public/creator-images/',i=u.pathname.indexOf(mark);return i>=0?u.pathname.slice(i+mark.length).split('/').map(decodeURIComponent).join('/'):null}catch{return null}};
const creatorCred=()=>{try{return JSON.parse(localStorage.getItem(credKey(series()))||'null')}catch{return null}};
const ownerToken=()=>sessionStorage.getItem(OWNER)||'';
const setOwnerToken=t=>t?sessionStorage.setItem(OWNER,t):sessionStorage.removeItem(OWNER);
const mapCreator=c=>({id:c.id,noteId:c.note_id,displayName:c.display_name||'',status:c.status||'approved',job:c.job||'',rarity:c.rarity||'Normal',dialoguePack:c.dialogue_pack||'gentle',images:(c.images||[]).map(publicImage),intro:c.intro||'',article1Url:c.article1_url||'',article2Url:c.article2_url||'',participationArticleUrl:c.participation_article_url||'',articleStatus:c.article_status||'none',approvedAt:c.approved_at||null,createdAt:c.created_at||new Date().toISOString(),isDemo:false});
const mapOpponent=o=>({id:o.id,name:o.name,job:o.job||'',rarity:o.rarity||'Normal',dialoguePack:o.dialogue_pack||'gentle',images:o.image_path?[publicImage(o.image_path)]:[],version:o.version||1,enabled:o.enabled!==false,slot:o.slot});
const mapSettings=s=>({title:s.title,hashtag:s.hashtag,started:s.started_label,announcement:s.announcement||'',rankDailyLimit:s.rank_daily_limit||10,winPercent:s.win_percent||45,drawPercent:s.draw_percent||10,profileUrl:s.profile_url||'',recruitUrl:s.recruit_url||'',magazineUrl:s.magazine_url||''});
function synthBattles(creators,today,week,all,total){const byId=new Map(creators.map(c=>[c.id,c])),out=[];const maps={today:new Map((today||[]).map(x=>[x.id,x])),week:new Map((week||[]).map(x=>[x.id,x])),all:new Map((all||[]).map(x=>[x.id,x]))};const add=(id,count,wins,dateBase,tag)=>{for(let i=0;i<count;i++)out.push({id:`remote-${tag}-${id}-${i}`,participantId:id,opponentId:'remote',opponentVersion:1,action:'strike',result:i<wins?'win':'lose',ranked:true,createdAt:new Date(dateBase.getTime()+i*1000).toISOString(),source:'remote'})};for(const id of byId.keys()){const a=maps.all.get(id)||{battles:0,wins:0},w=maps.week.get(id)||{battles:0,wins:0},d=maps.today.get(id)||{battles:0,wins:0};const oldGames=Math.max(0,(+a.battles||0)-(+w.battles||0)),oldWins=Math.max(0,(+a.wins||0)-(+w.wins||0));const weekGames=Math.max(0,(+w.battles||0)-(+d.battles||0)),weekWins=Math.max(0,(+w.wins||0)-(+d.wins||0));add(id,oldGames,oldWins,new Date('2026-01-01T00:00:00Z'),'old');const wd=new Date();wd.setDate(wd.getDate()-2);add(id,weekGames,weekWins,wd,'week');const td=new Date();td.setHours(1,0,0,0);add(id,+d.battles||0,+d.wins||0,td,'today')}
while(out.length<(+total||0))out.push({id:`guest-${out.length}`,participantId:null,opponentId:'remote',opponentVersion:1,action:'strike',result:'draw',ranked:false,createdAt:new Date().toISOString(),source:'remote'});return out}
async function buildState(){const s=series();const [pub,adv,sen,today,week,all]=await Promise.all([rpc('get_public_state',{p_series:s}),rpc('get_public_state',{p_series:'adventure'}),rpc('get_public_state',{p_series:'sengoku'}),rpc('get_leaderboard',{p_series:s,p_period:'today'}),rpc('get_leaderboard',{p_series:s,p_period:'week'}),rpc('get_leaderboard',{p_series:s,p_period:'all'})]);window.MUMEI_SERIES_PUBLIC={adventure:!!adv?.series?.is_public,sengoku:!!sen?.series?.is_public};let source=pub,admin=false;if(location.hash.replace(/^#/,'')==='admin'&&ownerToken()){try{source=await rpc('admin_snapshot',{p_owner_token:ownerToken(),p_series:s});admin=true}catch{setOwnerToken('')}}
const ser=source.series||pub.series||{};let creators=(source.creators||pub.creators||[]).map(mapCreator);const cred=creatorCred();if(cred&&!creators.some(x=>x.id===cred.id)){try{const mine=await rpc('get_creator_private',{p_id:cred.id,p_edit_token:cred.token});creators.push(mapCreator(mine))}catch{}}
const opponents=(source.opponents||pub.opponents||[]).map(mapOpponent);const state={version:3,settings:mapSettings(ser),opponents,participants:creators,battles:synthBattles(creators,today,week,all,pub.battle_total||0),audit:(source.logs||[]).map(a=>({id:a.id,action:a.action,at:a.created_at}))};localStorage.setItem(stateKey,JSON.stringify(state));if(cred)localStorage.setItem(sessionKey,cred.id);window.MUMEI_BACKEND_ADMIN=admin;return state}
async function verifyOwner(force=false){let t=ownerToken();if(!t||force){t=prompt('オーナーキーを入力してください')||'';if(!t)return false}try{await rpc('admin_snapshot',{p_owner_token:t,p_series:series()});setOwnerToken(t);return true}catch{setOwnerToken('');alert('オーナーキーが違います。');return false}}
const dataUrlBlob=async src=>(await fetch(src)).blob();
async function uploadBlob(path,blob){const r=await fetch(`${API}/storage/v1/object/creator-images/${path.split('/').map(encodeURIComponent).join('/')}`,{method:'POST',headers:{'apikey':KEY,'Authorization':`Bearer ${KEY}`,'Content-Type':blob.type||'image/webp','x-upsert':'true'},body:blob});if(!r.ok)throw Error(`画像アップロード失敗: ${r.status}`);return path}
async function collectImages(form,kind,id){const imgs=[...form.querySelectorAll('.upload-item img')].slice(0,3),paths=[];for(const img of imgs){const old=imagePath(img.src);if(old){paths.push(old);continue}if(img.src.startsWith('data:')){const blob=await dataUrlBlob(img.src),path=`${kind}/${id}/${crypto.randomUUID()}.webp`;await uploadBlob(path,blob);paths.push(path)}}return paths}
const normId=v=>{const s=String(v||'').trim(),m=s.match(/note\.com\/([\w-]+)/i);return(m?m[1]:s.replace(/^@/,'')).trim()};
const stop=e=>{e.preventDefault();e.stopImmediatePropagation()};
async function reload(hash=location.hash){await buildState();location.hash=hash||'';location.reload()}
function showResult(r){const m=document.querySelector('#modal');if(!m)return;const title=r.result==='win'?'勝利！':r.result==='draw'?'引き分け':'敗北';m.innerHTML=`<div class="modal-shell battle-result"><button class="modal-close" data-live-close>×</button><div class="result-mark">${r.result==='win'?'🏆':r.result==='draw'?'🤝':'⚔️'}</div><p class="eyebrow">BATTLE RESULT</p><h2>${title}</h2><p class="lead">${r.ranked?`ランキング加算対象・今週 ${r.week_rank||'-'}位`:'ゲスト／上限後のためランキング加算なし'}</p><div class="actions" style="justify-content:center"><button class="primary" data-live-reload>ランキングを更新</button></div></div>`;m.showModal()}
window.addEventListener('click',async e=>{try{const adminNav=e.target.closest('[data-nav="admin"]');if(adminNav){stop(e);if(await verifyOwner())return reload('#admin');return}
const close=e.target.closest('[data-live-close]');if(close){stop(e);document.querySelector('#modal')?.close();return}if(e.target.closest('[data-live-reload]')){stop(e);return reload('#battle')}
const play=e.target.closest('[data-play]');if(play){stop(e);const opp=document.querySelector('input[name="opponent"]:checked')?.value,act=document.querySelector('.action-card.selected')?.dataset.action||'strike';if(!opp)return alert('対戦相手を選んでください。');const cred=creatorCred(),r=await rpc('play_catalog_battle',{p_series:series(),p_opponent_id:opp,p_action:act==='strike'?'attack':act,p_participant_id:cred?.id||null,p_edit_token:cred?.token||null});return showResult(r)}
for(const [sel,status] of [['[data-approve]','approved'],['[data-revision]','revision'],['[data-unpublish]','unpublished']]){const b=e.target.closest(sel);if(b){stop(e);if(!await verifyOwner())return;const id=b.dataset.approve||b.dataset.revision||b.dataset.unpublish;await rpc('admin_set_creator_status',{p_owner_token:ownerToken(),p_id:id,p_status:status});return reload('#admin')}}
for(const [sel,status] of [['[data-verify]','verified'],['[data-reject]','revision']]){const b=e.target.closest(sel);if(b){stop(e);if(!await verifyOwner())return;const id=b.dataset.verify||b.dataset.reject;await rpc('admin_verify_article',{p_owner_token:ownerToken(),p_id:id,p_status:status});return reload('#admin')}}
const toggle=e.target.closest('[data-toggle-sengoku]');if(toggle){stop(e);if(!await verifyOwner())return;const current=!!window.MUMEI_SERIES_PUBLIC?.sengoku;if(!confirm(current?'戦国カード名鑑を非公開にしますか？':'戦国カード名鑑を公開しますか？'))return;await rpc('admin_toggle_series',{p_owner_token:ownerToken(),p_series:'sengoku',p_public:!current});return reload('#admin')}
}catch(err){console.error(err);alert(err.message||'処理に失敗しました。')}} ,true);
window.addEventListener('submit',async e=>{try{const f=e.target;if(f.id==='joinForm'){stop(e);const d=new FormData(f),noteId=normId(d.get('noteId'));const r=await rpc('register_creator',{p_series:series(),p_note_id:noteId,p_display_name:String(d.get('displayName')||''),p_intro:String(d.get('intro')||''),p_article1_url:String(d.get('article1Url')||'')});const paths=await collectImages(f,'creator',r.id);if(paths.length)await rpc('set_creator_images',{p_id:r.id,p_edit_token:r.edit_token,p_paths:paths});localStorage.setItem(credKey(series()),JSON.stringify({id:r.id,token:r.edit_token}));localStorage.setItem(sessionKey,r.id);alert('参加申請を受け付けました。');return reload('#mypage')}
if(f.id==='myForm'){stop(e);const c=creatorCred();if(!c)throw Error('編集情報が見つかりません。');const d=new FormData(f);await rpc('update_creator',{p_id:c.id,p_edit_token:c.token,p_display_name:String(d.get('displayName')||''),p_intro:String(d.get('intro')||''),p_article1_url:String(d.get('article1Url')||''),p_article2_url:String(d.get('article2Url')||'')});const paths=await collectImages(f,'creator',c.id);await rpc('set_creator_images',{p_id:c.id,p_edit_token:c.token,p_paths:paths});return reload('#mypage')}
if(f.id==='articleForm'){stop(e);const c=creatorCred();if(!c)throw Error('編集情報が見つかりません。');await rpc('submit_participation_article',{p_id:c.id,p_edit_token:c.token,p_url:String(new FormData(f).get('url')||'')});alert('記事認証を申請しました。');return reload('#mypage')}
if(f.id==='editPForm'){stop(e);if(!await verifyOwner())return;const id=f.dataset.id,d=new FormData(f);await rpc('admin_update_creator',{p_owner_token:ownerToken(),p_id:id,p_display_name:String(d.get('displayName')||''),p_intro:String(d.get('intro')||''),p_job:String(d.get('job')||''),p_rarity:String(d.get('rarity')||'Normal'),p_dialogue_pack:String(d.get('dialoguePack')||'gentle'),p_article1_url:String(d.get('article1Url')||''),p_article2_url:String(d.get('article2Url')||'')});const paths=await collectImages(f,'creator',id);await rpc('admin_set_creator_images',{p_owner_token:ownerToken(),p_id:id,p_paths:paths});return reload('#admin')}
if(f.id==='editOForm'){stop(e);if(!await verifyOwner())return;const id=f.dataset.id,d=new FormData(f);await rpc('admin_update_opponent',{p_owner_token:ownerToken(),p_id:id,p_name:String(d.get('name')||''),p_job:String(d.get('job')||''),p_rarity:String(d.get('rarity')||'Normal'),p_dialogue_pack:String(d.get('dialoguePack')||'gentle'),p_enabled:d.get('enabled')==='on'});const paths=await collectImages(f,'opponent',id);await rpc('admin_set_opponent_image',{p_owner_token:ownerToken(),p_id:id,p_path:paths[0]||''});return reload('#admin')}
if(f.id==='settingsForm'){stop(e);if(!await verifyOwner())return;const d=new FormData(f);await rpc('admin_update_series',{p_owner_token:ownerToken(),p_series:series(),p_title:String(d.get('title')||''),p_hashtag:String(d.get('hashtag')||''),p_started_label:String(d.get('started')||''),p_announcement:String(d.get('announcement')||''),p_rank_daily_limit:Number(d.get('rankDailyLimit')),p_win_percent:Number(d.get('winPercent')),p_draw_percent:Number(d.get('drawPercent')),p_profile_url:String(d.get('profileUrl')||''),p_recruit_url:String(d.get('recruitUrl')||''),p_magazine_url:String(d.get('magazineUrl')||'')});return reload('#admin')}
}catch(err){console.error(err);alert(err.message||'処理に失敗しました。')}},true);
window.MUMEI_BACKEND={rpc,buildState,verifyOwner,ownerToken,publicImage,seriesPublic:()=>window.MUMEI_SERIES_PUBLIC};
window.__MUMEI_BOOT__=buildState().catch(err=>{console.error('[backend boot]',err);return null});
})();