(() => {
'use strict';
const SUPA='https://xxhaerjvrgmnadxjqetz.supabase.co';
const KEY='sb_publishable_yUoJtk-zLMLBZFyBUZehIw_9Bym2Z3w';
const STORAGE=`${SUPA}/storage/v1/object/public/creator-images/`;
const FN=`${SUPA}/functions/v1/catalog-image`;
const H={'Content-Type':'application/json','apikey':KEY,'Authorization':`Bearer ${KEY}`};
const app=document.querySelector('#app'),modal=document.querySelector('#modal'),toastEl=document.querySelector('#toast');
const SERIES=new URLSearchParams(location.search).get('series')==='sengoku'?'sengoku':'adventure';
const SESSION_KEY=`mumei-live-session-${SERIES}`; const OWNER_KEY='mumei-live-owner';
let route=(location.hash||'#home').slice(1),state=null,me=null,admin=null,adminTab='applications',rankPeriod='week',busy=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const img=p=>p?STORAGE+p:''; const label=c=>c.display_name||c.note_id||'名称未設定';
const noteUrl=id=>`https://note.com/${encodeURIComponent(id)}`;
const fmt=d=>new Date(d).toLocaleString('ja-JP',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'});
function toast(s){toastEl.textContent=s;toastEl.classList.add('show');setTimeout(()=>toastEl.classList.remove('show'),2400)}
async function rpc(name,p={}){const r=await fetch(`${SUPA}/rest/v1/rpc/${name}`,{method:'POST',headers:H,body:JSON.stringify(p)});const t=await r.text();if(!r.ok)throw new Error((()=>{try{return JSON.parse(t).message||JSON.parse(t).hint||t}catch{return t}})());return t?JSON.parse(t):null}
async function loadPublic(){state=await rpc('get_public_state',{p_series:SERIES});if(state?.unreleased&&route!=='admin'){location.href='./?series=adventure#home';return false}return true}
function session(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch{return null}}
async function loadMe(){const s=session();if(!s){me=null;return}try{me=await rpc('get_creator_private',{p_id:s.id,p_edit_token:s.token})}catch{me=null}}
function saveSession(v){localStorage.setItem(SESSION_KEY,JSON.stringify(v))}
function go(r){route=r;location.hash=r;render();scrollTo({top:0,behavior:'smooth'})}
function imageBox(path,name){return path?`<img src="${img(path)}" alt="${esc(name)}">`:`<div class="placeholder">S</div>`}
function card(c){return `<article class="creator-card" data-profile="${c.id}"><figure>${imageBox(c.images?.[0],label(c))}<span class="tag rarity">${esc(c.rarity||'Normal')}</span></figure><div class="card-body"><span class="archive">CREATOR ARCHIVE</span><h3>${esc(label(c))}</h3><p>${esc(c.job||'ジョブ設定待ち')}</p>${c.article_status==='verified'?'<span class="badge verified">記事認証済み</span>':''}</div></article>`}
function opponentCard(o){return `<article class="creator-card"><figure>${imageBox(o.image_path,o.name)}<span class="tag rarity">${esc(o.rarity)}</span></figure><div class="card-body"><span class="archive">BATTLE OPPONENT · V${o.version}</span><h3>${esc(o.name)}</h3><p>${esc(o.job||'ジョブ未設定')}</p></div></article>`}
function rankingRows(list=state?.leaderboard_week||[]){return `<div class="rank-list">${list.length?list.map((x,i)=>`<div class="rank-row"><span class="place">${i+1}</span><div><b>${esc(x.display_name)}</b><small>@${esc(x.note_id)} · ${x.battles}戦</small></div><div class="rank-score"><strong>${x.wins}</strong><small>WIN</small></div></div>`).join(''):'<div class="empty">ランキングはまだありません。</div>'}</div>`}
function seriesBadge(){const s=state?.series;return `<div class="series-title"><span>無名S note</span><h1>${esc(s?.main_title||'冒険クリエイター名鑑')}</h1><p>${esc(s?.hashtag||'#無名S名鑑')}<i></i>${esc(s?.started_label||'')}</p></div>`}
function home(){const s=state.series,o=state.opponents?.[0];return `<section class="page"><section class="hero"><div>${seriesBadge()}<h1 class="hero-tagline">才能を見つけ、<br><em>遊びながらつながる。</em></h1><p class="lead">${esc(s.announcement||'')}</p><div class="actions"><button class="primary" data-nav="join">IDだけで参加</button><button class="btn" data-nav="directory">名鑑を見る</button></div></div><div class="hero-stage">${o?`<article class="featured"><div class="art">${imageBox(o.image_path,o.name)}</div><div class="featured-copy"><small>FEATURED SAMPLE OPPONENT</small><h3>${esc(o.name)}</h3><p>${esc(o.job)}</p></div></article>`:''}<div class="float"><small>累計対戦</small><b>${state.battle_total||0}</b><small>回</small></div></div></section><div class="stat-band"><div><b>${state.creators.length}</b><span>公開クリエイター</span></div><div><b>${state.battle_total||0}</b><span>累計対戦</span></div><div><b>1→2</b><span>記事認証でおすすめ枠</span></div><div><b>承認制</b><span>公開前にオーナー確認</span></div></div><section class="section"><div class="section-head"><div><p class="eyebrow">WEEKLY WINNERS</p><h2>今週の勝者ランキング</h2></div><button class="btn" data-nav="battle">対戦する</button></div>${rankingRows()}</section><section class="section"><div class="section-head"><div><p class="eyebrow">SAMPLE OPPONENTS</p><h2>無名S noteの3カード</h2></div></div><div class="creator-grid">${state.opponents.map(opponentCard).join('')}</div></section><section class="section"><div class="section-head"><div><p class="eyebrow">NEW CREATORS</p><h2>新着クリエイター</h2></div></div><div class="creator-grid">${state.creators.slice(0,6).map(card).join('')||'<div class="empty">最初の参加者を募集中です。</div>'}</div></section></section>`}
function directory(){return `<section class="page"><header class="page-title"><p class="eyebrow">CREATOR DIRECTORY</p><h1>${esc(state.series.main_title)}</h1><p class="lead">公開承認済みのクリエイターを掲載しています。</p></header><div class="creator-grid">${state.creators.map(card).join('')||'<div class="empty">まだ公開クリエイターはいません。</div>'}</div></section>`}
function join(){return `<section class="page narrow"><header class="page-title"><p class="eyebrow">QUICK ENTRY</p><h1>IDだけで参加申請</h1><p class="lead">最初に必要なのはnoteクリエイターIDだけ。パスワードやSupabase登録は不要です。</p></header><form class="panel gold" id="joinForm"><div class="form-grid"><label class="form-label full"><span>noteクリエイターID（必須）</span><input class="field" name="noteId" required placeholder="例：ss_yr またはプロフィールURL"></label><label class="form-label"><span>表示名（任意）</span><input class="field" name="displayName"></label><label class="form-label"><span>おすすめ記事①（任意）</span><input class="field" name="article1Url" placeholder="https://note.com/..."></label><label class="form-label full"><span>ひとこと（任意）</span><textarea class="field" name="intro" maxlength="300"></textarea></label></div><div class="actions"><button class="primary" type="submit">参加申請する</button></div></form></section>`}
function fileUploader(title='カード画像'){return `<div class="uploader"><div class="uploader-head"><div><b>${title}</b><small class="help">最大3枚。アップロード後は全端末に反映されます。</small></div></div><input class="field" id="creatorFiles" type="file" accept="image/jpeg,image/png,image/webp" multiple></div>`}
function mypage(){if(!me)return `<section class="page narrow"><header class="page-title"><h1>マイページ</h1></header><div class="panel"><p class="lead">この端末には参加情報がありません。</p><button class="primary" data-nav="join">参加申請へ</button></div></section>`;const imgs=me.images||[];return `<section class="page"><header class="page-title"><p class="eyebrow">MY CREATOR PAGE</p><h1>${esc(label(me))}</h1><p class="lead">状態：${esc(me.status)} ／ 記事認証：${esc(me.article_status)}</p></header><div class="grid cols-2"><form class="panel" id="myForm"><h3>プロフィール</h3><div class="form-grid"><label class="form-label"><span>表示名</span><input class="field" name="displayName" value="${esc(me.display_name)}"></label><label class="form-label"><span>おすすめ記事①</span><input class="field" name="article1Url" value="${esc(me.article1_url)}"></label><label class="form-label full"><span>ひとこと</span><textarea class="field" name="intro">${esc(me.intro)}</textarea></label>${me.article_status==='verified'?`<label class="form-label full"><span>おすすめ記事②（認証特典）</span><input class="field" name="article2Url" value="${esc(me.article2_url)}"></label>`:''}</div><div class="actions"><button class="primary">保存</button></div></form><div class="panel"><h3>カード画像</h3><div class="upload-grid">${[0,1,2].map(i=>`<div class="upload-item">${imgs[i]?`<img src="${img(imgs[i])}">`:`<span class="upload-empty">画像${i+1}</span>`}</div>`).join('')}</div><div style="margin-top:14px">${fileUploader()}</div></div></div><section class="section"><form class="panel gold" id="articleForm"><h3>参加記事認証</h3><p class="lead">参加記事のURLを送信し、オーナーが確認すると「記事認証済み」になり、おすすめ記事②が解放されます。</p><input class="field" name="url" placeholder="https://note.com/..." value="${esc(me.participation_article_url)}"><div class="actions"><button class="primary">認証を申請</button></div></form></section></section>`}
const actions={attack:['⚔','攻める'],guard:['🛡','守る'],special:['✨','必殺技']};let selectedOpponent=null,selectedAction='attack';
function battle(){if(!selectedOpponent)selectedOpponent=state.opponents?.[0]?.id;return `<section class="page"><header class="page-title"><p class="eyebrow">RANDOM CREATOR BATTLE</p><h1>冒険カード対戦</h1><p class="lead">カード性能は勝率に影響しません。DB側でランダム判定します。</p></header><section class="section"><h2>対戦相手を選ぶ</h2><div class="creator-grid">${state.opponents.map(o=>`<label class="panel ${o.id===selectedOpponent?'gold':''}" style="padding:0;cursor:pointer"><input class="sr-only" type="radio" name="opponent" value="${o.id}" ${o.id===selectedOpponent?'checked':''}>${opponentCard(o)}</label>`).join('')}</div></section><section class="section"><h2>行動を選ぶ</h2><div class="action-grid">${Object.entries(actions).map(([k,v])=>`<button class="action-card ${k===selectedAction?'selected':''}" data-action="${k}"><span style="font-size:28px">${v[0]}</span><b>${v[1]}</b><span class="small">演出のみ。勝率は同じです。</span></button>`).join('')}</div><div class="actions"><button class="primary" data-play>この内容で対戦</button></div></section><section class="section"><div class="tabs"><button class="tab ${rankPeriod==='week'?'active':''}" data-period="week">今週</button><button class="tab ${rankPeriod==='today'?'active':''}" data-period="today">今日</button><button class="tab ${rankPeriod==='all'?'active':''}" data-period="all">累計</button></div><div id="rankingBox">${rankingRows()}</div></section></section>`}
function profile(c){const links=[[c.article1_url,'おすすめ記事①'],[c.article_status==='verified'?c.article2_url:'','おすすめ記事②'],[c.article_status==='verified'?c.participation_article_url:'','参加記事']].filter(x=>x[0]);modal.innerHTML=`<div class="modal-shell"><button class="modal-close" data-close>×</button><div class="profile-layout"><div class="gallery-main">${imageBox(c.images?.[0],label(c))}</div><div><p class="eyebrow">CREATOR ID · ${esc(c.note_id)}</p><h2>${esc(label(c))}</h2><p style="color:var(--gold)">${esc(c.job||'ジョブ設定待ち')} · ${esc(c.rarity)}</p>${c.article_status==='verified'?'<span class="badge verified">参加記事認証済み・おすすめ2枠</span>':'<span class="badge">おすすめ1枠</span>'}<p class="lead">${esc(c.intro||'')}</p><div class="article-list">${links.map(([u,t])=>`<a class="article-link" href="${esc(u)}" target="_blank" rel="noopener"><b>${t}</b><span>→</span></a>`).join('')||'<div class="empty">記事はまだ登録されていません。</div>'}</div><div class="actions"><a class="btn" target="_blank" rel="noopener" href="${noteUrl(c.note_id)}">noteプロフィール</a></div></div></div></div>`;modal.showModal()}
async function adminLoad(token){admin=await rpc('admin_snapshot',{p_owner_token:token,p_series:SERIES});localStorage.setItem(OWNER_KEY,token)}
function adminLogin(){return `<section class="page narrow"><header class="page-title"><p class="eyebrow">OWNER CONTROL</p><h1>オーナー管理</h1></header><form class="panel gold" id="ownerLogin"><label class="form-label"><span>オーナーキー</span><input class="field" name="token" type="password" autocomplete="current-password" required></label><div class="actions"><button class="primary">管理画面を開く</button></div></form></section>`}
function adminApplications(){const x=admin.creators.filter(c=>c.status==='pending'||c.status==='revision');return `<section class="panel"><h3>参加申請</h3><div class="admin-list">${x.map(c=>`<div class="admin-item"><div><h4>${esc(label(c))}</h4><p>@${esc(c.note_id)} · ${fmt(c.created_at)}</p></div><div class="admin-actions"><button class="primary" data-status="approved" data-id="${c.id}">承認</button><button class="danger" data-status="revision" data-id="${c.id}">修正依頼</button></div></div>`).join('')||'<div class="empty">確認待ちはありません。</div>'}</div></section>`}
function adminArticles(){const x=admin.creators.filter(c=>c.article_status==='pending');return `<section class="panel"><h3>参加記事認証</h3><div class="admin-list">${x.map(c=>`<div class="admin-item"><div><h4>${esc(label(c))}</h4><p>${esc(c.participation_article_url)}</p></div><div class="admin-actions"><a class="btn" href="${esc(c.participation_article_url)}" target="_blank">記事確認</a><button class="primary" data-article="verified" data-id="${c.id}">認証</button><button class="danger" data-article="revision" data-id="${c.id}">修正依頼</button></div></div>`).join('')||'<div class="empty">記事認証待ちはありません。</div>'}</div></section>`}
function adminOpponents(){return `<section class="panel"><h3>見本カード3枚</h3><p class="lead">画像・ジョブ・レア度・セリフパックを管理します。</p><div class="creator-grid">${admin.opponents.map(o=>`<div><div data-opcard>${opponentCard(o)}</div><form class="panel" data-opform="${o.id}"><input class="field" name="name" value="${esc(o.name)}"><input class="field" name="job" value="${esc(o.job)}" placeholder="ジョブ"><select class="field" name="rarity">${['Normal','Rare','SR','SSR','Dream SSR','Legend SSR'].map(r=>`<option ${r===o.rarity?'selected':''}>${r}</option>`).join('')}</select><select class="field" name="dialogue"><option value="gentle" ${o.dialogue_pack==='gentle'?'selected':''}>やさしい応援</option><option value="brave" ${o.dialogue_pack==='brave'?'selected':''}>王道勇者</option><option value="cool" ${o.dialogue_pack==='cool'?'selected':''}>冷静</option><option value="mystical" ${o.dialogue_pack==='mystical'?'selected':''}>神秘</option></select><label class="form-label"><span>画像</span><input class="field" type="file" name="image" accept="image/*"></label><div class="actions"><button class="primary">保存</button></div></form></div>`).join('')}</div></section>`}
function adminSettings(){const s=admin.series;return `<section class="grid cols-2"><form class="panel" id="settingsForm"><h3>冒険名鑑設定</h3><label class="form-label"><span>タイトル</span><input class="field" name="title" value="${esc(s.title)}"></label><label class="form-label"><span>ハッシュタグ</span><input class="field" name="hashtag" value="${esc(s.hashtag)}"></label><label class="form-label"><span>開始表示</span><input class="field" name="started" value="${esc(s.started_label)}"></label><label class="form-label"><span>お知らせ</span><textarea class="field" name="announcement">${esc(s.announcement)}</textarea></label><div class="form-grid"><label class="form-label"><span>1日加算上限</span><input class="field" type="number" name="limit" value="${s.rank_daily_limit}"></label><label class="form-label"><span>勝率%</span><input class="field" type="number" name="win" value="${s.win_percent}"></label><label class="form-label"><span>引分%</span><input class="field" type="number" name="draw" value="${s.draw_percent}"></label></div><input type="hidden" name="profile" value="${esc(s.profile_url)}"><input type="hidden" name="recruit" value="${esc(s.recruit_url)}"><input type="hidden" name="magazine" value="${esc(s.magazine_url)}"><div class="actions"><button class="primary">設定保存</button></div></form><div class="panel gold"><h3>戦国カード名鑑</h3><p class="lead">現在は${SERIES==='sengoku'?(s.is_public?'公開中':'非公開'): '別シリーズとして管理'}。戦国を開始するときだけONにできます。</p><button class="${SERIES==='sengoku'&&s.is_public?'danger':'primary'}" data-toggle-series>${SERIES==='sengoku'&&s.is_public?'非公開OFFにする':'戦国管理へ'}</button></div></section>`}
function adminPage(){if(!admin)return adminLogin();const tabs=[['applications','参加申請'],['articles','記事認証'],['opponents','見本カード'],['settings','設定']];let content=adminTab==='applications'?adminApplications():adminTab==='articles'?adminArticles():adminTab==='opponents'?adminOpponents():adminSettings();return `<section class="page"><header class="page-title"><p class="eyebrow">OWNER CONTROL</p><h1>オーナー管理</h1><p class="lead">共有DB接続済み。ここでの操作は全端末へ反映されます。</p></header><div class="tabs">${tabs.map(([k,t])=>`<button class="tab ${adminTab===k?'active':''}" data-admintab="${k}">${t}</button>`).join('')}</div>${content}</section>`}
function render(){document.querySelectorAll('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===route));app.innerHTML=route==='directory'?directory():route==='join'?join():route==='mypage'?mypage():route==='battle'?battle():route==='admin'?adminPage():home()}
async function refresh(){await loadPublic();await loadMe();render()}
function normId(v){const s=String(v||'').trim();const m=s.match(/note\.com\/([\w-]+)/i);return(m?m[1]:s.replace(/^@/,'')).trim()}
function validNote(u){if(!u)return true;try{const x=new URL(u);return x.protocol==='https:'&&x.hostname==='note.com'}catch{return false}}
async function compress(file){return new Promise((res,rej)=>{const im=new Image(),fr=new FileReader();fr.onload=()=>im.src=fr.result;fr.onerror=rej;im.onload=()=>{const max=1800,scale=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.round(im.width*scale);c.height=Math.round(im.height*scale);c.getContext('2d').drawImage(im,0,0,c.width,c.height);res(c.toDataURL('image/webp',.9))};fr.readAsDataURL(file)})}
async function uploadCreatorFiles(files){const s=session();if(!s)return;const a=[...files].slice(0,3);for(let i=0;i<a.length;i++){toast(`画像${i+1}をアップロード中…`);const dataUrl=await compress(a[i]);const r=await fetch(FN,{method:'POST',headers:H,body:JSON.stringify({mode:'creator',id:s.id,token:s.token,position:i,dataUrl})});if(!r.ok)throw new Error(await r.text())}await loadMe();render();toast('画像を共有保存しました')}
async function uploadOpponent(o,file,token){if(!file)return;const dataUrl=await compress(file);const r=await fetch(FN,{method:'POST',headers:H,body:JSON.stringify({mode:'opponent',id:o,token,dataUrl})});if(!r.ok)throw new Error(await r.text())}
document.addEventListener('click',async e=>{try{const nav=e.target.closest('[data-nav]');if(nav)return go(nav.dataset.nav);if(e.target.closest('[data-close]'))return modal.close();const p=e.target.closest('[data-profile]');if(p){const c=state.creators.find(x=>x.id===p.dataset.profile);if(c)return profile(c)}const a=e.target.closest('[data-action]');if(a){selectedAction=a.dataset.action;return render()}if(e.target.name==='opponent'){selectedOpponent=e.target.value;return render()}const play=e.target.closest('[data-play]');if(play){if(busy)return;busy=true;const s=session();const r=await rpc('play_catalog_battle',{p_series:SERIES,p_opponent_id:selectedOpponent,p_action:selectedAction,p_participant_id:s?.id||null,p_edit_token:s?.token||null});await loadPublic();const mark=r.result==='win'?'🏆':r.result==='draw'?'🤝':'⚔️';modal.innerHTML=`<div class="modal-shell battle-result"><button class="modal-close" data-close>×</button><div class="result-mark">${mark}</div><h2>${r.result==='win'?'勝利！':r.result==='draw'?'引き分け':'敗北'}</h2><p class="lead">${r.ranked?`ランキング加算対象・今週${r.week_rank}位`:'ゲスト／上限後のためランキング加算なし'}</p><div class="actions" style="justify-content:center"><button class="primary" data-close>戻る</button></div></div>`;modal.showModal();busy=false;return}const per=e.target.closest('[data-period]');if(per){rankPeriod=per.dataset.period;const list=await rpc('get_leaderboard',{p_series:SERIES,p_period:rankPeriod});document.querySelector('#rankingBox').innerHTML=rankingRows(list);document.querySelectorAll('[data-period]').forEach(x=>x.classList.toggle('active',x.dataset.period===rankPeriod));return}const at=e.target.closest('[data-admintab]');if(at){adminTab=at.dataset.admintab;return render()}const st=e.target.closest('[data-status]');if(st){const token=localStorage.getItem(OWNER_KEY);await rpc('admin_set_creator_status',{p_owner_token:token,p_id:st.dataset.id,p_status:st.dataset.status});await adminLoad(token);await loadPublic();render();toast('参加状態を更新しました');return}const ar=e.target.closest('[data-article]');if(ar){const token=localStorage.getItem(OWNER_KEY);await rpc('admin_verify_article',{p_owner_token:token,p_id:ar.dataset.id,p_status:ar.dataset.article});await adminLoad(token);await loadPublic();render();toast('記事認証を更新しました');return}const tg=e.target.closest('[data-toggle-series]');if(tg){if(SERIES!=='sengoku'){location.href='./?series=sengoku#admin';return}const token=localStorage.getItem(OWNER_KEY),next=!admin.series.is_public;if(!confirm(next?'戦国カード名鑑を公開しますか？':'戦国カード名鑑を非公開にしますか？'))return;await rpc('admin_toggle_series',{p_owner_token:token,p_series:'sengoku',p_public:next});await adminLoad(token);render();return}}catch(err){busy=false;toast(`エラー：${err.message}`)}});
document.addEventListener('change',e=>{if(e.target.id==='creatorFiles'&&e.target.files?.length)uploadCreatorFiles(e.target.files).catch(x=>toast(`画像エラー：${x.message}`));if(e.target.name==='opponent'){selectedOpponent=e.target.value;render()}});
document.addEventListener('submit',async e=>{e.preventDefault();try{if(busy)return;busy=true;const f=new FormData(e.target);if(e.target.id==='joinForm'){const id=normId(f.get('noteId')),u=String(f.get('article1Url')||'').trim();if(!validNote(u))throw new Error('note記事URLを確認してください');const r=await rpc('register_creator',{p_series:SERIES,p_note_id:id,p_display_name:String(f.get('displayName')||''),p_intro:String(f.get('intro')||''),p_article1_url:u});saveSession({id:r.id,token:r.edit_token});await refresh();go('mypage');toast('参加申請を受け付けました')}else if(e.target.id==='myForm'){const s=session(),a1=String(f.get('article1Url')||''),a2=String(f.get('article2Url')||'');if(!validNote(a1)||!validNote(a2))throw new Error('note記事URLを確認してください');await rpc('update_creator',{p_id:s.id,p_edit_token:s.token,p_display_name:String(f.get('displayName')||''),p_intro:String(f.get('intro')||''),p_article1_url:a1,p_article2_url:a2});await loadMe();render();toast('保存しました')}else if(e.target.id==='articleForm'){const s=session(),u=String(f.get('url')||'');if(!validNote(u)||!u)throw new Error('参加記事URLを確認してください');await rpc('submit_participation_article',{p_id:s.id,p_edit_token:s.token,p_url:u});await loadMe();render();toast('記事認証を申請しました')}else if(e.target.id==='ownerLogin'){const token=String(f.get('token')||'');await adminLoad(token);render();toast('管理画面を開きました')}else if(e.target.matches('[data-opform]')){const token=localStorage.getItem(OWNER_KEY),id=e.target.dataset.opform,file=f.get('image');await rpc('admin_update_opponent',{p_owner_token:token,p_id:id,p_name:String(f.get('name')||''),p_job:String(f.get('job')||''),p_rarity:String(f.get('rarity')||'Normal'),p_dialogue_pack:String(f.get('dialogue')||'gentle'),p_enabled:true});if(file&&file.size)await uploadOpponent(id,file,token);await adminLoad(token);await loadPublic();render();toast('見本カードを保存しました')}else if(e.target.id==='settingsForm'){const token=localStorage.getItem(OWNER_KEY);await rpc('admin_update_series',{p_owner_token:token,p_series:SERIES,p_title:String(f.get('title')),p_hashtag:String(f.get('hashtag')),p_started_label:String(f.get('started')),p_announcement:String(f.get('announcement')),p_rank_daily_limit:Number(f.get('limit')),p_win_percent:Number(f.get('win')),p_draw_percent:Number(f.get('draw')),p_profile_url:String(f.get('profile')),p_recruit_url:String(f.get('recruit')),p_magazine_url:String(f.get('magazine'))});await adminLoad(token);await loadPublic();render();toast('設定を保存しました')}busy=false}catch(err){busy=false;toast(`エラー：${err.message}`)}});
window.addEventListener('hashchange',()=>{route=(location.hash||'#home').slice(1);render()});
(async()=>{try{await loadPublic();await loadMe();if(route==='admin'){const t=localStorage.getItem(OWNER_KEY);if(t)try{await adminLoad(t)}catch{localStorage.removeItem(OWNER_KEY)}}render()}catch(err){app.innerHTML=`<section class="page narrow"><div class="panel"><h1>接続エラー</h1><p class="lead">${esc(err.message)}</p></div></section>`}})();
})();
